// Code generated by bm2rust of https://github.com/on-keyday/rebrgen
#[derive(Debug)]
pub enum Error {
    PropertySetterError(&'static str),
    EncodeError(&'static str, std::io::Error),
    DecodeError(&'static str, std::io::Error),
    TryFromIntError(std::num::TryFromIntError),
    ArrayLengthMismatch(&'static str,usize /*expected*/,usize /*actual*/),
    AssertError(&'static str),
    InvalidUnionVariant(&'static str),
    BackwardError(usize,usize),
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::PropertySetterError(s) => write!(f, "PropertySetterError: {}", s),
            Error::EncodeError(s,e) => write!(f, "EncodeError: {} {}", s,e),
            Error::DecodeError(s,e) => write!(f, "DecodeError: {} {}", s,e),
            Error::TryFromIntError(e) => write!(f, "TryFromIntError: {}", e),
            Error::ArrayLengthMismatch(s,expected,actual) => write!(f, "ArrayLengthMismatch: {} expected:{} actual:{}", s,expected,actual),
            Error::AssertError(s) => write!(f, "AssertError: {}", s),
            Error::InvalidUnionVariant(s) => write!(f, "InvalidUnionVariant: {}", s),
            Error::BackwardError(expected,actual) => write!(f, "BackwardError: expected:{} actual:{}", expected,actual),
        }
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Error::EncodeError(_,e) => Some(e),
            Error::DecodeError(_,e) => Some(e),
            Error::TryFromIntError(e) => Some(e),
            Error::PropertySetterError(_) => None,
            Error::ArrayLengthMismatch(_,_,_) => None,
            Error::AssertError(_) => None,
            Error::InvalidUnionVariant(_) => None,
            Error::BackwardError(_,_) => None,
        }
    }
}
impl From<std::num::TryFromIntError> for Error {
    fn from(e: std::num::TryFromIntError) -> Self {
        Error::TryFromIntError(e)
    }
}
impl From<std::convert::Infallible> for Error {
    fn from(_: std::convert::Infallible) -> Self {
        unreachable!()
    }
}
/* Unimplemented op: IMMEDIATE_STRING */
#[derive(Debug,Default, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub struct LogLevel(u8);
impl LogLevel  {
    pub const TRACE:Self = Self(0);
    pub const DEBUG:Self = Self(1);
    pub const INFO:Self = Self(2);
    pub const WARN:Self = Self(3);
    pub const ERROR:Self = Self(4);
}
impl std::fmt::Display for LogLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match *self {
            LogLevel::TRACE => write!(f, "{}", "TRACE"),
            LogLevel::DEBUG => write!(f, "{}", "DEBUG"),
            LogLevel::INFO => write!(f, "{}", "INFO"),
            LogLevel::WARN => write!(f, "{}", "WARN"),
            LogLevel::ERROR => write!(f, "{}", "ERROR"),
            _ => write!(f, "LogLevel({})",self.0),
        }
    }
}
impl std::convert::From<LogLevel> for std::option::Option<&str> {
    fn from(e: LogLevel) -> Self {
        match e {
            LogLevel::TRACE => Some("TRACE"),
            LogLevel::DEBUG => Some("DEBUG"),
            LogLevel::INFO => Some("INFO"),
            LogLevel::WARN => Some("WARN"),
            LogLevel::ERROR => Some("ERROR"),
            _ =>  None,
        }
    }
}
impl LogLevel {
    pub fn is_known(&self) -> bool {
        match *self {
            LogLevel::TRACE => true,
            LogLevel::DEBUG => true,
            LogLevel::INFO => true,
            LogLevel::WARN => true,
            LogLevel::ERROR => true,
            _ => false,
        }
    }
}
impl std::convert::From<u8> for LogLevel {
    fn from(e: u8) -> Self {
        Self(e)
    }
}
impl std::convert::From<LogLevel> for u8 {
    fn from(e: LogLevel) -> Self {
        e.0
    }
}
#[derive(Debug,Default, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub struct Protocol(u8);
impl Protocol  {
    pub const http1_plain:Self = Self(0);
    pub const http1:Self = Self(1);
    pub const h2:Self = Self(2);
    pub const h3:Self = Self(3);
    pub const other:Self = Self(255);
}
impl std::fmt::Display for Protocol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match *self {
            Protocol::http1_plain => write!(f, "{}", "http1_plain"),
            Protocol::http1 => write!(f, "{}", "http1"),
            Protocol::h2 => write!(f, "{}", "h2"),
            Protocol::h3 => write!(f, "{}", "h3"),
            Protocol::other => write!(f, "{}", "other"),
            _ => write!(f, "Protocol({})",self.0),
        }
    }
}
impl std::convert::From<Protocol> for std::option::Option<&str> {
    fn from(e: Protocol) -> Self {
        match e {
            Protocol::http1_plain => Some("http1_plain"),
            Protocol::http1 => Some("http1"),
            Protocol::h2 => Some("h2"),
            Protocol::h3 => Some("h3"),
            Protocol::other => Some("other"),
            _ =>  None,
        }
    }
}
impl Protocol {
    pub fn is_known(&self) -> bool {
        match *self {
            Protocol::http1_plain => true,
            Protocol::http1 => true,
            Protocol::h2 => true,
            Protocol::h3 => true,
            Protocol::other => true,
            _ => false,
        }
    }
}
impl std::convert::From<u8> for Protocol {
    fn from(e: u8) -> Self {
        Self(e)
    }
}
impl std::convert::From<Protocol> for u8 {
    fn from(e: Protocol) -> Self {
        e.0
    }
}
#[derive(Debug,Default, Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub struct Method(u8);
impl Method  {
    pub const GET:Self = Self(0);
    pub const POST:Self = Self(1);
    pub const PUT:Self = Self(2);
    pub const HEAD:Self = Self(3);
    pub const OPTIONS:Self = Self(4);
    pub const PATCH:Self = Self(5);
    pub const DELETE:Self = Self(6);
    pub const CONNECT:Self = Self(7);
    pub const PRI:Self = Self(8);
    pub const TRACE:Self = Self(9);
    pub const OTHER:Self = Self(255);
}
impl std::fmt::Display for Method {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match *self {
            Method::GET => write!(f, "{}", "GET"),
            Method::POST => write!(f, "{}", "POST"),
            Method::PUT => write!(f, "{}", "PUT"),
            Method::HEAD => write!(f, "{}", "HEAD"),
            Method::OPTIONS => write!(f, "{}", "OPTIONS"),
            Method::PATCH => write!(f, "{}", "PATCH"),
            Method::DELETE => write!(f, "{}", "DELETE"),
            Method::CONNECT => write!(f, "{}", "CONNECT"),
            Method::PRI => write!(f, "{}", "PRI"),
            Method::TRACE => write!(f, "{}", "TRACE"),
            Method::OTHER => write!(f, "{}", "OTHER"),
            _ => write!(f, "Method({})",self.0),
        }
    }
}
impl std::convert::From<Method> for std::option::Option<&str> {
    fn from(e: Method) -> Self {
        match e {
            Method::GET => Some("GET"),
            Method::POST => Some("POST"),
            Method::PUT => Some("PUT"),
            Method::HEAD => Some("HEAD"),
            Method::OPTIONS => Some("OPTIONS"),
            Method::PATCH => Some("PATCH"),
            Method::DELETE => Some("DELETE"),
            Method::CONNECT => Some("CONNECT"),
            Method::PRI => Some("PRI"),
            Method::TRACE => Some("TRACE"),
            Method::OTHER => Some("OTHER"),
            _ =>  None,
        }
    }
}
impl Method {
    pub fn is_known(&self) -> bool {
        match *self {
            Method::GET => true,
            Method::POST => true,
            Method::PUT => true,
            Method::HEAD => true,
            Method::OPTIONS => true,
            Method::PATCH => true,
            Method::DELETE => true,
            Method::CONNECT => true,
            Method::PRI => true,
            Method::TRACE => true,
            Method::OTHER => true,
            _ => false,
        }
    }
}
impl std::convert::From<u8> for Method {
    fn from(e: u8) -> Self {
        Self(e)
    }
}
impl std::convert::From<Method> for u8 {
    fn from(e: Method) -> Self {
        e.0
    }
}
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
/* Unimplemented op: DECLARE_FORMAT */
#[derive(Debug,Default, Clone, PartialEq, Eq)]
struct Variant33<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    pub len: u8,
    pub protocol_name: std::borrow::Cow<'a,[u8]>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
enum Variant32<'a> {
    #[default]
    None,
    Variant33(Variant33<'a>),
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
struct Variant81<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    pub len: u8,
    pub method_name: std::borrow::Cow<'a,[u8]>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
enum Variant80<'a> {
    #[default]
    None,
    Variant81(Variant81<'a>),
}
impl <'a>Address<'a> {
    pub fn is_v6(&self) -> bool {
        ((self.field_118>>7) & 1) as u8 != 0}
    pub fn set_is_v6(&mut self, value: bool) -> bool {
        self.field_118 = self.field_118& !(1<< 7) | ((if value {1} else {0} as u8) << 7);
        true
    }
}
impl <'a>Address<'a> {
    pub fn reserved(&self) -> u8 {
        ((self.field_118>>0) & 127) as u8}
    pub fn set_reserved(&mut self, value: u8) -> bool {
        if value > 127 {
        return false;
        }
        self.field_118 = self.field_118& !(127<< 0) | ((value as u8) << 0);
        true
    }
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
struct Variant125<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    pub addr_v6: [u8; 16],
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
struct Variant128<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    pub addr_v4: [u8; 4],
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
enum Variant124<'a> {
    #[default]
    None,
    Variant125(Variant125<'a>),
    Variant128(Variant128<'a>),
}
/* Unimplemented op: IMMEDIATE_STRING */
/* Unimplemented op: METADATA */
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct ProtocolInfo<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub protocol: Protocol,
    pub field31: Variant32<'a>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct MethodInfo<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub method: Method,
    pub field79: Variant80<'a>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct String<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub len: u16,
    pub data: std::borrow::Cow<'a,[u8]>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct Body<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub len: u32,
    pub body: std::borrow::Cow<'a,[u8]>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct Address<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    field_118 :u8,/*is_v6 :1*/
    /*reserved :7*/
    
    
    pub field123: Variant124<'a>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct Field<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub key: String<'a>,
    pub value: String<'a>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct Header<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub len: u16,
    pub fields: std::borrow::Cow<'a,[Field<'a>]>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct ResponseInfo<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub status: u16,
    pub header: Header<'a>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct PathInfo<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub path: String<'a>,
    pub query_len: u8,
    pub query: std::borrow::Cow<'a,[Field<'a>]>,
}
#[derive(Debug,Default, Clone, PartialEq, Eq)]
pub struct RequestInfo<'a> {
    pub _phantom: std::marker::PhantomData<&'a ()>,
    /* Unimplemented op: DEFINE_ENCODER */
    /* Unimplemented op: DEFINE_DECODER */
    pub popID: u32,
    pub reqID: u64,
    pub protocol: ProtocolInfo<'a>,
    pub remoteAddr: Address<'a>,
    pub remotePort: u16,
    pub method: MethodInfo<'a>,
    pub path: PathInfo<'a>,
    pub header: Header<'a>,
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>ProtocolInfo<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        let mut tmp408 = <[u8; 1]>::default();
        (tmp408)[0 as usize] = u8::from(self.protocol);
        w.write_all(&tmp408[0..1 as usize]).map_err(|e| Error::EncodeError("ProtocolInfo::protocol",e))?;
        if (self.protocol == Protocol::other) {
            if !matches!(self.field31,Variant32::Variant33(_)) {
                return Err(Error::InvalidUnionVariant("Variant32::Variant33"));
            }
            let mut tmp413 = <[u8; 1]>::default();
            (tmp413)[0 as usize] = match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len;
            w.write_all(&tmp413[0..1 as usize]).map_err(|e| Error::EncodeError("ProtocolInfo::Variant32::Variant33::len",e))?;
            let mut tmp168 = match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len;
            if match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name.len() != tmp168 as usize {
            return Err(Error::ArrayLengthMismatch("encode ProtocolInfo::Variant32::Variant33::protocol_name", tmp168 as usize, match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name.len()));
            }
            w.write_all(&match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name[0..match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name.len() as usize]).map_err(|e| Error::EncodeError("ProtocolInfo::Variant32::Variant33::protocol_name",e))?;
        }
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>MethodInfo<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        let mut tmp418 = <[u8; 1]>::default();
        (tmp418)[0 as usize] = u8::from(self.method);
        w.write_all(&tmp418[0..1 as usize]).map_err(|e| Error::EncodeError("MethodInfo::method",e))?;
        if (self.method == Method::OTHER) {
            if !matches!(self.field79,Variant80::Variant81(_)) {
                return Err(Error::InvalidUnionVariant("Variant80::Variant81"));
            }
            let mut tmp423 = <[u8; 1]>::default();
            (tmp423)[0 as usize] = match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len;
            w.write_all(&tmp423[0..1 as usize]).map_err(|e| Error::EncodeError("MethodInfo::Variant80::Variant81::len",e))?;
            let mut tmp176 = match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len;
            if match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name.len() != tmp176 as usize {
            return Err(Error::ArrayLengthMismatch("encode MethodInfo::Variant80::Variant81::method_name", tmp176 as usize, match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name.len()));
            }
            w.write_all(&match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name[0..match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name.len() as usize]).map_err(|e| Error::EncodeError("MethodInfo::Variant80::Variant81::method_name",e))?;
        }
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>PathInfo<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        self.path.encode(w)?;
        let mut tmp428 = <[u8; 1]>::default();
        (tmp428)[0 as usize] = self.query_len;
        w.write_all(&tmp428[0..1 as usize]).map_err(|e| Error::EncodeError("PathInfo::query_len",e))?;
        let mut tmp179 = self.query_len;
        if self.query.len() != tmp179 as usize {
        return Err(Error::ArrayLengthMismatch("encode PathInfo::query", tmp179 as usize, self.query.len()));
        }
        let mut tmp180 = 0;
        while((tmp180 < self.query.len())) {
            (self.query)[tmp180 as usize].encode(w)?;
            tmp180+= 1;
        }
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>String<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        let mut tmp434 = <[u8; 2]>::default();
        let mut tmp435 = 0;
        while((tmp435 < 2)) {
            (tmp434)[tmp435 as usize] = (((self.len >> (tmp435 * 8)) & 255) as u8);
            tmp435+= 1;
        }
        w.write_all(&tmp434[0..2 as usize]).map_err(|e| Error::EncodeError("String::len",e))?;
        let mut tmp185 = self.len;
        if self.data.len() != tmp185 as usize {
        return Err(Error::ArrayLengthMismatch("encode String::data", tmp185 as usize, self.data.len()));
        }
        w.write_all(&self.data[0..self.data.len() as usize]).map_err(|e| Error::EncodeError("String::data",e))?;
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
impl <'a>Field<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        self.key.encode(w)?;
        self.value.encode(w)?;
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>Header<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        let mut tmp445 = <[u8; 2]>::default();
        let mut tmp446 = 0;
        while((tmp446 < 2)) {
            (tmp445)[tmp446 as usize] = (((self.len >> (tmp446 * 8)) & 255) as u8);
            tmp446+= 1;
        }
        w.write_all(&tmp445[0..2 as usize]).map_err(|e| Error::EncodeError("Header::len",e))?;
        let mut tmp189 = self.len;
        if self.fields.len() != tmp189 as usize {
        return Err(Error::ArrayLengthMismatch("encode Header::fields", tmp189 as usize, self.fields.len()));
        }
        let mut tmp190 = 0;
        while((tmp190 < self.fields.len())) {
            (self.fields)[tmp190 as usize].encode(w)?;
            tmp190+= 1;
        }
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>Body<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        let mut tmp456 = <[u8; 4]>::default();
        let mut tmp457 = 0;
        while((tmp457 < 4)) {
            (tmp456)[tmp457 as usize] = (((self.len >> (tmp457 * 8)) & 255) as u8);
            tmp457+= 1;
        }
        w.write_all(&tmp456[0..4 as usize]).map_err(|e| Error::EncodeError("Body::len",e))?;
        let mut tmp195 = self.len;
        if self.body.len() != tmp195 as usize {
        return Err(Error::ArrayLengthMismatch("encode Body::body", tmp195 as usize, self.body.len()));
        }
        w.write_all(&self.body[0..self.body.len() as usize]).map_err(|e| Error::EncodeError("Body::body",e))?;
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
impl <'a>Address<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        let mut tmp366 = <u8>::default();
        let mut tmp368 = 0;
        tmp366 = (tmp366 | ((if self.is_v6() {1} else {0} & 1) << tmp368));
        tmp368 = (tmp368 + 1);
        tmp366 = (tmp366 | (((self.reserved() as u8) & 127) << tmp368));
        tmp368 = (tmp368 + 7);
        let mut tmp614 = <[u8; 1]>::default();
        (tmp614)[0 as usize] = tmp366;
        w.write_all(&tmp614[0..1 as usize]).map_err(|e| Error::EncodeError("Address::bit_field_is_v6_reserved",e))?;
        if (if self.is_v6() {1} else {0} == 1) {
            if !matches!(self.field123,Variant124::Variant125(_)) {
                return Err(Error::InvalidUnionVariant("Variant124::Variant125"));
            }
            w.write_all(&match &self.field123 {  Variant124::Variant125(x) => x, _ => unreachable!() }.addr_v6[0..16 as usize]).map_err(|e| Error::EncodeError("Address::Variant124::Variant125::addr_v6",e))?;
        } else {
            if !matches!(self.field123,Variant124::Variant128(_)) {
                return Err(Error::InvalidUnionVariant("Variant124::Variant128"));
            }
            w.write_all(&match &self.field123 {  Variant124::Variant128(x) => x, _ => unreachable!() }.addr_v4[0..4 as usize]).map_err(|e| Error::EncodeError("Address::Variant124::Variant128::addr_v4",e))?;
        }
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>RequestInfo<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        let mut tmp467 = <[u8; 4]>::default();
        let mut tmp468 = 0;
        while((tmp468 < 4)) {
            (tmp467)[tmp468 as usize] = (((self.popID >> (tmp468 * 8)) & 255) as u8);
            tmp468+= 1;
        }
        w.write_all(&tmp467[0..4 as usize]).map_err(|e| Error::EncodeError("RequestInfo::popID",e))?;
        let mut tmp479 = <[u8; 8]>::default();
        let mut tmp480 = 0;
        while((tmp480 < 8)) {
            (tmp479)[tmp480 as usize] = (((self.reqID >> (tmp480 * 8)) & 255) as u8);
            tmp480+= 1;
        }
        w.write_all(&tmp479[0..8 as usize]).map_err(|e| Error::EncodeError("RequestInfo::reqID",e))?;
        self.protocol.encode(w)?;
        self.remoteAddr.encode(w)?;
        let mut tmp490 = <[u8; 2]>::default();
        let mut tmp491 = 0;
        while((tmp491 < 2)) {
            (tmp490)[tmp491 as usize] = (((self.remotePort >> (tmp491 * 8)) & 255) as u8);
            tmp491+= 1;
        }
        w.write_all(&tmp490[0..2 as usize]).map_err(|e| Error::EncodeError("RequestInfo::remotePort",e))?;
        self.method.encode(w)?;
        self.path.encode(w)?;
        self.header.encode(w)?;
        return Ok(());
    }
}
/* Unimplemented op: ENCODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>ResponseInfo<'a> {
    pub fn encode_to_vec(&self) -> std::result::Result<Vec<u8>, Error> {
        let mut w = std::io::Cursor::new(Vec::new());
        self.encode(&mut w
        )?;
        Ok(w.into_inner())
    }
    pub fn encode_to_fixed<'b>(&self, data: &'b mut [u8]) -> std::result::Result<&'b [u8], Error> {
        let mut w = std::io::Cursor::new(&mut *data);
        self.encode(&mut w
        )?;
        let written = w.position() as usize;
        drop(w);
        Ok(&data[0..written])
    }
    pub fn encode<W: std::io::Write>(&self, w :&mut W) -> std::result::Result<(), Error> {
        let mut tmp501 = <[u8; 2]>::default();
        let mut tmp502 = 0;
        while((tmp502 < 2)) {
            (tmp501)[tmp502 as usize] = (((self.status >> (tmp502 * 8)) & 255) as u8);
            tmp502+= 1;
        }
        w.write_all(&tmp501[0..2 as usize]).map_err(|e| Error::EncodeError("ResponseInfo::status",e))?;
        self.header.encode(w)?;
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>ProtocolInfo<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        let mut tmp205 = <u8>::default();
        let mut tmp512 = <[u8; 1]>::default();
        r.read_exact(&mut tmp512[0..1 as usize]).map_err(|e| Error::DecodeError("ProtocolInfo::protocol",e))?;
        tmp205 = (tmp512)[0 as usize];
        self.protocol = Protocol::from(tmp205);
        if (self.protocol == Protocol::other) {
            if !matches!(self.field31,Variant32::Variant33(_)) {
                self.field31 = Variant32::Variant33(Variant33::default());
            }
            let mut tmp517 = <[u8; 1]>::default();
            r.read_exact(&mut tmp517[0..1 as usize]).map_err(|e| Error::DecodeError("ProtocolInfo::Variant32::Variant33::len",e))?;
            match &mut self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len = (tmp517)[0 as usize];
            let mut tmp212 = match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len;
            match &mut self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name.to_mut().resize(tmp212 as usize,0);
            r.read_exact(match &mut self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name.to_mut()).map_err(|e| Error::DecodeError("ProtocolInfo::Variant32::Variant33::protocol_name",e))?;
        }
        return Ok(());
    }
}
impl <'a>ProtocolInfo<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        let mut tmp205 = <u8>::default();
        let mut tmp512 = <[u8; 1]>::default();
        if *offset + 1 as usize > r.len() {
        return Err(Error::DecodeError("ProtocolInfo::protocol",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp512.copy_from_slice(&r[*offset..(*offset + 1 as usize)]);
        *offset += 1 as usize;
        tmp205 = (tmp512)[0 as usize];
        self.protocol = Protocol::from(tmp205);
        if (self.protocol == Protocol::other) {
            if !matches!(self.field31,Variant32::Variant33(_)) {
                self.field31 = Variant32::Variant33(Variant33::default());
            }
            let mut tmp517 = <[u8; 1]>::default();
            if *offset + 1 as usize > r.len() {
            return Err(Error::DecodeError("ProtocolInfo::Variant32::Variant33::len",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
            }
            tmp517.copy_from_slice(&r[*offset..(*offset + 1 as usize)]);
            *offset += 1 as usize;
            match &mut self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len = (tmp517)[0 as usize];
            let mut tmp212 = match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len;
            if *offset + tmp212 as usize > r.len() {
            return Err(Error::DecodeError("ProtocolInfo::Variant32::Variant33::protocol_name",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
            }
            match &mut self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name = std::borrow::Cow::Borrowed(&r[*offset..(*offset + tmp212 as usize)]);
            *offset += tmp212 as usize;
        }
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>MethodInfo<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        let mut tmp215 = <u8>::default();
        let mut tmp522 = <[u8; 1]>::default();
        r.read_exact(&mut tmp522[0..1 as usize]).map_err(|e| Error::DecodeError("MethodInfo::method",e))?;
        tmp215 = (tmp522)[0 as usize];
        self.method = Method::from(tmp215);
        if (self.method == Method::OTHER) {
            if !matches!(self.field79,Variant80::Variant81(_)) {
                self.field79 = Variant80::Variant81(Variant81::default());
            }
            let mut tmp527 = <[u8; 1]>::default();
            r.read_exact(&mut tmp527[0..1 as usize]).map_err(|e| Error::DecodeError("MethodInfo::Variant80::Variant81::len",e))?;
            match &mut self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len = (tmp527)[0 as usize];
            let mut tmp222 = match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len;
            match &mut self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name.to_mut().resize(tmp222 as usize,0);
            r.read_exact(match &mut self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name.to_mut()).map_err(|e| Error::DecodeError("MethodInfo::Variant80::Variant81::method_name",e))?;
        }
        return Ok(());
    }
}
impl <'a>MethodInfo<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        let mut tmp215 = <u8>::default();
        let mut tmp522 = <[u8; 1]>::default();
        if *offset + 1 as usize > r.len() {
        return Err(Error::DecodeError("MethodInfo::method",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp522.copy_from_slice(&r[*offset..(*offset + 1 as usize)]);
        *offset += 1 as usize;
        tmp215 = (tmp522)[0 as usize];
        self.method = Method::from(tmp215);
        if (self.method == Method::OTHER) {
            if !matches!(self.field79,Variant80::Variant81(_)) {
                self.field79 = Variant80::Variant81(Variant81::default());
            }
            let mut tmp527 = <[u8; 1]>::default();
            if *offset + 1 as usize > r.len() {
            return Err(Error::DecodeError("MethodInfo::Variant80::Variant81::len",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
            }
            tmp527.copy_from_slice(&r[*offset..(*offset + 1 as usize)]);
            *offset += 1 as usize;
            match &mut self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len = (tmp527)[0 as usize];
            let mut tmp222 = match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len;
            if *offset + tmp222 as usize > r.len() {
            return Err(Error::DecodeError("MethodInfo::Variant80::Variant81::method_name",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
            }
            match &mut self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name = std::borrow::Cow::Borrowed(&r[*offset..(*offset + tmp222 as usize)]);
            *offset += tmp222 as usize;
        }
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: RESERVE_SIZE */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: RESERVE_SIZE */
impl <'a>PathInfo<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        self.path.decode(r)?;
        let mut tmp532 = <[u8; 1]>::default();
        r.read_exact(&mut tmp532[0..1 as usize]).map_err(|e| Error::DecodeError("PathInfo::query_len",e))?;
        self.query_len = (tmp532)[0 as usize];
        let mut tmp224 = self.query_len;
        let mut tmp225 = 0;
        while((tmp225 < tmp224)) {
            let mut tmp229 = <Field<'a>>::default();
            tmp229.decode(r)?;
            self.query.to_mut().push(tmp229);
            tmp225+= 1;
        }
        return Ok(());
    }
}
impl <'a>PathInfo<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        self.path.decode_direct(r, offset)?;
        let mut tmp532 = <[u8; 1]>::default();
        if *offset + 1 as usize > r.len() {
        return Err(Error::DecodeError("PathInfo::query_len",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp532.copy_from_slice(&r[*offset..(*offset + 1 as usize)]);
        *offset += 1 as usize;
        self.query_len = (tmp532)[0 as usize];
        let mut tmp224 = self.query_len;
        let mut tmp225 = 0;
        while((tmp225 < tmp224)) {
            let mut tmp229 = <Field<'a>>::default();
            tmp229.decode_direct(r, offset)?;
            self.query.to_mut().push(tmp229);
            tmp225+= 1;
        }
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>String<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        let mut tmp537 = <[u8; 2]>::default();
        r.read_exact(&mut tmp537[0..2 as usize]).map_err(|e| Error::DecodeError("String::len",e))?;
        let mut tmp538 = 0;
        while((tmp538 < 2)) {
            self.len = (self.len | (((tmp537)[tmp538 as usize] as u16) << (tmp538 * 8)));
            tmp538+= 1;
        }
        let mut tmp231 = self.len;
        self.data.to_mut().resize(tmp231 as usize,0);
        r.read_exact(self.data.to_mut()).map_err(|e| Error::DecodeError("String::data",e))?;
        return Ok(());
    }
}
impl <'a>String<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        let mut tmp537 = <[u8; 2]>::default();
        if *offset + 2 as usize > r.len() {
        return Err(Error::DecodeError("String::len",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp537.copy_from_slice(&r[*offset..(*offset + 2 as usize)]);
        *offset += 2 as usize;
        let mut tmp538 = 0;
        while((tmp538 < 2)) {
            self.len = (self.len | (((tmp537)[tmp538 as usize] as u16) << (tmp538 * 8)));
            tmp538+= 1;
        }
        let mut tmp231 = self.len;
        if *offset + tmp231 as usize > r.len() {
        return Err(Error::DecodeError("String::data",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        self.data = std::borrow::Cow::Borrowed(&r[*offset..(*offset + tmp231 as usize)]);
        *offset += tmp231 as usize;
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
impl <'a>Field<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        self.key.decode(r)?;
        self.value.decode(r)?;
        return Ok(());
    }
}
impl <'a>Field<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        self.key.decode_direct(r, offset)?;
        self.value.decode_direct(r, offset)?;
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: RESERVE_SIZE */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: RESERVE_SIZE */
impl <'a>Header<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        let mut tmp548 = <[u8; 2]>::default();
        r.read_exact(&mut tmp548[0..2 as usize]).map_err(|e| Error::DecodeError("Header::len",e))?;
        let mut tmp549 = 0;
        while((tmp549 < 2)) {
            self.len = (self.len | (((tmp548)[tmp549 as usize] as u16) << (tmp549 * 8)));
            tmp549+= 1;
        }
        let mut tmp234 = self.len;
        let mut tmp235 = 0;
        while((tmp235 < tmp234)) {
            let mut tmp238 = <Field<'a>>::default();
            tmp238.decode(r)?;
            self.fields.to_mut().push(tmp238);
            tmp235+= 1;
        }
        return Ok(());
    }
}
impl <'a>Header<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        let mut tmp548 = <[u8; 2]>::default();
        if *offset + 2 as usize > r.len() {
        return Err(Error::DecodeError("Header::len",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp548.copy_from_slice(&r[*offset..(*offset + 2 as usize)]);
        *offset += 2 as usize;
        let mut tmp549 = 0;
        while((tmp549 < 2)) {
            self.len = (self.len | (((tmp548)[tmp549 as usize] as u16) << (tmp549 * 8)));
            tmp549+= 1;
        }
        let mut tmp234 = self.len;
        let mut tmp235 = 0;
        while((tmp235 < tmp234)) {
            let mut tmp238 = <Field<'a>>::default();
            tmp238.decode_direct(r, offset)?;
            self.fields.to_mut().push(tmp238);
            tmp235+= 1;
        }
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>Body<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        let mut tmp559 = <[u8; 4]>::default();
        r.read_exact(&mut tmp559[0..4 as usize]).map_err(|e| Error::DecodeError("Body::len",e))?;
        let mut tmp560 = 0;
        while((tmp560 < 4)) {
            self.len = (self.len | (((tmp559)[tmp560 as usize] as u32) << (tmp560 * 8)));
            tmp560+= 1;
        }
        let mut tmp240 = self.len;
        self.body.to_mut().resize(tmp240 as usize,0);
        r.read_exact(self.body.to_mut()).map_err(|e| Error::DecodeError("Body::body",e))?;
        return Ok(());
    }
}
impl <'a>Body<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        let mut tmp559 = <[u8; 4]>::default();
        if *offset + 4 as usize > r.len() {
        return Err(Error::DecodeError("Body::len",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp559.copy_from_slice(&r[*offset..(*offset + 4 as usize)]);
        *offset += 4 as usize;
        let mut tmp560 = 0;
        while((tmp560 < 4)) {
            self.len = (self.len | (((tmp559)[tmp560 as usize] as u32) << (tmp560 * 8)));
            tmp560+= 1;
        }
        let mut tmp240 = self.len;
        if *offset + tmp240 as usize > r.len() {
        return Err(Error::DecodeError("Body::body",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        self.body = std::borrow::Cow::Borrowed(&r[*offset..(*offset + tmp240 as usize)]);
        *offset += tmp240 as usize;
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: END_COND_BLOCK */
impl <'a>Address<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        let mut tmp388 = <u8>::default();
        let mut tmp389 = 0;
        let mut tmp619 = <[u8; 1]>::default();
        r.read_exact(&mut tmp619[0..1 as usize]).map_err(|e| Error::DecodeError("Address::bit_field_is_v6_reserved",e))?;
        tmp388 = (tmp619)[0 as usize];
        self.set_is_v6(((tmp388 >> tmp389) & 1) != 0);
        tmp389 = (tmp389 + 1);
        self.set_reserved((((tmp388 >> tmp389) & 127) as u8));
        tmp389 = (tmp389 + 7);
        if (if self.is_v6() {1} else {0} == 1) {
            if !matches!(self.field123,Variant124::Variant125(_)) {
                self.field123 = Variant124::Variant125(Variant125::default());
            }
            r.read_exact(&mut match &mut self.field123 {  Variant124::Variant125(x) => x, _ => unreachable!() }.addr_v6[0..16 as usize]).map_err(|e| Error::DecodeError("Address::Variant124::Variant125::addr_v6",e))?;
        } else {
            if !matches!(self.field123,Variant124::Variant128(_)) {
                self.field123 = Variant124::Variant128(Variant128::default());
            }
            r.read_exact(&mut match &mut self.field123 {  Variant124::Variant128(x) => x, _ => unreachable!() }.addr_v4[0..4 as usize]).map_err(|e| Error::DecodeError("Address::Variant124::Variant128::addr_v4",e))?;
        }
        return Ok(());
    }
}
impl <'a>Address<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        let mut tmp388 = <u8>::default();
        let mut tmp389 = 0;
        let mut tmp619 = <[u8; 1]>::default();
        if *offset + 1 as usize > r.len() {
        return Err(Error::DecodeError("Address::bit_field_is_v6_reserved",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp619.copy_from_slice(&r[*offset..(*offset + 1 as usize)]);
        *offset += 1 as usize;
        tmp388 = (tmp619)[0 as usize];
        self.set_is_v6(((tmp388 >> tmp389) & 1) != 0);
        tmp389 = (tmp389 + 1);
        self.set_reserved((((tmp388 >> tmp389) & 127) as u8));
        tmp389 = (tmp389 + 7);
        if (if self.is_v6() {1} else {0} == 1) {
            if !matches!(self.field123,Variant124::Variant125(_)) {
                self.field123 = Variant124::Variant125(Variant125::default());
            }
            if *offset + 16 as usize > r.len() {
            return Err(Error::DecodeError("Address::Variant124::Variant125::addr_v6",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
            }
            match &mut self.field123 {  Variant124::Variant125(x) => x, _ => unreachable!() }.addr_v6.copy_from_slice(&r[*offset..(*offset + 16 as usize)]);
            *offset += 16 as usize;
        } else {
            if !matches!(self.field123,Variant124::Variant128(_)) {
                self.field123 = Variant124::Variant128(Variant128::default());
            }
            if *offset + 4 as usize > r.len() {
            return Err(Error::DecodeError("Address::Variant124::Variant128::addr_v4",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
            }
            match &mut self.field123 {  Variant124::Variant128(x) => x, _ => unreachable!() }.addr_v4.copy_from_slice(&r[*offset..(*offset + 4 as usize)]);
            *offset += 4 as usize;
        }
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>RequestInfo<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        let mut tmp570 = <[u8; 4]>::default();
        r.read_exact(&mut tmp570[0..4 as usize]).map_err(|e| Error::DecodeError("RequestInfo::popID",e))?;
        let mut tmp571 = 0;
        while((tmp571 < 4)) {
            self.popID = (self.popID | (((tmp570)[tmp571 as usize] as u32) << (tmp571 * 8)));
            tmp571+= 1;
        }
        let mut tmp581 = <[u8; 8]>::default();
        r.read_exact(&mut tmp581[0..8 as usize]).map_err(|e| Error::DecodeError("RequestInfo::reqID",e))?;
        let mut tmp582 = 0;
        while((tmp582 < 8)) {
            self.reqID = (self.reqID | (((tmp581)[tmp582 as usize] as u64) << (tmp582 * 8)));
            tmp582+= 1;
        }
        self.protocol.decode(r)?;
        self.remoteAddr.decode(r)?;
        let mut tmp592 = <[u8; 2]>::default();
        r.read_exact(&mut tmp592[0..2 as usize]).map_err(|e| Error::DecodeError("RequestInfo::remotePort",e))?;
        let mut tmp593 = 0;
        while((tmp593 < 2)) {
            self.remotePort = (self.remotePort | (((tmp592)[tmp593 as usize] as u16) << (tmp593 * 8)));
            tmp593+= 1;
        }
        self.method.decode(r)?;
        self.path.decode(r)?;
        self.header.decode(r)?;
        return Ok(());
    }
}
impl <'a>RequestInfo<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        let mut tmp570 = <[u8; 4]>::default();
        if *offset + 4 as usize > r.len() {
        return Err(Error::DecodeError("RequestInfo::popID",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp570.copy_from_slice(&r[*offset..(*offset + 4 as usize)]);
        *offset += 4 as usize;
        let mut tmp571 = 0;
        while((tmp571 < 4)) {
            self.popID = (self.popID | (((tmp570)[tmp571 as usize] as u32) << (tmp571 * 8)));
            tmp571+= 1;
        }
        let mut tmp581 = <[u8; 8]>::default();
        if *offset + 8 as usize > r.len() {
        return Err(Error::DecodeError("RequestInfo::reqID",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp581.copy_from_slice(&r[*offset..(*offset + 8 as usize)]);
        *offset += 8 as usize;
        let mut tmp582 = 0;
        while((tmp582 < 8)) {
            self.reqID = (self.reqID | (((tmp581)[tmp582 as usize] as u64) << (tmp582 * 8)));
            tmp582+= 1;
        }
        self.protocol.decode_direct(r, offset)?;
        self.remoteAddr.decode_direct(r, offset)?;
        let mut tmp592 = <[u8; 2]>::default();
        if *offset + 2 as usize > r.len() {
        return Err(Error::DecodeError("RequestInfo::remotePort",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp592.copy_from_slice(&r[*offset..(*offset + 2 as usize)]);
        *offset += 2 as usize;
        let mut tmp593 = 0;
        while((tmp593 < 2)) {
            self.remotePort = (self.remotePort | (((tmp592)[tmp593 as usize] as u16) << (tmp593 * 8)));
            tmp593+= 1;
        }
        self.method.decode_direct(r, offset)?;
        self.path.decode_direct(r, offset)?;
        self.header.decode_direct(r, offset)?;
        return Ok(());
    }
}
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
/* Unimplemented op: DECODER_PARAMETER */
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: DEFINE_FALLBACK */
/* Unimplemented op: END_FALLBACK */
impl <'a>ResponseInfo<'a> {
    pub fn decode_slice<'b>(data :&'b [u8]) -> Result<(Self,&'b [u8]), Error> {
        let mut r = std::io::Cursor::new(data);
        let mut result = Self::default();
        result.decode(&mut r)?;
        Ok((result,&data[r.position() as usize..]))
    }
    pub fn decode_exact(data :&[u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode<R: std::io::Read>(&mut self, r :&mut R) -> std::result::Result<(), Error> {
        let mut tmp603 = <[u8; 2]>::default();
        r.read_exact(&mut tmp603[0..2 as usize]).map_err(|e| Error::DecodeError("ResponseInfo::status",e))?;
        let mut tmp604 = 0;
        while((tmp604 < 2)) {
            self.status = (self.status | (((tmp603)[tmp604 as usize] as u16) << (tmp604 * 8)));
            tmp604+= 1;
        }
        self.header.decode(r)?;
        return Ok(());
    }
}
impl <'a>ResponseInfo<'a> {
    pub fn decode_slice_direct(data :&'a [u8]) -> Result<(Self,&'a [u8]), Error> {
        let mut result = Self::default();
        let mut offset = 0;
        result.decode_direct(data,&mut offset
        )?;
        Ok((result,&data[offset..]))
    }
    pub fn decode_exact_direct(data :&'a [u8]) -> Result<Self, Error> {
        let (result,rest) = Self::decode_slice_direct(data)?;
        if rest.len() > 0 {
        return Err(Error::AssertError("Unexpected data"));
        }
        Ok(result)
    }
    pub fn decode_direct(&mut self, r :&'a [u8], offset :&mut usize) -> std::result::Result<(), Error> {
        let mut tmp603 = <[u8; 2]>::default();
        if *offset + 2 as usize > r.len() {
        return Err(Error::DecodeError("ResponseInfo::status",std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "Unexpected end of input")));
        }
        tmp603.copy_from_slice(&r[*offset..(*offset + 2 as usize)]);
        *offset += 2 as usize;
        let mut tmp604 = 0;
        while((tmp604 < 2)) {
            self.status = (self.status | (((tmp603)[tmp604 as usize] as u16) << (tmp604 * 8)));
            tmp604+= 1;
        }
        self.header.decode_direct(r, offset)?;
        return Ok(());
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>ProtocolInfo<'a> {
    pub fn len(&self) -> std::option::Option<&u8> {
        if (self.protocol == Protocol::other) {
            if !matches!(self.field31,Variant32::Variant33(_)) {
                return None;
            }
            return Some(&match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len);
        }
        return None;
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>ProtocolInfo<'a> {
    pub fn set_len(&mut self, param266: u8) -> std::result::Result<(), Error> {
        if (self.protocol == Protocol::other) {
            if !matches!(self.field31,Variant32::Variant33(_)) {
                self.field31 = Variant32::Variant33(Variant33::default());
            }
            match &mut self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len = param266;
            return Ok(());
        }
        return Err(Error::PropertySetterError("ProtocolInfo::len"));
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>ProtocolInfo<'a> {
    pub fn protocol_name(&self) -> std::option::Option<&std::borrow::Cow<'a,[u8]>> {
        if (self.protocol == Protocol::other) {
            if !matches!(self.field31,Variant32::Variant33(_)) {
                return None;
            }
            return Some(&match &self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name);
        }
        return None;
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>ProtocolInfo<'a> {
    pub fn set_protocol_name(&mut self, param273: std::borrow::Cow<'a,[u8]>) -> std::result::Result<(), Error> {
        if (self.protocol == Protocol::other) {
            if !matches!(self.field31,Variant32::Variant33(_)) {
                self.field31 = Variant32::Variant33(Variant33::default());
            }
            if(!(param273.len() <= 255)) { 
            return Err(Error::AssertError("(param273.len() <= 255)"));
            }
            match &mut self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.len = (param273.len() as u8);
            match &mut self.field31 {  Variant32::Variant33(x) => x, _ => unreachable!() }.protocol_name = param273;
            return Ok(());
        }
        return Err(Error::PropertySetterError("ProtocolInfo::protocol_name"));
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>MethodInfo<'a> {
    pub fn len(&self) -> std::option::Option<&u8> {
        if (self.method == Method::OTHER) {
            if !matches!(self.field79,Variant80::Variant81(_)) {
                return None;
            }
            return Some(&match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len);
        }
        return None;
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>MethodInfo<'a> {
    pub fn set_len(&mut self, param283: u8) -> std::result::Result<(), Error> {
        if (self.method == Method::OTHER) {
            if !matches!(self.field79,Variant80::Variant81(_)) {
                self.field79 = Variant80::Variant81(Variant81::default());
            }
            match &mut self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len = param283;
            return Ok(());
        }
        return Err(Error::PropertySetterError("MethodInfo::len"));
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>MethodInfo<'a> {
    pub fn method_name(&self) -> std::option::Option<&std::borrow::Cow<'a,[u8]>> {
        if (self.method == Method::OTHER) {
            if !matches!(self.field79,Variant80::Variant81(_)) {
                return None;
            }
            return Some(&match &self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name);
        }
        return None;
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>MethodInfo<'a> {
    pub fn set_method_name(&mut self, param288: std::borrow::Cow<'a,[u8]>) -> std::result::Result<(), Error> {
        if (self.method == Method::OTHER) {
            if !matches!(self.field79,Variant80::Variant81(_)) {
                self.field79 = Variant80::Variant81(Variant81::default());
            }
            if(!(param288.len() <= 255)) { 
            return Err(Error::AssertError("(param288.len() <= 255)"));
            }
            match &mut self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.len = (param288.len() as u8);
            match &mut self.field79 {  Variant80::Variant81(x) => x, _ => unreachable!() }.method_name = param288;
            return Ok(());
        }
        return Err(Error::PropertySetterError("MethodInfo::method_name"));
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>PathInfo<'a> {
    pub fn set_query(&mut self, param295: std::borrow::Cow<'a,[Field<'a>]>) -> std::result::Result<(), Error> {
        if(!(param295.len() <= 255)) { 
        return Err(Error::AssertError("(param295.len() <= 255)"));
        }
        self.query_len = (param295.len() as u8);
        self.query = param295;
        return Ok(());
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>String<'a> {
    pub fn set_data(&mut self, param301: std::borrow::Cow<'a,[u8]>) -> std::result::Result<(), Error> {
        if(!(param301.len() <= 65535)) { 
        return Err(Error::AssertError("(param301.len() <= 65535)"));
        }
        self.len = (param301.len() as u16);
        self.data = param301;
        return Ok(());
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>Header<'a> {
    pub fn set_fields(&mut self, param309: std::borrow::Cow<'a,[Field<'a>]>) -> std::result::Result<(), Error> {
        if(!(param309.len() <= 65535)) { 
        return Err(Error::AssertError("(param309.len() <= 65535)"));
        }
        self.len = (param309.len() as u16);
        self.fields = param309;
        return Ok(());
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>Body<'a> {
    pub fn set_body(&mut self, param315: std::borrow::Cow<'a,[u8]>) -> std::result::Result<(), Error> {
        if(!(param315.len() <= 4294967295)) { 
        return Err(Error::AssertError("(param315.len() <= 4294967295)"));
        }
        self.len = (param315.len() as u32);
        self.body = param315;
        return Ok(());
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>Address<'a> {
    pub fn addr_v4(&self) -> std::option::Option<&[u8; 4]> {
        if (if self.is_v6() {1} else {0} == 1) {
            return None;
        }
        if true {
            if !matches!(self.field123,Variant124::Variant128(_)) {
                return None;
            }
            return Some(&match &self.field123 {  Variant124::Variant128(x) => x, _ => unreachable!() }.addr_v4);
        }
        return None;
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>Address<'a> {
    pub fn set_addr_v4(&mut self, param327: [u8; 4]) -> std::result::Result<(), Error> {
        if (if self.is_v6() {1} else {0} == 1) {
            return Err(Error::PropertySetterError("Address::addr_v4"));
        }
        if true {
            if !matches!(self.field123,Variant124::Variant128(_)) {
                self.field123 = Variant124::Variant128(Variant128::default());
            }
            match &mut self.field123 {  Variant124::Variant128(x) => x, _ => unreachable!() }.addr_v4 = param327;
            return Ok(());
        }
        return Err(Error::PropertySetterError("Address::addr_v4"));
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>Address<'a> {
    pub fn addr_v6(&self) -> std::option::Option<&[u8; 16]> {
        if (if self.is_v6() {1} else {0} == 1) {
            if !matches!(self.field123,Variant124::Variant125(_)) {
                return None;
            }
            return Some(&match &self.field123 {  Variant124::Variant125(x) => x, _ => unreachable!() }.addr_v6);
        }
        return None;
    }
}
/* Unimplemented op: RETURN_TYPE */
/* Unimplemented op: PROPERTY_FUNCTION */
impl <'a>Address<'a> {
    pub fn set_addr_v6(&mut self, param333: [u8; 16]) -> std::result::Result<(), Error> {
        if (if self.is_v6() {1} else {0} == 1) {
            if !matches!(self.field123,Variant124::Variant125(_)) {
                self.field123 = Variant124::Variant125(Variant125::default());
            }
            match &mut self.field123 {  Variant124::Variant125(x) => x, _ => unreachable!() }.addr_v6 = param333;
            return Ok(());
        }
        return Err(Error::PropertySetterError("Address::addr_v6"));
    }
}
