package l4lbdrv

// This file is auto generated by gen_bindings.go. Do not modify.

import (
	"bytes"
	"fmt"
	"strings"
	"unsafe"
)

// Source: ../c/lb.c

const (
	DESTINATIONS_SIZE = 255 // ../c/lb.c:94
)

type StatCounters struct { // ../c/lb.c:32
	RxPacketTotal                   uint64 // ../c/lb.c:33
	RxTotalSize                     uint64 // ../c/lb.c:34
	TooShortPacketTotal             uint64 // ../c/lb.c:36
	NonIpv4PacketTotal              uint64 // ../c/lb.c:37
	IpOptionPacketTotal             uint64 // ../c/lb.c:38
	NonSupportedProtoPacketTotal    uint64 // ../c/lb.c:39
	NoVipMatchTotal                 uint64 // ../c/lb.c:40
	FailedAdjustHeadTotal           uint64 // ../c/lb.c:41
	FailedAdjustTailTotal           uint64 // ../c/lb.c:42
	TcpPacketTotal                  uint64 // ../c/lb.c:43
	MtuExceededTotal                uint64 // ../c/lb.c:44
	QuiclbNoDestPortMatchTotal      uint64 // ../c/lb.c:46
	QuiclbShortPacketTotal          uint64 // ../c/lb.c:47
	QuiclbLongPacketTotal           uint64 // ../c/lb.c:48
	QuiclbInitialRoutingPacketTotal uint64 // ../c/lb.c:49
	QuiclbTooShortLongPacketTotal   uint64 // ../c/lb.c:50
	QuiclbNoConnectionIdTotal       uint64 // ../c/lb.c:51
	QuiclbNoDestEntryTotal          uint64 // ../c/lb.c:52
	QuiclbInvalidCryptoContextTotal uint64 // ../c/lb.c:53
	QuiclbEncryptSuccessCallTotal   uint64 // ../c/lb.c:54
	QuiclbDecryptSuccessCallTotal   uint64 // ../c/lb.c:55
	QuiclbConnidCacheHitTotal       uint64 // ../c/lb.c:56
}

func StatCountersAssertLayout(s *DWARFStruct) error {
	if s == nil {
		return fmt.Errorf("DWARFStruct is nil")
	}

	gosize := unsafe.Sizeof(StatCounters{})
	if gosize != uintptr(s.Size) {
		return fmt.Errorf("size mismatch: go: %d, dwarf: %d", gosize, s.Size)
	}

	fs := s.Fields

	var goff uintptr
	var doff int64
	goff = unsafe.Offsetof(StatCounters{}.RxPacketTotal)
	doff = fs["rx_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go RxPacketTotal: %d, dwarf rx_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.RxTotalSize)
	doff = fs["rx_total_size"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go RxTotalSize: %d, dwarf rx_total_size: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.TooShortPacketTotal)
	doff = fs["too_short_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go TooShortPacketTotal: %d, dwarf too_short_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.NonIpv4PacketTotal)
	doff = fs["non_ipv4_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go NonIpv4PacketTotal: %d, dwarf non_ipv4_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.IpOptionPacketTotal)
	doff = fs["ip_option_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go IpOptionPacketTotal: %d, dwarf ip_option_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.NonSupportedProtoPacketTotal)
	doff = fs["non_supported_proto_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go NonSupportedProtoPacketTotal: %d, dwarf non_supported_proto_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.NoVipMatchTotal)
	doff = fs["no_vip_match_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go NoVipMatchTotal: %d, dwarf no_vip_match_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.FailedAdjustHeadTotal)
	doff = fs["failed_adjust_head_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go FailedAdjustHeadTotal: %d, dwarf failed_adjust_head_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.FailedAdjustTailTotal)
	doff = fs["failed_adjust_tail_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go FailedAdjustTailTotal: %d, dwarf failed_adjust_tail_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.TcpPacketTotal)
	doff = fs["tcp_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go TcpPacketTotal: %d, dwarf tcp_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.MtuExceededTotal)
	doff = fs["mtu_exceeded_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go MtuExceededTotal: %d, dwarf mtu_exceeded_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbNoDestPortMatchTotal)
	doff = fs["quiclb_no_dest_port_match_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbNoDestPortMatchTotal: %d, dwarf quiclb_no_dest_port_match_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbShortPacketTotal)
	doff = fs["quiclb_short_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbShortPacketTotal: %d, dwarf quiclb_short_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbLongPacketTotal)
	doff = fs["quiclb_long_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbLongPacketTotal: %d, dwarf quiclb_long_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbInitialRoutingPacketTotal)
	doff = fs["quiclb_initial_routing_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbInitialRoutingPacketTotal: %d, dwarf quiclb_initial_routing_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbTooShortLongPacketTotal)
	doff = fs["quiclb_too_short_long_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbTooShortLongPacketTotal: %d, dwarf quiclb_too_short_long_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbNoConnectionIdTotal)
	doff = fs["quiclb_no_connection_id_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbNoConnectionIdTotal: %d, dwarf quiclb_no_connection_id_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbNoDestEntryTotal)
	doff = fs["quiclb_no_dest_entry_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbNoDestEntryTotal: %d, dwarf quiclb_no_dest_entry_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbInvalidCryptoContextTotal)
	doff = fs["quiclb_invalid_crypto_context_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbInvalidCryptoContextTotal: %d, dwarf quiclb_invalid_crypto_context_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbEncryptSuccessCallTotal)
	doff = fs["quiclb_encrypt_success_call_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbEncryptSuccessCallTotal: %d, dwarf quiclb_encrypt_success_call_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbDecryptSuccessCallTotal)
	doff = fs["quiclb_decrypt_success_call_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbDecryptSuccessCallTotal: %d, dwarf quiclb_decrypt_success_call_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.QuiclbConnidCacheHitTotal)
	doff = fs["quiclb_connid_cache_hit_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuiclbConnidCacheHitTotal: %d, dwarf quiclb_connid_cache_hit_total: %d", goff, doff)
	}

	return nil
}

func (c *StatCounters) Add(other *StatCounters) {
	c.RxPacketTotal += other.RxPacketTotal
	c.RxTotalSize += other.RxTotalSize
	c.TooShortPacketTotal += other.TooShortPacketTotal
	c.NonIpv4PacketTotal += other.NonIpv4PacketTotal
	c.IpOptionPacketTotal += other.IpOptionPacketTotal
	c.NonSupportedProtoPacketTotal += other.NonSupportedProtoPacketTotal
	c.NoVipMatchTotal += other.NoVipMatchTotal
	c.FailedAdjustHeadTotal += other.FailedAdjustHeadTotal
	c.FailedAdjustTailTotal += other.FailedAdjustTailTotal
	c.TcpPacketTotal += other.TcpPacketTotal
	c.MtuExceededTotal += other.MtuExceededTotal
	c.QuiclbNoDestPortMatchTotal += other.QuiclbNoDestPortMatchTotal
	c.QuiclbShortPacketTotal += other.QuiclbShortPacketTotal
	c.QuiclbLongPacketTotal += other.QuiclbLongPacketTotal
	c.QuiclbInitialRoutingPacketTotal += other.QuiclbInitialRoutingPacketTotal
	c.QuiclbTooShortLongPacketTotal += other.QuiclbTooShortLongPacketTotal
	c.QuiclbNoConnectionIdTotal += other.QuiclbNoConnectionIdTotal
	c.QuiclbNoDestEntryTotal += other.QuiclbNoDestEntryTotal
	c.QuiclbInvalidCryptoContextTotal += other.QuiclbInvalidCryptoContextTotal
	c.QuiclbEncryptSuccessCallTotal += other.QuiclbEncryptSuccessCallTotal
	c.QuiclbDecryptSuccessCallTotal += other.QuiclbDecryptSuccessCallTotal
	c.QuiclbConnidCacheHitTotal += other.QuiclbConnidCacheHitTotal
}

func (c *StatCounters) String() string {
	var buf bytes.Buffer
	buf.WriteString("StatCounters{")
	if c.RxPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("RxPacketTotal=%d, ", c.RxPacketTotal))
	}
	if c.RxTotalSize != 0 {
		buf.WriteString(fmt.Sprintf("RxTotalSize=%d, ", c.RxTotalSize))
	}
	if c.TooShortPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("TooShortPacketTotal=%d, ", c.TooShortPacketTotal))
	}
	if c.NonIpv4PacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("NonIpv4PacketTotal=%d, ", c.NonIpv4PacketTotal))
	}
	if c.IpOptionPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("IpOptionPacketTotal=%d, ", c.IpOptionPacketTotal))
	}
	if c.NonSupportedProtoPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("NonSupportedProtoPacketTotal=%d, ", c.NonSupportedProtoPacketTotal))
	}
	if c.NoVipMatchTotal != 0 {
		buf.WriteString(fmt.Sprintf("NoVipMatchTotal=%d, ", c.NoVipMatchTotal))
	}
	if c.FailedAdjustHeadTotal != 0 {
		buf.WriteString(fmt.Sprintf("FailedAdjustHeadTotal=%d, ", c.FailedAdjustHeadTotal))
	}
	if c.FailedAdjustTailTotal != 0 {
		buf.WriteString(fmt.Sprintf("FailedAdjustTailTotal=%d, ", c.FailedAdjustTailTotal))
	}
	if c.TcpPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("TcpPacketTotal=%d, ", c.TcpPacketTotal))
	}
	if c.MtuExceededTotal != 0 {
		buf.WriteString(fmt.Sprintf("MtuExceededTotal=%d, ", c.MtuExceededTotal))
	}
	if c.QuiclbNoDestPortMatchTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbNoDestPortMatchTotal=%d, ", c.QuiclbNoDestPortMatchTotal))
	}
	if c.QuiclbShortPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbShortPacketTotal=%d, ", c.QuiclbShortPacketTotal))
	}
	if c.QuiclbLongPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbLongPacketTotal=%d, ", c.QuiclbLongPacketTotal))
	}
	if c.QuiclbInitialRoutingPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbInitialRoutingPacketTotal=%d, ", c.QuiclbInitialRoutingPacketTotal))
	}
	if c.QuiclbTooShortLongPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbTooShortLongPacketTotal=%d, ", c.QuiclbTooShortLongPacketTotal))
	}
	if c.QuiclbNoConnectionIdTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbNoConnectionIdTotal=%d, ", c.QuiclbNoConnectionIdTotal))
	}
	if c.QuiclbNoDestEntryTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbNoDestEntryTotal=%d, ", c.QuiclbNoDestEntryTotal))
	}
	if c.QuiclbInvalidCryptoContextTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbInvalidCryptoContextTotal=%d, ", c.QuiclbInvalidCryptoContextTotal))
	}
	if c.QuiclbEncryptSuccessCallTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbEncryptSuccessCallTotal=%d, ", c.QuiclbEncryptSuccessCallTotal))
	}
	if c.QuiclbDecryptSuccessCallTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbDecryptSuccessCallTotal=%d, ", c.QuiclbDecryptSuccessCallTotal))
	}
	if c.QuiclbConnidCacheHitTotal != 0 {
		buf.WriteString(fmt.Sprintf("QuiclbConnidCacheHitTotal=%d, ", c.QuiclbConnidCacheHitTotal))
	}
	if strings.HasSuffix(buf.String(), ", ") {
		buf.Truncate(buf.Len() - 2)
	}
	buf.WriteString("}")
	return buf.String()
}

type LbConfig struct { // ../c/lb.c:69
	VipAddress      uint32 // ../c/lb.c:70
	NumDests        uint32 // ../c/lb.c:71
	Mtu             uint16 // ../c/lb.c:72
	QuicDestPort    uint16 // ../c/lb.c:73
	Flags           uint32 // ../c/lb.c:74
	ServerIdHashKey uint32 // ../c/lb.c:75
}

func LbConfigAssertLayout(s *DWARFStruct) error {
	if s == nil {
		return fmt.Errorf("DWARFStruct is nil")
	}

	gosize := unsafe.Sizeof(LbConfig{})
	if gosize != uintptr(s.Size) {
		return fmt.Errorf("size mismatch: go: %d, dwarf: %d", gosize, s.Size)
	}

	fs := s.Fields

	var goff uintptr
	var doff int64
	goff = unsafe.Offsetof(LbConfig{}.VipAddress)
	doff = fs["vip_address"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go VipAddress: %d, dwarf vip_address: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.NumDests)
	doff = fs["num_dests"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go NumDests: %d, dwarf num_dests: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.Mtu)
	doff = fs["mtu"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Mtu: %d, dwarf mtu: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.QuicDestPort)
	doff = fs["quic_dest_port"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go QuicDestPort: %d, dwarf quic_dest_port: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.Flags)
	doff = fs["flags"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Flags: %d, dwarf flags: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.ServerIdHashKey)
	doff = fs["server_id_hash_key"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go ServerIdHashKey: %d, dwarf server_id_hash_key: %d", goff, doff)
	}

	return nil
}

type TestDecrypt struct { // ../c/lb.c:506
	ConnectionId    [20]uint8 // ../c/lb.c:507
	Len             uint8     // ../c/lb.c:508
	IsShortServerId uint8     // ../c/lb.c:509
}

func TestDecryptAssertLayout(s *DWARFStruct) error {
	if s == nil {
		return fmt.Errorf("DWARFStruct is nil")
	}

	gosize := unsafe.Sizeof(TestDecrypt{})
	if gosize != uintptr(s.Size) {
		return fmt.Errorf("size mismatch: go: %d, dwarf: %d", gosize, s.Size)
	}

	fs := s.Fields

	var goff uintptr
	var doff int64
	goff = unsafe.Offsetof(TestDecrypt{}.ConnectionId)
	doff = fs["connection_id"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go ConnectionId: %d, dwarf connection_id: %d", goff, doff)
	}
	goff = unsafe.Offsetof(TestDecrypt{}.Len)
	doff = fs["len"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Len: %d, dwarf len: %d", goff, doff)
	}
	goff = unsafe.Offsetof(TestDecrypt{}.IsShortServerId)
	doff = fs["is_short_server_id"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go IsShortServerId: %d, dwarf is_short_server_id: %d", goff, doff)
	}

	return nil
}

func LbAssertLayout(m map[string]*DWARFStruct) error {
	if err := StatCountersAssertLayout(m["stat_counters"]); err != nil {
		return fmt.Errorf("stat_counters: %v", err)
	}
	if err := LbConfigAssertLayout(m["lb_config"]); err != nil {
		return fmt.Errorf("lb_config: %v", err)
	}
	if err := TestDecryptAssertLayout(m["test_decrypt"]); err != nil {
		return fmt.Errorf("test_decrypt: %v", err)
	}
	return nil
}

// Source: ../c/init_crypto.c

const ()

type QuiclbSharedKey struct { // ../c/init_crypto.c:38
	Key [16]uint8 // ../c/init_crypto.c:39
}

func QuiclbSharedKeyAssertLayout(s *DWARFStruct) error {
	if s == nil {
		return fmt.Errorf("DWARFStruct is nil")
	}

	gosize := unsafe.Sizeof(QuiclbSharedKey{})
	if gosize != uintptr(s.Size) {
		return fmt.Errorf("size mismatch: go: %d, dwarf: %d", gosize, s.Size)
	}

	fs := s.Fields

	var goff uintptr
	var doff int64
	goff = unsafe.Offsetof(QuiclbSharedKey{}.Key)
	doff = fs["key"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Key: %d, dwarf key: %d", goff, doff)
	}

	return nil
}

func Init_cryptoAssertLayout(m map[string]*DWARFStruct) error {
	if err := QuiclbSharedKeyAssertLayout(m["quiclb_shared_key"]); err != nil {
		return fmt.Errorf("quiclb_shared_key: %v", err)
	}
	return nil
}
