// Code generated by json2go. DO NOT EDIT.
package protocol

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"reflect"
)

type ControlMessageType uint8

const (
	ControlMessageType_L4LbKeepalive  ControlMessageType = 0
	ControlMessageType_L7LbKeepalive  ControlMessageType = 1
	ControlMessageType_L7LbHello      ControlMessageType = 2
	ControlMessageType_L7LbUpdate     ControlMessageType = 3
	ControlMessageType_L4LbL7LbUpdate ControlMessageType = 4
	ControlMessageType_L4LbHello      ControlMessageType = 5
	ControlMessageType_L4LbUpdate     ControlMessageType = 6
	ControlMessageType_KeyShare       ControlMessageType = 7
	ControlMessageType_WasmInstall    ControlMessageType = 8
	ControlMessageType_WasmUninstall  ControlMessageType = 9
)

func (t ControlMessageType) String() string {
	switch t {
	case ControlMessageType_L4LbKeepalive:
		return "L4LbKeepalive"
	case ControlMessageType_L7LbKeepalive:
		return "L7LbKeepalive"
	case ControlMessageType_L7LbHello:
		return "L7LbHello"
	case ControlMessageType_L7LbUpdate:
		return "L7LbUpdate"
	case ControlMessageType_L4LbL7LbUpdate:
		return "L4LbL7LbUpdate"
	case ControlMessageType_L4LbHello:
		return "L4LbHello"
	case ControlMessageType_L4LbUpdate:
		return "L4LbUpdate"
	case ControlMessageType_KeyShare:
		return "KeyShare"
	case ControlMessageType_WasmInstall:
		return "WasmInstall"
	case ControlMessageType_WasmUninstall:
		return "WasmUninstall"
	}
	return fmt.Sprintf("ControlMessageType(%d)", t)
}

type KeyType uint8

const (
	KeyType_Quiclb KeyType = 0
)

func (t KeyType) String() string {
	switch t {
	case KeyType_Quiclb:
		return "Quiclb"
	}
	return fmt.Sprintf("KeyType(%d)", t)
}

type ControlMessageHeader struct {
	Version     uint8
	Len         uint16
	MessageType ControlMessageType
}
type VisitorJJRQX interface {
	Visit(v VisitorJJRQX, name string, field any)
}
type VisitorJJRQXFunc func(v VisitorJJRQX, name string, field any)

func (f VisitorJJRQXFunc) Visit(v VisitorJJRQX, name string, field any) {
	f(v, name, field)
}

type VisitorJJRQXVisitable interface {
	Visit(v VisitorJJRQX)
}

func VisitorJJRQXToMap(v any) interface{} {
	if v == nil {
		return nil
	}
	if inter, ok := v.(VisitorJJRQXVisitable); ok {
		if p := reflect.ValueOf(inter); p.Kind() == reflect.Pointer && p.IsNil() {
			return nil
		}
		m := map[string]interface{}{}
		inter.Visit(VisitorJJRQXFunc(func(v VisitorJJRQX, name string, field any) {
			m[name] = VisitorJJRQXToMap(field)
		}))
		return m
	}
	if tf := reflect.TypeOf(v); (tf.Kind() == reflect.Slice || tf.Kind() == reflect.Array) && !(func() bool { k := tf.Elem().Kind().String(); return k[:3] == "int" || k[:3] == "uin" || k[:3] == "flo" })() {
		m := []interface{}{}
		vf := reflect.ValueOf(v)
		for i := 0; i < vf.Len(); i++ {
			index := vf.Index(i)
			if index.Kind() == reflect.Struct && index.CanAddr() {
				index = index.Addr()
			}
			m = append(m, VisitorJJRQXToMap(index.Interface()))
		}
		return m
	}
	if tf := reflect.TypeOf(v); tf.Kind() == reflect.Pointer {
		val := reflect.ValueOf(v)
		if val.IsNil() {
			return nil
		}
		return VisitorJJRQXToMap(val.Elem().Interface())
	}
	return v
}

type MachineInfo struct {
	CpuCount    uint8
	MemoryTotal uint64
	DiskTotal   uint64
}
type L7Lbinfo struct {
	ServerId   uint32
	Address    [4]uint8
	MacAddress [6]uint8
	PortLen    uint8
	Port       []uint16
}
type L4Lbinfo struct {
	ServerId       uint32
	VirtualAddress [4]uint8
	Address        [4]uint8
	MacAddress     [6]uint8
}
type L7Lbupdate struct {
	ServerId uint32
}
type KeepAliveInfo struct {
	NextPeriod    uint64
	CpuLen        uint8
	CpuUsage      []float64
	MemoryUsage   uint64
	DiskUsage     uint64
	IoUtilization float64
	LoadAvg       float64
	DiskSwap      float64
}
type L7LbportInfo struct {
	HandshakeFailure   uint64
	Rps                float64
	Success            uint64
	ClientFailure      uint64
	ServerFailure      uint64
	Disconnect         uint64
	OriginResponseTime uint64
}
type L4Lbupdate struct {
	VirtualAddress [4]uint8
}
type KeyShareInfo struct {
	Type KeyType
	Len  uint16
	Key  []uint8
}
type WasmInstallInfo struct {
	Id         uint32
	MethodLen  uint8
	Method     []uint8
	PathLen    uint16
	Path       []uint8
	BinarySize uint64
}
type WasmUninstallInfo struct {
	Id uint32
}
type L4Lbl7Lbupdate struct {
	Len  uint8
	Info []L7Lbinfo
}
type L4LbkeepAlive struct {
	Info     KeepAliveInfo
	EbpfLen  uint8
	EbpfData []uint8
}
type L7Lbhello struct {
	Machine MachineInfo
	Info    L7Lbinfo
}
type L4Lbhello struct {
	Machine MachineInfo
	Info    L4Lbinfo
}
type L7LbkeepAlive struct {
	Info        KeepAliveInfo
	Throughput  uint64
	DropCount   uint64
	PacketTotal uint64
	PortLen     uint8
	Ports       []L7LbportInfo
}
type union44_ControlMessage interface {
	isunion43_()
}
type union_45_t struct {
	L4LbKeepAlive L4LbkeepAlive
}
type union_46_t struct {
	L7LbKeepAlive L7LbkeepAlive
}
type union_47_t struct {
	L7LbHello L7Lbhello
}
type union_48_t struct {
	L7LbUpdate L7Lbupdate
}
type union_49_t struct {
	L4LbHello L4Lbhello
}
type union_50_t struct {
	L4LbL7LbUpdate L4Lbl7Lbupdate
}
type union_51_t struct {
	L4LbUpdate L4Lbupdate
}
type union_52_t struct {
	KeyShare KeyShareInfo
}
type union_53_t struct {
	WasmInstall WasmInstallInfo
}
type union_54_t struct {
	WasmUninstall WasmUninstallInfo
}
type union_55_t struct {
	Data []uint8
}
type ControlMessage struct {
	Header   ControlMessageHeader
	union43_ union44_ControlMessage
}

func (t *ControlMessageHeader) Visit(v VisitorJJRQX) {
	v.Visit(v, "Version", &t.Version)
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "MessageType", &t.MessageType)
}
func (t *ControlMessageHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *ControlMessageHeader) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Version)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Version: %w", err)
	}
	tmp1 := [2]byte{}
	binary.BigEndian.PutUint16(tmp1[:], uint16(t.Len))
	if n, err := w.Write(tmp1[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.MessageType)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.MessageType: %w", err)
	}
	return nil
}
func (t *ControlMessageHeader) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *ControlMessageHeader) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *ControlMessageHeader) Read(r io.Reader) (err error) {
	tmpVersion := [1]byte{}
	n_Version, err := io.ReadFull(r, tmpVersion[:])
	if err != nil {
		return fmt.Errorf("read Version: expect 1 byte but read %d bytes: %w", n_Version, err)
	}
	t.Version = uint8(tmpVersion[0])
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.BigEndian.Uint16(tmpLen[:]))
	tmpMessageType := [1]byte{}
	n_MessageType, err := io.ReadFull(r, tmpMessageType[:])
	if err != nil {
		return fmt.Errorf("read MessageType: expect 1 byte but read %d bytes: %w", n_MessageType, err)
	}
	t.MessageType = ControlMessageType(tmpMessageType[0])
	return nil
}

func (t *ControlMessageHeader) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *ControlMessageHeader) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode ControlMessageHeader: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *MachineInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "CpuCount", &t.CpuCount)
	v.Visit(v, "MemoryTotal", &t.MemoryTotal)
	v.Visit(v, "DiskTotal", &t.DiskTotal)
}
func (t *MachineInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *MachineInfo) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.CpuCount)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.CpuCount: %w", err)
	}
	tmp2 := [8]byte{}
	binary.BigEndian.PutUint64(tmp2[:], uint64(t.MemoryTotal))
	if n, err := w.Write(tmp2[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.MemoryTotal: %w", err)
	}
	tmp3 := [8]byte{}
	binary.BigEndian.PutUint64(tmp3[:], uint64(t.DiskTotal))
	if n, err := w.Write(tmp3[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.DiskTotal: %w", err)
	}
	return nil
}
func (t *MachineInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 17))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *MachineInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *MachineInfo) Read(r io.Reader) (err error) {
	tmpCpuCount := [1]byte{}
	n_CpuCount, err := io.ReadFull(r, tmpCpuCount[:])
	if err != nil {
		return fmt.Errorf("read CpuCount: expect 1 byte but read %d bytes: %w", n_CpuCount, err)
	}
	t.CpuCount = uint8(tmpCpuCount[0])
	tmpMemoryTotal := [8]byte{}
	n_MemoryTotal, err := io.ReadFull(r, tmpMemoryTotal[:])
	if err != nil {
		return fmt.Errorf("read MemoryTotal: expect 8 bytes but read %d bytes: %w", n_MemoryTotal, err)
	}
	t.MemoryTotal = uint64(binary.BigEndian.Uint64(tmpMemoryTotal[:]))
	tmpDiskTotal := [8]byte{}
	n_DiskTotal, err := io.ReadFull(r, tmpDiskTotal[:])
	if err != nil {
		return fmt.Errorf("read DiskTotal: expect 8 bytes but read %d bytes: %w", n_DiskTotal, err)
	}
	t.DiskTotal = uint64(binary.BigEndian.Uint64(tmpDiskTotal[:]))
	return nil
}

func (t *MachineInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *MachineInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode MachineInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L7Lbinfo) SetPort(v []uint16) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.PortLen = uint8(len(v))
	t.Port = v
	return true
}
func (t *L7Lbinfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "ServerId", &t.ServerId)
	v.Visit(v, "Address", &t.Address)
	v.Visit(v, "MacAddress", &t.MacAddress)
	v.Visit(v, "PortLen", &t.PortLen)
	v.Visit(v, "Port", &t.Port)
}
func (t *L7Lbinfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L7Lbinfo) Write(w io.Writer) (err error) {
	tmp4 := [4]byte{}
	binary.BigEndian.PutUint32(tmp4[:], uint32(t.ServerId))
	if n, err := w.Write(tmp4[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.ServerId: %w", err)
	}
	if n, err := w.Write(t.Address[:]); err != nil || n != len(t.Address) {
		return fmt.Errorf("encode Address: %w", err)
	}
	if n, err := w.Write(t.MacAddress[:]); err != nil || n != len(t.MacAddress) {
		return fmt.Errorf("encode MacAddress: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.PortLen)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.PortLen: %w", err)
	}
	len_Port := int(t.PortLen)
	if len(t.Port) != len_Port {
		return fmt.Errorf("encode Port: expect %d but got %d for length", len_Port, len(t.Port))
	}
	for _, v := range t.Port {
		tmp5 := [2]byte{}
		binary.BigEndian.PutUint16(tmp5[:], uint16(v))
		if n, err := w.Write(tmp5[:]); err != nil || n != 2 {
			return fmt.Errorf("encode v: %w", err)
		}
	}
	return nil
}
func (t *L7Lbinfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 15))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L7Lbinfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L7Lbinfo) Read(r io.Reader) (err error) {
	tmpServerId := [4]byte{}
	n_ServerId, err := io.ReadFull(r, tmpServerId[:])
	if err != nil {
		return fmt.Errorf("read ServerId: expect 4 bytes but read %d bytes: %w", n_ServerId, err)
	}
	t.ServerId = uint32(binary.BigEndian.Uint32(tmpServerId[:]))
	n_Address, err := io.ReadFull(r, t.Address[:])
	if err != nil {
		return fmt.Errorf("read Address: expect %d bytes but read %d bytes: %w", 4, n_Address, err)
	}
	n_MacAddress, err := io.ReadFull(r, t.MacAddress[:])
	if err != nil {
		return fmt.Errorf("read MacAddress: expect %d bytes but read %d bytes: %w", 6, n_MacAddress, err)
	}
	tmpPortLen := [1]byte{}
	n_PortLen, err := io.ReadFull(r, tmpPortLen[:])
	if err != nil {
		return fmt.Errorf("read PortLen: expect 1 byte but read %d bytes: %w", n_PortLen, err)
	}
	t.PortLen = uint8(tmpPortLen[0])
	len_Port := int(t.PortLen)
	for i_6 := 0; i_6 < len_Port; i_6++ {
		var tmp7_ uint16
		tmpPort := [2]byte{}
		n_Port, err := io.ReadFull(r, tmpPort[:])
		if err != nil {
			return fmt.Errorf("read Port: expect 2 bytes but read %d bytes: %w", n_Port, err)
		}
		tmp7_ = uint16(binary.BigEndian.Uint16(tmpPort[:]))
		t.Port = append(t.Port, tmp7_)
	}
	return nil
}

func (t *L7Lbinfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L7Lbinfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L7Lbinfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L4Lbinfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "ServerId", &t.ServerId)
	v.Visit(v, "VirtualAddress", &t.VirtualAddress)
	v.Visit(v, "Address", &t.Address)
	v.Visit(v, "MacAddress", &t.MacAddress)
}
func (t *L4Lbinfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L4Lbinfo) Write(w io.Writer) (err error) {
	tmp8 := [4]byte{}
	binary.BigEndian.PutUint32(tmp8[:], uint32(t.ServerId))
	if n, err := w.Write(tmp8[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.ServerId: %w", err)
	}
	if n, err := w.Write(t.VirtualAddress[:]); err != nil || n != len(t.VirtualAddress) {
		return fmt.Errorf("encode VirtualAddress: %w", err)
	}
	if n, err := w.Write(t.Address[:]); err != nil || n != len(t.Address) {
		return fmt.Errorf("encode Address: %w", err)
	}
	if n, err := w.Write(t.MacAddress[:]); err != nil || n != len(t.MacAddress) {
		return fmt.Errorf("encode MacAddress: %w", err)
	}
	return nil
}
func (t *L4Lbinfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 18))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L4Lbinfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L4Lbinfo) Read(r io.Reader) (err error) {
	tmpServerId := [4]byte{}
	n_ServerId, err := io.ReadFull(r, tmpServerId[:])
	if err != nil {
		return fmt.Errorf("read ServerId: expect 4 bytes but read %d bytes: %w", n_ServerId, err)
	}
	t.ServerId = uint32(binary.BigEndian.Uint32(tmpServerId[:]))
	n_VirtualAddress, err := io.ReadFull(r, t.VirtualAddress[:])
	if err != nil {
		return fmt.Errorf("read VirtualAddress: expect %d bytes but read %d bytes: %w", 4, n_VirtualAddress, err)
	}
	n_Address, err := io.ReadFull(r, t.Address[:])
	if err != nil {
		return fmt.Errorf("read Address: expect %d bytes but read %d bytes: %w", 4, n_Address, err)
	}
	n_MacAddress, err := io.ReadFull(r, t.MacAddress[:])
	if err != nil {
		return fmt.Errorf("read MacAddress: expect %d bytes but read %d bytes: %w", 6, n_MacAddress, err)
	}
	return nil
}

func (t *L4Lbinfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L4Lbinfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L4Lbinfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L7Lbupdate) Visit(v VisitorJJRQX) {
	v.Visit(v, "ServerId", &t.ServerId)
}
func (t *L7Lbupdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L7Lbupdate) Write(w io.Writer) (err error) {
	tmp9 := [4]byte{}
	binary.BigEndian.PutUint32(tmp9[:], uint32(t.ServerId))
	if n, err := w.Write(tmp9[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.ServerId: %w", err)
	}
	return nil
}
func (t *L7Lbupdate) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L7Lbupdate) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L7Lbupdate) Read(r io.Reader) (err error) {
	tmpServerId := [4]byte{}
	n_ServerId, err := io.ReadFull(r, tmpServerId[:])
	if err != nil {
		return fmt.Errorf("read ServerId: expect 4 bytes but read %d bytes: %w", n_ServerId, err)
	}
	t.ServerId = uint32(binary.BigEndian.Uint32(tmpServerId[:]))
	return nil
}

func (t *L7Lbupdate) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L7Lbupdate) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L7Lbupdate: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *KeepAliveInfo) SetCpuUsage(v []float64) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.CpuLen = uint8(len(v))
	t.CpuUsage = v
	return true
}
func (t *KeepAliveInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "NextPeriod", &t.NextPeriod)
	v.Visit(v, "CpuLen", &t.CpuLen)
	v.Visit(v, "CpuUsage", &t.CpuUsage)
	v.Visit(v, "MemoryUsage", &t.MemoryUsage)
	v.Visit(v, "DiskUsage", &t.DiskUsage)
	v.Visit(v, "IoUtilization", &t.IoUtilization)
	v.Visit(v, "LoadAvg", &t.LoadAvg)
	v.Visit(v, "DiskSwap", &t.DiskSwap)
}
func (t *KeepAliveInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *KeepAliveInfo) Write(w io.Writer) (err error) {
	tmp10 := [8]byte{}
	binary.BigEndian.PutUint64(tmp10[:], uint64(t.NextPeriod))
	if n, err := w.Write(tmp10[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.NextPeriod: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.CpuLen)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.CpuLen: %w", err)
	}
	len_CpuUsage := int(t.CpuLen)
	if len(t.CpuUsage) != len_CpuUsage {
		return fmt.Errorf("encode CpuUsage: expect %d but got %d for length", len_CpuUsage, len(t.CpuUsage))
	}
	for _, v := range t.CpuUsage {
		tmp11 := math.Float64bits(v)
		tmp12 := [8]byte{}
		binary.LittleEndian.PutUint64(tmp12[:], uint64(tmp11))
		if n, err := w.Write(tmp12[:]); err != nil || n != 8 {
			return fmt.Errorf("encode tmp11: %w", err)
		}
	}
	tmp13 := [8]byte{}
	binary.BigEndian.PutUint64(tmp13[:], uint64(t.MemoryUsage))
	if n, err := w.Write(tmp13[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.MemoryUsage: %w", err)
	}
	tmp14 := [8]byte{}
	binary.BigEndian.PutUint64(tmp14[:], uint64(t.DiskUsage))
	if n, err := w.Write(tmp14[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.DiskUsage: %w", err)
	}
	tmp15 := math.Float64bits(t.IoUtilization)
	tmp16 := [8]byte{}
	binary.LittleEndian.PutUint64(tmp16[:], uint64(tmp15))
	if n, err := w.Write(tmp16[:]); err != nil || n != 8 {
		return fmt.Errorf("encode tmp15: %w", err)
	}
	tmp17 := math.Float64bits(t.LoadAvg)
	tmp18 := [8]byte{}
	binary.LittleEndian.PutUint64(tmp18[:], uint64(tmp17))
	if n, err := w.Write(tmp18[:]); err != nil || n != 8 {
		return fmt.Errorf("encode tmp17: %w", err)
	}
	tmp19 := math.Float64bits(t.DiskSwap)
	tmp20 := [8]byte{}
	binary.LittleEndian.PutUint64(tmp20[:], uint64(tmp19))
	if n, err := w.Write(tmp20[:]); err != nil || n != 8 {
		return fmt.Errorf("encode tmp19: %w", err)
	}
	return nil
}
func (t *KeepAliveInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 9))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *KeepAliveInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *KeepAliveInfo) Read(r io.Reader) (err error) {
	tmpNextPeriod := [8]byte{}
	n_NextPeriod, err := io.ReadFull(r, tmpNextPeriod[:])
	if err != nil {
		return fmt.Errorf("read NextPeriod: expect 8 bytes but read %d bytes: %w", n_NextPeriod, err)
	}
	t.NextPeriod = uint64(binary.BigEndian.Uint64(tmpNextPeriod[:]))
	tmpCpuLen := [1]byte{}
	n_CpuLen, err := io.ReadFull(r, tmpCpuLen[:])
	if err != nil {
		return fmt.Errorf("read CpuLen: expect 1 byte but read %d bytes: %w", n_CpuLen, err)
	}
	t.CpuLen = uint8(tmpCpuLen[0])
	len_CpuUsage := int(t.CpuLen)
	for i_21 := 0; i_21 < len_CpuUsage; i_21++ {
		var tmp22_ float64
		var tmp_CpuUsage uint64
		tmpCpuUsage := [8]byte{}
		n_CpuUsage, err := io.ReadFull(r, tmpCpuUsage[:])
		if err != nil {
			return fmt.Errorf("read CpuUsage: expect 8 bytes but read %d bytes: %w", n_CpuUsage, err)
		}
		tmp_CpuUsage = uint64(binary.LittleEndian.Uint64(tmpCpuUsage[:]))
		tmp22_ = math.Float64frombits(uint64(tmp_CpuUsage))
		t.CpuUsage = append(t.CpuUsage, tmp22_)
	}
	tmpMemoryUsage := [8]byte{}
	n_MemoryUsage, err := io.ReadFull(r, tmpMemoryUsage[:])
	if err != nil {
		return fmt.Errorf("read MemoryUsage: expect 8 bytes but read %d bytes: %w", n_MemoryUsage, err)
	}
	t.MemoryUsage = uint64(binary.BigEndian.Uint64(tmpMemoryUsage[:]))
	tmpDiskUsage := [8]byte{}
	n_DiskUsage, err := io.ReadFull(r, tmpDiskUsage[:])
	if err != nil {
		return fmt.Errorf("read DiskUsage: expect 8 bytes but read %d bytes: %w", n_DiskUsage, err)
	}
	t.DiskUsage = uint64(binary.BigEndian.Uint64(tmpDiskUsage[:]))
	var tmp_IoUtilization uint64
	tmpIoUtilization := [8]byte{}
	n_IoUtilization, err := io.ReadFull(r, tmpIoUtilization[:])
	if err != nil {
		return fmt.Errorf("read IoUtilization: expect 8 bytes but read %d bytes: %w", n_IoUtilization, err)
	}
	tmp_IoUtilization = uint64(binary.LittleEndian.Uint64(tmpIoUtilization[:]))
	t.IoUtilization = math.Float64frombits(uint64(tmp_IoUtilization))
	var tmp_LoadAvg uint64
	tmpLoadAvg := [8]byte{}
	n_LoadAvg, err := io.ReadFull(r, tmpLoadAvg[:])
	if err != nil {
		return fmt.Errorf("read LoadAvg: expect 8 bytes but read %d bytes: %w", n_LoadAvg, err)
	}
	tmp_LoadAvg = uint64(binary.LittleEndian.Uint64(tmpLoadAvg[:]))
	t.LoadAvg = math.Float64frombits(uint64(tmp_LoadAvg))
	var tmp_DiskSwap uint64
	tmpDiskSwap := [8]byte{}
	n_DiskSwap, err := io.ReadFull(r, tmpDiskSwap[:])
	if err != nil {
		return fmt.Errorf("read DiskSwap: expect 8 bytes but read %d bytes: %w", n_DiskSwap, err)
	}
	tmp_DiskSwap = uint64(binary.LittleEndian.Uint64(tmpDiskSwap[:]))
	t.DiskSwap = math.Float64frombits(uint64(tmp_DiskSwap))
	return nil
}

func (t *KeepAliveInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *KeepAliveInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode KeepAliveInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L7LbportInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "HandshakeFailure", &t.HandshakeFailure)
	v.Visit(v, "Rps", &t.Rps)
	v.Visit(v, "Success", &t.Success)
	v.Visit(v, "ClientFailure", &t.ClientFailure)
	v.Visit(v, "ServerFailure", &t.ServerFailure)
	v.Visit(v, "Disconnect", &t.Disconnect)
	v.Visit(v, "OriginResponseTime", &t.OriginResponseTime)
}
func (t *L7LbportInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L7LbportInfo) Write(w io.Writer) (err error) {
	tmp23 := [8]byte{}
	binary.BigEndian.PutUint64(tmp23[:], uint64(t.HandshakeFailure))
	if n, err := w.Write(tmp23[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.HandshakeFailure: %w", err)
	}
	tmp24 := math.Float64bits(t.Rps)
	tmp25 := [8]byte{}
	binary.LittleEndian.PutUint64(tmp25[:], uint64(tmp24))
	if n, err := w.Write(tmp25[:]); err != nil || n != 8 {
		return fmt.Errorf("encode tmp24: %w", err)
	}
	tmp26 := [8]byte{}
	binary.BigEndian.PutUint64(tmp26[:], uint64(t.Success))
	if n, err := w.Write(tmp26[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.Success: %w", err)
	}
	tmp27 := [8]byte{}
	binary.BigEndian.PutUint64(tmp27[:], uint64(t.ClientFailure))
	if n, err := w.Write(tmp27[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.ClientFailure: %w", err)
	}
	tmp28 := [8]byte{}
	binary.BigEndian.PutUint64(tmp28[:], uint64(t.ServerFailure))
	if n, err := w.Write(tmp28[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.ServerFailure: %w", err)
	}
	tmp29 := [8]byte{}
	binary.BigEndian.PutUint64(tmp29[:], uint64(t.Disconnect))
	if n, err := w.Write(tmp29[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.Disconnect: %w", err)
	}
	tmp30 := [8]byte{}
	binary.BigEndian.PutUint64(tmp30[:], uint64(t.OriginResponseTime))
	if n, err := w.Write(tmp30[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.OriginResponseTime: %w", err)
	}
	return nil
}
func (t *L7LbportInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 56))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L7LbportInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L7LbportInfo) Read(r io.Reader) (err error) {
	tmpHandshakeFailure := [8]byte{}
	n_HandshakeFailure, err := io.ReadFull(r, tmpHandshakeFailure[:])
	if err != nil {
		return fmt.Errorf("read HandshakeFailure: expect 8 bytes but read %d bytes: %w", n_HandshakeFailure, err)
	}
	t.HandshakeFailure = uint64(binary.BigEndian.Uint64(tmpHandshakeFailure[:]))
	var tmp_Rps uint64
	tmpRps := [8]byte{}
	n_Rps, err := io.ReadFull(r, tmpRps[:])
	if err != nil {
		return fmt.Errorf("read Rps: expect 8 bytes but read %d bytes: %w", n_Rps, err)
	}
	tmp_Rps = uint64(binary.LittleEndian.Uint64(tmpRps[:]))
	t.Rps = math.Float64frombits(uint64(tmp_Rps))
	tmpSuccess := [8]byte{}
	n_Success, err := io.ReadFull(r, tmpSuccess[:])
	if err != nil {
		return fmt.Errorf("read Success: expect 8 bytes but read %d bytes: %w", n_Success, err)
	}
	t.Success = uint64(binary.BigEndian.Uint64(tmpSuccess[:]))
	tmpClientFailure := [8]byte{}
	n_ClientFailure, err := io.ReadFull(r, tmpClientFailure[:])
	if err != nil {
		return fmt.Errorf("read ClientFailure: expect 8 bytes but read %d bytes: %w", n_ClientFailure, err)
	}
	t.ClientFailure = uint64(binary.BigEndian.Uint64(tmpClientFailure[:]))
	tmpServerFailure := [8]byte{}
	n_ServerFailure, err := io.ReadFull(r, tmpServerFailure[:])
	if err != nil {
		return fmt.Errorf("read ServerFailure: expect 8 bytes but read %d bytes: %w", n_ServerFailure, err)
	}
	t.ServerFailure = uint64(binary.BigEndian.Uint64(tmpServerFailure[:]))
	tmpDisconnect := [8]byte{}
	n_Disconnect, err := io.ReadFull(r, tmpDisconnect[:])
	if err != nil {
		return fmt.Errorf("read Disconnect: expect 8 bytes but read %d bytes: %w", n_Disconnect, err)
	}
	t.Disconnect = uint64(binary.BigEndian.Uint64(tmpDisconnect[:]))
	tmpOriginResponseTime := [8]byte{}
	n_OriginResponseTime, err := io.ReadFull(r, tmpOriginResponseTime[:])
	if err != nil {
		return fmt.Errorf("read OriginResponseTime: expect 8 bytes but read %d bytes: %w", n_OriginResponseTime, err)
	}
	t.OriginResponseTime = uint64(binary.BigEndian.Uint64(tmpOriginResponseTime[:]))
	return nil
}

func (t *L7LbportInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L7LbportInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L7LbportInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L4Lbupdate) Visit(v VisitorJJRQX) {
	v.Visit(v, "VirtualAddress", &t.VirtualAddress)
}
func (t *L4Lbupdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L4Lbupdate) Write(w io.Writer) (err error) {
	if n, err := w.Write(t.VirtualAddress[:]); err != nil || n != len(t.VirtualAddress) {
		return fmt.Errorf("encode VirtualAddress: %w", err)
	}
	return nil
}
func (t *L4Lbupdate) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L4Lbupdate) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L4Lbupdate) Read(r io.Reader) (err error) {
	n_VirtualAddress, err := io.ReadFull(r, t.VirtualAddress[:])
	if err != nil {
		return fmt.Errorf("read VirtualAddress: expect %d bytes but read %d bytes: %w", 4, n_VirtualAddress, err)
	}
	return nil
}

func (t *L4Lbupdate) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L4Lbupdate) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L4Lbupdate: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *KeyShareInfo) SetKey(v []uint8) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.Len = uint16(len(v))
	t.Key = v
	return true
}
func (t *KeyShareInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "Type", &t.Type)
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Key", &t.Key)
}
func (t *KeyShareInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *KeyShareInfo) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Type)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Type: %w", err)
	}
	tmp31 := [2]byte{}
	binary.BigEndian.PutUint16(tmp31[:], uint16(t.Len))
	if n, err := w.Write(tmp31[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Key := int(t.Len)
	if len(t.Key) != len_Key {
		return fmt.Errorf("encode Key: expect %d bytes but got %d bytes", len_Key, len(t.Key))
	}
	if n, err := w.Write(t.Key); err != nil || n != len(t.Key) {
		return fmt.Errorf("encode Key: %w", err)
	}
	return nil
}
func (t *KeyShareInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 3))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *KeyShareInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *KeyShareInfo) Read(r io.Reader) (err error) {
	tmpType := [1]byte{}
	n_Type, err := io.ReadFull(r, tmpType[:])
	if err != nil {
		return fmt.Errorf("read Type: expect 1 byte but read %d bytes: %w", n_Type, err)
	}
	t.Type = KeyType(tmpType[0])
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.BigEndian.Uint16(tmpLen[:]))
	len_Key := int(t.Len)
	if len_Key != 0 {
		tmpKey := make([]byte, len_Key)
		n_Key, err := io.ReadFull(r, tmpKey[:])
		if err != nil {
			return fmt.Errorf("read Key: expect %d bytes but read %d bytes: %w", len_Key, n_Key, err)
		}
		t.Key = tmpKey[:]
	} else {
		t.Key = nil
	}
	return nil
}

func (t *KeyShareInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *KeyShareInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode KeyShareInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *WasmInstallInfo) SetMethod(v []uint8) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.MethodLen = uint8(len(v))
	t.Method = v
	return true
}
func (t *WasmInstallInfo) SetPath(v []uint8) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.PathLen = uint16(len(v))
	t.Path = v
	return true
}
func (t *WasmInstallInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "Id", &t.Id)
	v.Visit(v, "MethodLen", &t.MethodLen)
	v.Visit(v, "Method", &t.Method)
	v.Visit(v, "PathLen", &t.PathLen)
	v.Visit(v, "Path", &t.Path)
	v.Visit(v, "BinarySize", &t.BinarySize)
}
func (t *WasmInstallInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *WasmInstallInfo) Write(w io.Writer) (err error) {
	tmp32 := [4]byte{}
	binary.BigEndian.PutUint32(tmp32[:], uint32(t.Id))
	if n, err := w.Write(tmp32[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.Id: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.MethodLen)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.MethodLen: %w", err)
	}
	len_Method := int(t.MethodLen)
	if len(t.Method) != len_Method {
		return fmt.Errorf("encode Method: expect %d bytes but got %d bytes", len_Method, len(t.Method))
	}
	if n, err := w.Write(t.Method); err != nil || n != len(t.Method) {
		return fmt.Errorf("encode Method: %w", err)
	}
	tmp33 := [2]byte{}
	binary.BigEndian.PutUint16(tmp33[:], uint16(t.PathLen))
	if n, err := w.Write(tmp33[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.PathLen: %w", err)
	}
	len_Path := int(t.PathLen)
	if len(t.Path) != len_Path {
		return fmt.Errorf("encode Path: expect %d bytes but got %d bytes", len_Path, len(t.Path))
	}
	if n, err := w.Write(t.Path); err != nil || n != len(t.Path) {
		return fmt.Errorf("encode Path: %w", err)
	}
	tmp34 := [8]byte{}
	binary.BigEndian.PutUint64(tmp34[:], uint64(t.BinarySize))
	if n, err := w.Write(tmp34[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.BinarySize: %w", err)
	}
	return nil
}
func (t *WasmInstallInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 5))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *WasmInstallInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *WasmInstallInfo) Read(r io.Reader) (err error) {
	tmpId := [4]byte{}
	n_Id, err := io.ReadFull(r, tmpId[:])
	if err != nil {
		return fmt.Errorf("read Id: expect 4 bytes but read %d bytes: %w", n_Id, err)
	}
	t.Id = uint32(binary.BigEndian.Uint32(tmpId[:]))
	tmpMethodLen := [1]byte{}
	n_MethodLen, err := io.ReadFull(r, tmpMethodLen[:])
	if err != nil {
		return fmt.Errorf("read MethodLen: expect 1 byte but read %d bytes: %w", n_MethodLen, err)
	}
	t.MethodLen = uint8(tmpMethodLen[0])
	len_Method := int(t.MethodLen)
	if len_Method != 0 {
		tmpMethod := make([]byte, len_Method)
		n_Method, err := io.ReadFull(r, tmpMethod[:])
		if err != nil {
			return fmt.Errorf("read Method: expect %d bytes but read %d bytes: %w", len_Method, n_Method, err)
		}
		t.Method = tmpMethod[:]
	} else {
		t.Method = nil
	}
	tmpPathLen := [2]byte{}
	n_PathLen, err := io.ReadFull(r, tmpPathLen[:])
	if err != nil {
		return fmt.Errorf("read PathLen: expect 2 bytes but read %d bytes: %w", n_PathLen, err)
	}
	t.PathLen = uint16(binary.BigEndian.Uint16(tmpPathLen[:]))
	len_Path := int(t.PathLen)
	if len_Path != 0 {
		tmpPath := make([]byte, len_Path)
		n_Path, err := io.ReadFull(r, tmpPath[:])
		if err != nil {
			return fmt.Errorf("read Path: expect %d bytes but read %d bytes: %w", len_Path, n_Path, err)
		}
		t.Path = tmpPath[:]
	} else {
		t.Path = nil
	}
	tmpBinarySize := [8]byte{}
	n_BinarySize, err := io.ReadFull(r, tmpBinarySize[:])
	if err != nil {
		return fmt.Errorf("read BinarySize: expect 8 bytes but read %d bytes: %w", n_BinarySize, err)
	}
	t.BinarySize = uint64(binary.BigEndian.Uint64(tmpBinarySize[:]))
	return nil
}

func (t *WasmInstallInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *WasmInstallInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode WasmInstallInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *WasmUninstallInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "Id", &t.Id)
}
func (t *WasmUninstallInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *WasmUninstallInfo) Write(w io.Writer) (err error) {
	tmp35 := [4]byte{}
	binary.BigEndian.PutUint32(tmp35[:], uint32(t.Id))
	if n, err := w.Write(tmp35[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.Id: %w", err)
	}
	return nil
}
func (t *WasmUninstallInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *WasmUninstallInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *WasmUninstallInfo) Read(r io.Reader) (err error) {
	tmpId := [4]byte{}
	n_Id, err := io.ReadFull(r, tmpId[:])
	if err != nil {
		return fmt.Errorf("read Id: expect 4 bytes but read %d bytes: %w", n_Id, err)
	}
	t.Id = uint32(binary.BigEndian.Uint32(tmpId[:]))
	return nil
}

func (t *WasmUninstallInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *WasmUninstallInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode WasmUninstallInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L4Lbl7Lbupdate) SetInfo(v []L7Lbinfo) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.Len = uint8(len(v))
	t.Info = v
	return true
}
func (t *L4Lbl7Lbupdate) Visit(v VisitorJJRQX) {
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Info", &t.Info)
}
func (t *L4Lbl7Lbupdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L4Lbl7Lbupdate) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Len)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Info := int(t.Len)
	if len(t.Info) != len_Info {
		return fmt.Errorf("encode Info: expect %d but got %d for length", len_Info, len(t.Info))
	}
	for _, v := range t.Info {
		if err := v.Write(w); err != nil {
			return fmt.Errorf("encode Info: %w", err)
		}
	}
	return nil
}
func (t *L4Lbl7Lbupdate) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 1))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L4Lbl7Lbupdate) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L4Lbl7Lbupdate) Read(r io.Reader) (err error) {
	tmpLen := [1]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 1 byte but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint8(tmpLen[0])
	len_Info := int(t.Len)
	for i_36 := 0; i_36 < len_Info; i_36++ {
		var tmp37_ L7Lbinfo
		if err := tmp37_.Read(r); err != nil {
			return fmt.Errorf("read Info: %w", err)
		}
		t.Info = append(t.Info, tmp37_)
	}
	return nil
}

func (t *L4Lbl7Lbupdate) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L4Lbl7Lbupdate) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L4Lbl7Lbupdate: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L4LbkeepAlive) SetEbpfData(v []uint8) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.EbpfLen = uint8(len(v))
	t.EbpfData = v
	return true
}
func (t *L4LbkeepAlive) Visit(v VisitorJJRQX) {
	v.Visit(v, "Info", &t.Info)
	v.Visit(v, "EbpfLen", &t.EbpfLen)
	v.Visit(v, "EbpfData", &t.EbpfData)
}
func (t *L4LbkeepAlive) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L4LbkeepAlive) Write(w io.Writer) (err error) {
	if err := t.Info.Write(w); err != nil {
		return fmt.Errorf("encode Info: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.EbpfLen)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.EbpfLen: %w", err)
	}
	len_EbpfData := int(t.EbpfLen)
	if len(t.EbpfData) != len_EbpfData {
		return fmt.Errorf("encode EbpfData: expect %d bytes but got %d bytes", len_EbpfData, len(t.EbpfData))
	}
	if n, err := w.Write(t.EbpfData); err != nil || n != len(t.EbpfData) {
		return fmt.Errorf("encode EbpfData: %w", err)
	}
	return nil
}
func (t *L4LbkeepAlive) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 0))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L4LbkeepAlive) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L4LbkeepAlive) Read(r io.Reader) (err error) {
	if err := t.Info.Read(r); err != nil {
		return fmt.Errorf("read Info: %w", err)
	}
	tmpEbpfLen := [1]byte{}
	n_EbpfLen, err := io.ReadFull(r, tmpEbpfLen[:])
	if err != nil {
		return fmt.Errorf("read EbpfLen: expect 1 byte but read %d bytes: %w", n_EbpfLen, err)
	}
	t.EbpfLen = uint8(tmpEbpfLen[0])
	len_EbpfData := int(t.EbpfLen)
	if len_EbpfData != 0 {
		tmpEbpfData := make([]byte, len_EbpfData)
		n_EbpfData, err := io.ReadFull(r, tmpEbpfData[:])
		if err != nil {
			return fmt.Errorf("read EbpfData: expect %d bytes but read %d bytes: %w", len_EbpfData, n_EbpfData, err)
		}
		t.EbpfData = tmpEbpfData[:]
	} else {
		t.EbpfData = nil
	}
	return nil
}

func (t *L4LbkeepAlive) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L4LbkeepAlive) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L4LbkeepAlive: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L7Lbhello) Visit(v VisitorJJRQX) {
	v.Visit(v, "Machine", &t.Machine)
	v.Visit(v, "Info", &t.Info)
}
func (t *L7Lbhello) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L7Lbhello) Write(w io.Writer) (err error) {
	if err := t.Machine.Write(w); err != nil {
		return fmt.Errorf("encode Machine: %w", err)
	}
	if err := t.Info.Write(w); err != nil {
		return fmt.Errorf("encode Info: %w", err)
	}
	return nil
}
func (t *L7Lbhello) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 17))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L7Lbhello) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L7Lbhello) Read(r io.Reader) (err error) {
	if err := t.Machine.Read(r); err != nil {
		return fmt.Errorf("read Machine: %w", err)
	}
	if err := t.Info.Read(r); err != nil {
		return fmt.Errorf("read Info: %w", err)
	}
	return nil
}

func (t *L7Lbhello) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L7Lbhello) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L7Lbhello: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L4Lbhello) Visit(v VisitorJJRQX) {
	v.Visit(v, "Machine", &t.Machine)
	v.Visit(v, "Info", &t.Info)
}
func (t *L4Lbhello) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L4Lbhello) Write(w io.Writer) (err error) {
	if err := t.Machine.Write(w); err != nil {
		return fmt.Errorf("encode Machine: %w", err)
	}
	if err := t.Info.Write(w); err != nil {
		return fmt.Errorf("encode Info: %w", err)
	}
	return nil
}
func (t *L4Lbhello) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 35))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L4Lbhello) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L4Lbhello) Read(r io.Reader) (err error) {
	if err := t.Machine.Read(r); err != nil {
		return fmt.Errorf("read Machine: %w", err)
	}
	if err := t.Info.Read(r); err != nil {
		return fmt.Errorf("read Info: %w", err)
	}
	return nil
}

func (t *L4Lbhello) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L4Lbhello) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L4Lbhello: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L7LbkeepAlive) SetPorts(v []L7LbportInfo) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.PortLen = uint8(len(v))
	t.Ports = v
	return true
}
func (t *L7LbkeepAlive) Visit(v VisitorJJRQX) {
	v.Visit(v, "Info", &t.Info)
	v.Visit(v, "Throughput", &t.Throughput)
	v.Visit(v, "DropCount", &t.DropCount)
	v.Visit(v, "PacketTotal", &t.PacketTotal)
	v.Visit(v, "PortLen", &t.PortLen)
	v.Visit(v, "Ports", &t.Ports)
}
func (t *L7LbkeepAlive) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L7LbkeepAlive) Write(w io.Writer) (err error) {
	if err := t.Info.Write(w); err != nil {
		return fmt.Errorf("encode Info: %w", err)
	}
	tmp38 := [8]byte{}
	binary.BigEndian.PutUint64(tmp38[:], uint64(t.Throughput))
	if n, err := w.Write(tmp38[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.Throughput: %w", err)
	}
	tmp39 := [8]byte{}
	binary.BigEndian.PutUint64(tmp39[:], uint64(t.DropCount))
	if n, err := w.Write(tmp39[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.DropCount: %w", err)
	}
	tmp40 := [8]byte{}
	binary.BigEndian.PutUint64(tmp40[:], uint64(t.PacketTotal))
	if n, err := w.Write(tmp40[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.PacketTotal: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.PortLen)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.PortLen: %w", err)
	}
	len_Ports := int(t.PortLen)
	if len(t.Ports) != len_Ports {
		return fmt.Errorf("encode Ports: expect %d but got %d for length", len_Ports, len(t.Ports))
	}
	for _, v := range t.Ports {
		if err := v.Write(w); err != nil {
			return fmt.Errorf("encode Ports: %w", err)
		}
	}
	return nil
}
func (t *L7LbkeepAlive) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 0))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L7LbkeepAlive) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L7LbkeepAlive) Read(r io.Reader) (err error) {
	if err := t.Info.Read(r); err != nil {
		return fmt.Errorf("read Info: %w", err)
	}
	tmpThroughput := [8]byte{}
	n_Throughput, err := io.ReadFull(r, tmpThroughput[:])
	if err != nil {
		return fmt.Errorf("read Throughput: expect 8 bytes but read %d bytes: %w", n_Throughput, err)
	}
	t.Throughput = uint64(binary.BigEndian.Uint64(tmpThroughput[:]))
	tmpDropCount := [8]byte{}
	n_DropCount, err := io.ReadFull(r, tmpDropCount[:])
	if err != nil {
		return fmt.Errorf("read DropCount: expect 8 bytes but read %d bytes: %w", n_DropCount, err)
	}
	t.DropCount = uint64(binary.BigEndian.Uint64(tmpDropCount[:]))
	tmpPacketTotal := [8]byte{}
	n_PacketTotal, err := io.ReadFull(r, tmpPacketTotal[:])
	if err != nil {
		return fmt.Errorf("read PacketTotal: expect 8 bytes but read %d bytes: %w", n_PacketTotal, err)
	}
	t.PacketTotal = uint64(binary.BigEndian.Uint64(tmpPacketTotal[:]))
	tmpPortLen := [1]byte{}
	n_PortLen, err := io.ReadFull(r, tmpPortLen[:])
	if err != nil {
		return fmt.Errorf("read PortLen: expect 1 byte but read %d bytes: %w", n_PortLen, err)
	}
	t.PortLen = uint8(tmpPortLen[0])
	len_Ports := int(t.PortLen)
	for i_41 := 0; i_41 < len_Ports; i_41++ {
		var tmp42_ L7LbportInfo
		if err := tmp42_.Read(r); err != nil {
			return fmt.Errorf("read Ports: %w", err)
		}
		t.Ports = append(t.Ports, tmp42_)
	}
	return nil
}

func (t *L7LbkeepAlive) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L7LbkeepAlive) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L7LbkeepAlive: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *union_45_t) isunion43_() {}
func (t *union_46_t) isunion43_() {}
func (t *union_47_t) isunion43_() {}
func (t *union_48_t) isunion43_() {}
func (t *union_49_t) isunion43_() {}
func (t *union_50_t) isunion43_() {}
func (t *union_51_t) isunion43_() {}
func (t *union_52_t) isunion43_() {}
func (t *union_53_t) isunion43_() {}
func (t *union_54_t) isunion43_() {}
func (t *union_55_t) isunion43_() {}
func (t *ControlMessage) Data() *[]uint8 {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmUninstall {
		return nil
	} else if true {
		if _, ok := t.union43_.(*union_55_t); !ok {
			return nil // not set
		}
		tmp := []uint8(t.union43_.(*union_55_t).Data)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetData(v []uint8) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmUninstall {
		return false
	} else if true {
		if _, ok := t.union43_.(*union_55_t); !ok {
			t.union43_ = &union_55_t{}
		}
		t.union43_.(*union_55_t).Data = []uint8(v)
		return true
	}
	return false
}
func (t *ControlMessage) KeyShare() *KeyShareInfo {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		if _, ok := t.union43_.(*union_52_t); !ok {
			return nil // not set
		}
		tmp := KeyShareInfo(t.union43_.(*union_52_t).KeyShare)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetKeyShare(v KeyShareInfo) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		if _, ok := t.union43_.(*union_52_t); !ok {
			t.union43_ = &union_52_t{}
		}
		t.union43_.(*union_52_t).KeyShare = KeyShareInfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) L4LbHello() *L4Lbhello {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		if _, ok := t.union43_.(*union_49_t); !ok {
			return nil // not set
		}
		tmp := L4Lbhello(t.union43_.(*union_49_t).L4LbHello)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL4LbHello(v L4Lbhello) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		if _, ok := t.union43_.(*union_49_t); !ok {
			t.union43_ = &union_49_t{}
		}
		t.union43_.(*union_49_t).L4LbHello = L4Lbhello(v)
		return true
	}
	return false
}
func (t *ControlMessage) L4LbKeepAlive() *L4LbkeepAlive {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		if _, ok := t.union43_.(*union_45_t); !ok {
			return nil // not set
		}
		tmp := L4LbkeepAlive(t.union43_.(*union_45_t).L4LbKeepAlive)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL4LbKeepAlive(v L4LbkeepAlive) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		if _, ok := t.union43_.(*union_45_t); !ok {
			t.union43_ = &union_45_t{}
		}
		t.union43_.(*union_45_t).L4LbKeepAlive = L4LbkeepAlive(v)
		return true
	}
	return false
}
func (t *ControlMessage) L4LbL7LbUpdate() *L4Lbl7Lbupdate {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		if _, ok := t.union43_.(*union_50_t); !ok {
			return nil // not set
		}
		tmp := L4Lbl7Lbupdate(t.union43_.(*union_50_t).L4LbL7LbUpdate)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL4LbL7LbUpdate(v L4Lbl7Lbupdate) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		if _, ok := t.union43_.(*union_50_t); !ok {
			t.union43_ = &union_50_t{}
		}
		t.union43_.(*union_50_t).L4LbL7LbUpdate = L4Lbl7Lbupdate(v)
		return true
	}
	return false
}
func (t *ControlMessage) L4LbUpdate() *L4Lbupdate {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		if _, ok := t.union43_.(*union_51_t); !ok {
			return nil // not set
		}
		tmp := L4Lbupdate(t.union43_.(*union_51_t).L4LbUpdate)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL4LbUpdate(v L4Lbupdate) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		if _, ok := t.union43_.(*union_51_t); !ok {
			t.union43_ = &union_51_t{}
		}
		t.union43_.(*union_51_t).L4LbUpdate = L4Lbupdate(v)
		return true
	}
	return false
}
func (t *ControlMessage) L7LbHello() *L7Lbhello {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		if _, ok := t.union43_.(*union_47_t); !ok {
			return nil // not set
		}
		tmp := L7Lbhello(t.union43_.(*union_47_t).L7LbHello)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL7LbHello(v L7Lbhello) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		if _, ok := t.union43_.(*union_47_t); !ok {
			t.union43_ = &union_47_t{}
		}
		t.union43_.(*union_47_t).L7LbHello = L7Lbhello(v)
		return true
	}
	return false
}
func (t *ControlMessage) L7LbKeepAlive() *L7LbkeepAlive {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		if _, ok := t.union43_.(*union_46_t); !ok {
			return nil // not set
		}
		tmp := L7LbkeepAlive(t.union43_.(*union_46_t).L7LbKeepAlive)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL7LbKeepAlive(v L7LbkeepAlive) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		if _, ok := t.union43_.(*union_46_t); !ok {
			t.union43_ = &union_46_t{}
		}
		t.union43_.(*union_46_t).L7LbKeepAlive = L7LbkeepAlive(v)
		return true
	}
	return false
}
func (t *ControlMessage) L7LbUpdate() *L7Lbupdate {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		if _, ok := t.union43_.(*union_48_t); !ok {
			return nil // not set
		}
		tmp := L7Lbupdate(t.union43_.(*union_48_t).L7LbUpdate)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL7LbUpdate(v L7Lbupdate) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		if _, ok := t.union43_.(*union_48_t); !ok {
			t.union43_ = &union_48_t{}
		}
		t.union43_.(*union_48_t).L7LbUpdate = L7Lbupdate(v)
		return true
	}
	return false
}
func (t *ControlMessage) WasmInstall() *WasmInstallInfo {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		if _, ok := t.union43_.(*union_53_t); !ok {
			return nil // not set
		}
		tmp := WasmInstallInfo(t.union43_.(*union_53_t).WasmInstall)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetWasmInstall(v WasmInstallInfo) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		if _, ok := t.union43_.(*union_53_t); !ok {
			t.union43_ = &union_53_t{}
		}
		t.union43_.(*union_53_t).WasmInstall = WasmInstallInfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) WasmUninstall() *WasmUninstallInfo {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmUninstall {
		if _, ok := t.union43_.(*union_54_t); !ok {
			return nil // not set
		}
		tmp := WasmUninstallInfo(t.union43_.(*union_54_t).WasmUninstall)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetWasmUninstall(v WasmUninstallInfo) bool {
	if t.Header.MessageType == ControlMessageType_L4LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbKeepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmUninstall {
		if _, ok := t.union43_.(*union_54_t); !ok {
			t.union43_ = &union_54_t{}
		}
		t.union43_.(*union_54_t).WasmUninstall = WasmUninstallInfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) Visit(v VisitorJJRQX) {
	v.Visit(v, "Header", &t.Header)
	v.Visit(v, "Data", (t.Data()))
	v.Visit(v, "KeyShare", (t.KeyShare()))
	v.Visit(v, "L4LbHello", (t.L4LbHello()))
	v.Visit(v, "L4LbKeepAlive", (t.L4LbKeepAlive()))
	v.Visit(v, "L4LbL7LbUpdate", (t.L4LbL7LbUpdate()))
	v.Visit(v, "L4LbUpdate", (t.L4LbUpdate()))
	v.Visit(v, "L7LbHello", (t.L7LbHello()))
	v.Visit(v, "L7LbKeepAlive", (t.L7LbKeepAlive()))
	v.Visit(v, "L7LbUpdate", (t.L7LbUpdate()))
	v.Visit(v, "WasmInstall", (t.WasmInstall()))
	v.Visit(v, "WasmUninstall", (t.WasmUninstall()))
}
func (t *ControlMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *ControlMessage) Write(w io.Writer) (err error) {
	if err := t.Header.Write(w); err != nil {
		return fmt.Errorf("encode Header: %w", err)
	}
	switch {
	case (t.Header.MessageType == ControlMessageType_L4LbKeepalive):
		if _, ok := t.union43_.(*union_45_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_45_t")
		}
		new_buf_56 := bytes.NewBuffer(nil)
		old_buf_56_w := w
		w = new_buf_56
		if err := t.union43_.(*union_45_t).L4LbKeepAlive.Write(w); err != nil {
			return fmt.Errorf("encode L4LbKeepAlive: %w", err)
		}
		if new_buf_56.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L4LbKeepAlive: expect %d bytes but got %d bytes", new_buf_56.Len(), int(t.Header.Len))
		}
		_, err = new_buf_56.WriteTo(old_buf_56_w)
		if err != nil {
			return err
		}
		w = old_buf_56_w
	case (t.Header.MessageType == ControlMessageType_L7LbKeepalive):
		if _, ok := t.union43_.(*union_46_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_46_t")
		}
		new_buf_57 := bytes.NewBuffer(nil)
		old_buf_57_w := w
		w = new_buf_57
		if err := t.union43_.(*union_46_t).L7LbKeepAlive.Write(w); err != nil {
			return fmt.Errorf("encode L7LbKeepAlive: %w", err)
		}
		if new_buf_57.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L7LbKeepAlive: expect %d bytes but got %d bytes", new_buf_57.Len(), int(t.Header.Len))
		}
		_, err = new_buf_57.WriteTo(old_buf_57_w)
		if err != nil {
			return err
		}
		w = old_buf_57_w
	case (t.Header.MessageType == ControlMessageType_L7LbHello):
		if _, ok := t.union43_.(*union_47_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_47_t")
		}
		new_buf_58 := bytes.NewBuffer(nil)
		old_buf_58_w := w
		w = new_buf_58
		if err := t.union43_.(*union_47_t).L7LbHello.Write(w); err != nil {
			return fmt.Errorf("encode L7LbHello: %w", err)
		}
		if new_buf_58.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L7LbHello: expect %d bytes but got %d bytes", new_buf_58.Len(), int(t.Header.Len))
		}
		_, err = new_buf_58.WriteTo(old_buf_58_w)
		if err != nil {
			return err
		}
		w = old_buf_58_w
	case (t.Header.MessageType == ControlMessageType_L7LbUpdate):
		if _, ok := t.union43_.(*union_48_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_48_t")
		}
		new_buf_59 := bytes.NewBuffer(nil)
		old_buf_59_w := w
		w = new_buf_59
		if err := t.union43_.(*union_48_t).L7LbUpdate.Write(w); err != nil {
			return fmt.Errorf("encode L7LbUpdate: %w", err)
		}
		if new_buf_59.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L7LbUpdate: expect %d bytes but got %d bytes", new_buf_59.Len(), int(t.Header.Len))
		}
		_, err = new_buf_59.WriteTo(old_buf_59_w)
		if err != nil {
			return err
		}
		w = old_buf_59_w
	case (t.Header.MessageType == ControlMessageType_L4LbHello):
		if _, ok := t.union43_.(*union_49_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_49_t")
		}
		new_buf_60 := bytes.NewBuffer(nil)
		old_buf_60_w := w
		w = new_buf_60
		if err := t.union43_.(*union_49_t).L4LbHello.Write(w); err != nil {
			return fmt.Errorf("encode L4LbHello: %w", err)
		}
		if new_buf_60.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L4LbHello: expect %d bytes but got %d bytes", new_buf_60.Len(), int(t.Header.Len))
		}
		_, err = new_buf_60.WriteTo(old_buf_60_w)
		if err != nil {
			return err
		}
		w = old_buf_60_w
	case (t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate):
		if _, ok := t.union43_.(*union_50_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_50_t")
		}
		new_buf_61 := bytes.NewBuffer(nil)
		old_buf_61_w := w
		w = new_buf_61
		if err := t.union43_.(*union_50_t).L4LbL7LbUpdate.Write(w); err != nil {
			return fmt.Errorf("encode L4LbL7LbUpdate: %w", err)
		}
		if new_buf_61.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L4LbL7LbUpdate: expect %d bytes but got %d bytes", new_buf_61.Len(), int(t.Header.Len))
		}
		_, err = new_buf_61.WriteTo(old_buf_61_w)
		if err != nil {
			return err
		}
		w = old_buf_61_w
	case (t.Header.MessageType == ControlMessageType_L4LbUpdate):
		if _, ok := t.union43_.(*union_51_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_51_t")
		}
		new_buf_62 := bytes.NewBuffer(nil)
		old_buf_62_w := w
		w = new_buf_62
		if err := t.union43_.(*union_51_t).L4LbUpdate.Write(w); err != nil {
			return fmt.Errorf("encode L4LbUpdate: %w", err)
		}
		if new_buf_62.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L4LbUpdate: expect %d bytes but got %d bytes", new_buf_62.Len(), int(t.Header.Len))
		}
		_, err = new_buf_62.WriteTo(old_buf_62_w)
		if err != nil {
			return err
		}
		w = old_buf_62_w
	case (t.Header.MessageType == ControlMessageType_KeyShare):
		if _, ok := t.union43_.(*union_52_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_52_t")
		}
		new_buf_63 := bytes.NewBuffer(nil)
		old_buf_63_w := w
		w = new_buf_63
		if err := t.union43_.(*union_52_t).KeyShare.Write(w); err != nil {
			return fmt.Errorf("encode KeyShare: %w", err)
		}
		if new_buf_63.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode KeyShare: expect %d bytes but got %d bytes", new_buf_63.Len(), int(t.Header.Len))
		}
		_, err = new_buf_63.WriteTo(old_buf_63_w)
		if err != nil {
			return err
		}
		w = old_buf_63_w
	case (t.Header.MessageType == ControlMessageType_WasmInstall):
		if _, ok := t.union43_.(*union_53_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_53_t")
		}
		new_buf_64 := bytes.NewBuffer(nil)
		old_buf_64_w := w
		w = new_buf_64
		if err := t.union43_.(*union_53_t).WasmInstall.Write(w); err != nil {
			return fmt.Errorf("encode WasmInstall: %w", err)
		}
		if new_buf_64.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode WasmInstall: expect %d bytes but got %d bytes", new_buf_64.Len(), int(t.Header.Len))
		}
		_, err = new_buf_64.WriteTo(old_buf_64_w)
		if err != nil {
			return err
		}
		w = old_buf_64_w
	case (t.Header.MessageType == ControlMessageType_WasmUninstall):
		if _, ok := t.union43_.(*union_54_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_54_t")
		}
		new_buf_65 := bytes.NewBuffer(nil)
		old_buf_65_w := w
		w = new_buf_65
		if err := t.union43_.(*union_54_t).WasmUninstall.Write(w); err != nil {
			return fmt.Errorf("encode WasmUninstall: %w", err)
		}
		if new_buf_65.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode WasmUninstall: expect %d bytes but got %d bytes", new_buf_65.Len(), int(t.Header.Len))
		}
		_, err = new_buf_65.WriteTo(old_buf_65_w)
		if err != nil {
			return err
		}
		w = old_buf_65_w
	default:
		if _, ok := t.union43_.(*union_55_t); !ok {
			return fmt.Errorf("encode t.union43_: union is not set to union_55_t")
		}
		len_Data := int(t.Header.Len)
		if len(t.union43_.(*union_55_t).Data) != len_Data {
			return fmt.Errorf("encode Data: expect %d bytes but got %d bytes", len_Data, len(t.union43_.(*union_55_t).Data))
		}
		if n, err := w.Write(t.union43_.(*union_55_t).Data); err != nil || n != len(t.union43_.(*union_55_t).Data) {
			return fmt.Errorf("encode Data: %w", err)
		}
	}
	return nil
}
func (t *ControlMessage) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *ControlMessage) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *ControlMessage) Read(r io.Reader) (err error) {
	if err := t.Header.Read(r); err != nil {
		return fmt.Errorf("read Header: %w", err)
	}
	switch {
	case (t.Header.MessageType == ControlMessageType_L4LbKeepalive):
		t.union43_ = &union_45_t{}
		sub_byte_len_L4LbKeepAlive := int64(t.Header.Len)
		sub_byte_r_L4LbKeepAlive := io.LimitReader(r, int64(sub_byte_len_L4LbKeepAlive))
		tmp_old_r_L4LbKeepAlive_66 := r
		r = sub_byte_r_L4LbKeepAlive
		if err := t.union43_.(*union_45_t).L4LbKeepAlive.Read(r); err != nil {
			return fmt.Errorf("read L4LbKeepAlive: %w", err)
		}
		if sub_byte_r_L4LbKeepAlive.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L4LbKeepAlive: expect %d bytes but got %d bytes", sub_byte_len_L4LbKeepAlive, sub_byte_len_L4LbKeepAlive-sub_byte_r_L4LbKeepAlive.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L4LbKeepAlive_66
	case (t.Header.MessageType == ControlMessageType_L7LbKeepalive):
		t.union43_ = &union_46_t{}
		sub_byte_len_L7LbKeepAlive := int64(t.Header.Len)
		sub_byte_r_L7LbKeepAlive := io.LimitReader(r, int64(sub_byte_len_L7LbKeepAlive))
		tmp_old_r_L7LbKeepAlive_67 := r
		r = sub_byte_r_L7LbKeepAlive
		if err := t.union43_.(*union_46_t).L7LbKeepAlive.Read(r); err != nil {
			return fmt.Errorf("read L7LbKeepAlive: %w", err)
		}
		if sub_byte_r_L7LbKeepAlive.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L7LbKeepAlive: expect %d bytes but got %d bytes", sub_byte_len_L7LbKeepAlive, sub_byte_len_L7LbKeepAlive-sub_byte_r_L7LbKeepAlive.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L7LbKeepAlive_67
	case (t.Header.MessageType == ControlMessageType_L7LbHello):
		t.union43_ = &union_47_t{}
		sub_byte_len_L7LbHello := int64(t.Header.Len)
		sub_byte_r_L7LbHello := io.LimitReader(r, int64(sub_byte_len_L7LbHello))
		tmp_old_r_L7LbHello_68 := r
		r = sub_byte_r_L7LbHello
		if err := t.union43_.(*union_47_t).L7LbHello.Read(r); err != nil {
			return fmt.Errorf("read L7LbHello: %w", err)
		}
		if sub_byte_r_L7LbHello.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L7LbHello: expect %d bytes but got %d bytes", sub_byte_len_L7LbHello, sub_byte_len_L7LbHello-sub_byte_r_L7LbHello.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L7LbHello_68
	case (t.Header.MessageType == ControlMessageType_L7LbUpdate):
		t.union43_ = &union_48_t{}
		sub_byte_len_L7LbUpdate := int64(t.Header.Len)
		sub_byte_r_L7LbUpdate := io.LimitReader(r, int64(sub_byte_len_L7LbUpdate))
		tmp_old_r_L7LbUpdate_69 := r
		r = sub_byte_r_L7LbUpdate
		if err := t.union43_.(*union_48_t).L7LbUpdate.Read(r); err != nil {
			return fmt.Errorf("read L7LbUpdate: %w", err)
		}
		if sub_byte_r_L7LbUpdate.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L7LbUpdate: expect %d bytes but got %d bytes", sub_byte_len_L7LbUpdate, sub_byte_len_L7LbUpdate-sub_byte_r_L7LbUpdate.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L7LbUpdate_69
	case (t.Header.MessageType == ControlMessageType_L4LbHello):
		t.union43_ = &union_49_t{}
		sub_byte_len_L4LbHello := int64(t.Header.Len)
		sub_byte_r_L4LbHello := io.LimitReader(r, int64(sub_byte_len_L4LbHello))
		tmp_old_r_L4LbHello_70 := r
		r = sub_byte_r_L4LbHello
		if err := t.union43_.(*union_49_t).L4LbHello.Read(r); err != nil {
			return fmt.Errorf("read L4LbHello: %w", err)
		}
		if sub_byte_r_L4LbHello.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L4LbHello: expect %d bytes but got %d bytes", sub_byte_len_L4LbHello, sub_byte_len_L4LbHello-sub_byte_r_L4LbHello.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L4LbHello_70
	case (t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate):
		t.union43_ = &union_50_t{}
		sub_byte_len_L4LbL7LbUpdate := int64(t.Header.Len)
		sub_byte_r_L4LbL7LbUpdate := io.LimitReader(r, int64(sub_byte_len_L4LbL7LbUpdate))
		tmp_old_r_L4LbL7LbUpdate_71 := r
		r = sub_byte_r_L4LbL7LbUpdate
		if err := t.union43_.(*union_50_t).L4LbL7LbUpdate.Read(r); err != nil {
			return fmt.Errorf("read L4LbL7LbUpdate: %w", err)
		}
		if sub_byte_r_L4LbL7LbUpdate.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L4LbL7LbUpdate: expect %d bytes but got %d bytes", sub_byte_len_L4LbL7LbUpdate, sub_byte_len_L4LbL7LbUpdate-sub_byte_r_L4LbL7LbUpdate.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L4LbL7LbUpdate_71
	case (t.Header.MessageType == ControlMessageType_L4LbUpdate):
		t.union43_ = &union_51_t{}
		sub_byte_len_L4LbUpdate := int64(t.Header.Len)
		sub_byte_r_L4LbUpdate := io.LimitReader(r, int64(sub_byte_len_L4LbUpdate))
		tmp_old_r_L4LbUpdate_72 := r
		r = sub_byte_r_L4LbUpdate
		if err := t.union43_.(*union_51_t).L4LbUpdate.Read(r); err != nil {
			return fmt.Errorf("read L4LbUpdate: %w", err)
		}
		if sub_byte_r_L4LbUpdate.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L4LbUpdate: expect %d bytes but got %d bytes", sub_byte_len_L4LbUpdate, sub_byte_len_L4LbUpdate-sub_byte_r_L4LbUpdate.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L4LbUpdate_72
	case (t.Header.MessageType == ControlMessageType_KeyShare):
		t.union43_ = &union_52_t{}
		sub_byte_len_KeyShare := int64(t.Header.Len)
		sub_byte_r_KeyShare := io.LimitReader(r, int64(sub_byte_len_KeyShare))
		tmp_old_r_KeyShare_73 := r
		r = sub_byte_r_KeyShare
		if err := t.union43_.(*union_52_t).KeyShare.Read(r); err != nil {
			return fmt.Errorf("read KeyShare: %w", err)
		}
		if sub_byte_r_KeyShare.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read KeyShare: expect %d bytes but got %d bytes", sub_byte_len_KeyShare, sub_byte_len_KeyShare-sub_byte_r_KeyShare.(*io.LimitedReader).N)
		}
		r = tmp_old_r_KeyShare_73
	case (t.Header.MessageType == ControlMessageType_WasmInstall):
		t.union43_ = &union_53_t{}
		sub_byte_len_WasmInstall := int64(t.Header.Len)
		sub_byte_r_WasmInstall := io.LimitReader(r, int64(sub_byte_len_WasmInstall))
		tmp_old_r_WasmInstall_74 := r
		r = sub_byte_r_WasmInstall
		if err := t.union43_.(*union_53_t).WasmInstall.Read(r); err != nil {
			return fmt.Errorf("read WasmInstall: %w", err)
		}
		if sub_byte_r_WasmInstall.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read WasmInstall: expect %d bytes but got %d bytes", sub_byte_len_WasmInstall, sub_byte_len_WasmInstall-sub_byte_r_WasmInstall.(*io.LimitedReader).N)
		}
		r = tmp_old_r_WasmInstall_74
	case (t.Header.MessageType == ControlMessageType_WasmUninstall):
		t.union43_ = &union_54_t{}
		sub_byte_len_WasmUninstall := int64(t.Header.Len)
		sub_byte_r_WasmUninstall := io.LimitReader(r, int64(sub_byte_len_WasmUninstall))
		tmp_old_r_WasmUninstall_75 := r
		r = sub_byte_r_WasmUninstall
		if err := t.union43_.(*union_54_t).WasmUninstall.Read(r); err != nil {
			return fmt.Errorf("read WasmUninstall: %w", err)
		}
		if sub_byte_r_WasmUninstall.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read WasmUninstall: expect %d bytes but got %d bytes", sub_byte_len_WasmUninstall, sub_byte_len_WasmUninstall-sub_byte_r_WasmUninstall.(*io.LimitedReader).N)
		}
		r = tmp_old_r_WasmUninstall_75
	default:
		t.union43_ = &union_55_t{}
		len_Data := int(t.Header.Len)
		if len_Data != 0 {
			tmpData := make([]byte, len_Data)
			n_Data, err := io.ReadFull(r, tmpData[:])
			if err != nil {
				return fmt.Errorf("read Data: expect %d bytes but read %d bytes: %w", len_Data, n_Data, err)
			}
			t.union43_.(*union_55_t).Data = tmpData[:]
		} else {
			t.union43_.(*union_55_t).Data = nil
		}
	}
	return nil
}

func (t *ControlMessage) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *ControlMessage) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode ControlMessage: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
