// Code generated by json2go. DO NOT EDIT.
package protocol

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"reflect"
)

type ControlMessageType uint8

const (
	ControlMessageType_Keepalive      ControlMessageType = 0
	ControlMessageType_L7LbHello      ControlMessageType = 1
	ControlMessageType_L7LbUpdate     ControlMessageType = 2
	ControlMessageType_L4LbL7LbUpdate ControlMessageType = 3
	ControlMessageType_L4LbHello      ControlMessageType = 4
	ControlMessageType_L4LbUpdate     ControlMessageType = 5
	ControlMessageType_KeyShare       ControlMessageType = 6
	ControlMessageType_WasmInstall    ControlMessageType = 7
	ControlMessageType_WasmUninstall  ControlMessageType = 8
)

func (t ControlMessageType) String() string {
	switch t {
	case ControlMessageType_Keepalive:
		return "Keepalive"
	case ControlMessageType_L7LbHello:
		return "L7LbHello"
	case ControlMessageType_L7LbUpdate:
		return "L7LbUpdate"
	case ControlMessageType_L4LbL7LbUpdate:
		return "L4LbL7LbUpdate"
	case ControlMessageType_L4LbHello:
		return "L4LbHello"
	case ControlMessageType_L4LbUpdate:
		return "L4LbUpdate"
	case ControlMessageType_KeyShare:
		return "KeyShare"
	case ControlMessageType_WasmInstall:
		return "WasmInstall"
	case ControlMessageType_WasmUninstall:
		return "WasmUninstall"
	}
	return fmt.Sprintf("ControlMessageType(%d)", t)
}

type KeyType uint8

const (
	KeyType_Quiclb KeyType = 0
)

func (t KeyType) String() string {
	switch t {
	case KeyType_Quiclb:
		return "Quiclb"
	}
	return fmt.Sprintf("KeyType(%d)", t)
}

type ControlMessageHeader struct {
	Version     uint8
	Len         uint16
	MessageType ControlMessageType
}
type VisitorJJRQX interface {
	Visit(v VisitorJJRQX, name string, field any)
}
type VisitorJJRQXFunc func(v VisitorJJRQX, name string, field any)

func (f VisitorJJRQXFunc) Visit(v VisitorJJRQX, name string, field any) {
	f(v, name, field)
}

type VisitorJJRQXVisitable interface {
	Visit(v VisitorJJRQX)
}

func VisitorJJRQXToMap(v any) interface{} {
	if v == nil {
		return nil
	}
	if inter, ok := v.(VisitorJJRQXVisitable); ok {
		if p := reflect.ValueOf(inter); p.Kind() == reflect.Pointer && p.IsNil() {
			return nil
		}
		m := map[string]interface{}{}
		inter.Visit(VisitorJJRQXFunc(func(v VisitorJJRQX, name string, field any) {
			m[name] = VisitorJJRQXToMap(field)
		}))
		return m
	}
	if tf := reflect.TypeOf(v); (tf.Kind() == reflect.Slice || tf.Kind() == reflect.Array) && !(func() bool { k := tf.Elem().Kind().String(); return k[:3] == "int" || k[:3] == "uin" || k[:3] == "flo" })() {
		m := []interface{}{}
		vf := reflect.ValueOf(v)
		for i := 0; i < vf.Len(); i++ {
			index := vf.Index(i)
			if index.Kind() == reflect.Struct && index.CanAddr() {
				index = index.Addr()
			}
			m = append(m, VisitorJJRQXToMap(index.Interface()))
		}
		return m
	}
	if tf := reflect.TypeOf(v); tf.Kind() == reflect.Pointer {
		val := reflect.ValueOf(v)
		if val.IsNil() {
			return nil
		}
		return VisitorJJRQXToMap(val.Elem().Interface())
	}
	return v
}

type L7Lbinfo struct {
	ServerId   uint32
	Address    [4]uint8
	MacAddress [6]uint8
	PortLen    uint8
	Port       []uint16
}
type L7Lbupdate struct {
	ServerId uint32
}
type KeepAliveInfo struct {
	NextPeriod uint64
}
type L4Lbinfo struct {
	ServerId       uint32
	VirtualAddress [4]uint8
	Address        [4]uint8
	MacAddress     [6]uint8
}
type L4Lbupdate struct {
	VirtualAddress [4]uint8
}
type KeyShareInfo struct {
	Type KeyType
	Len  uint16
	Key  []uint8
}
type WasmInstallInfo struct {
	Id         uint32
	MethodLen  uint8
	Method     []uint8
	PathLen    uint16
	Path       []uint8
	BinarySize uint64
}
type WasmUninstallInfo struct {
	Id uint32
}
type L4Lbl7Lbupdate struct {
	Len  uint8
	Info []L7Lbinfo
}
type union17_ControlMessage interface {
	isunion16_()
}
type union_18_t struct {
	KeepAlive KeepAliveInfo
}
type union_19_t struct {
	L7LbHello L7Lbinfo
}
type union_20_t struct {
	L7LbUpdate L7Lbupdate
}
type union_21_t struct {
	L4LbHello L4Lbinfo
}
type union_22_t struct {
	L4LbL7LbUpdate L4Lbl7Lbupdate
}
type union_23_t struct {
	L4LbUpdate L4Lbupdate
}
type union_24_t struct {
	KeyShare KeyShareInfo
}
type union_25_t struct {
	WasmInstall WasmInstallInfo
}
type union_26_t struct {
	WasmUninstall WasmUninstallInfo
}
type union_27_t struct {
	Data []uint8
}
type ControlMessage struct {
	Header   ControlMessageHeader
	union16_ union17_ControlMessage
}

func (t *ControlMessageHeader) Visit(v VisitorJJRQX) {
	v.Visit(v, "Version", &t.Version)
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "MessageType", &t.MessageType)
}
func (t *ControlMessageHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *ControlMessageHeader) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Version)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Version: %w", err)
	}
	tmp1 := [2]byte{}
	binary.BigEndian.PutUint16(tmp1[:], uint16(t.Len))
	if n, err := w.Write(tmp1[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.MessageType)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.MessageType: %w", err)
	}
	return nil
}
func (t *ControlMessageHeader) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *ControlMessageHeader) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *ControlMessageHeader) Read(r io.Reader) (err error) {
	tmpVersion := [1]byte{}
	n_Version, err := io.ReadFull(r, tmpVersion[:])
	if err != nil {
		return fmt.Errorf("read Version: expect 1 byte but read %d bytes: %w", n_Version, err)
	}
	t.Version = uint8(tmpVersion[0])
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.BigEndian.Uint16(tmpLen[:]))
	tmpMessageType := [1]byte{}
	n_MessageType, err := io.ReadFull(r, tmpMessageType[:])
	if err != nil {
		return fmt.Errorf("read MessageType: expect 1 byte but read %d bytes: %w", n_MessageType, err)
	}
	t.MessageType = ControlMessageType(tmpMessageType[0])
	return nil
}

func (t *ControlMessageHeader) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *ControlMessageHeader) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode ControlMessageHeader: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L7Lbinfo) SetPort(v []uint16) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.PortLen = uint8(len(v))
	t.Port = v
	return true
}
func (t *L7Lbinfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "ServerId", &t.ServerId)
	v.Visit(v, "Address", &t.Address)
	v.Visit(v, "MacAddress", &t.MacAddress)
	v.Visit(v, "PortLen", &t.PortLen)
	v.Visit(v, "Port", &t.Port)
}
func (t *L7Lbinfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L7Lbinfo) Write(w io.Writer) (err error) {
	tmp2 := [4]byte{}
	binary.BigEndian.PutUint32(tmp2[:], uint32(t.ServerId))
	if n, err := w.Write(tmp2[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.ServerId: %w", err)
	}
	if n, err := w.Write(t.Address[:]); err != nil || n != len(t.Address) {
		return fmt.Errorf("encode Address: %w", err)
	}
	if n, err := w.Write(t.MacAddress[:]); err != nil || n != len(t.MacAddress) {
		return fmt.Errorf("encode MacAddress: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.PortLen)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.PortLen: %w", err)
	}
	len_Port := int(t.PortLen)
	if len(t.Port) != len_Port {
		return fmt.Errorf("encode Port: expect %d but got %d for length", len_Port, len(t.Port))
	}
	for _, v := range t.Port {
		tmp3 := [2]byte{}
		binary.BigEndian.PutUint16(tmp3[:], uint16(v))
		if n, err := w.Write(tmp3[:]); err != nil || n != 2 {
			return fmt.Errorf("encode v: %w", err)
		}
	}
	return nil
}
func (t *L7Lbinfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 15))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L7Lbinfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L7Lbinfo) Read(r io.Reader) (err error) {
	tmpServerId := [4]byte{}
	n_ServerId, err := io.ReadFull(r, tmpServerId[:])
	if err != nil {
		return fmt.Errorf("read ServerId: expect 4 bytes but read %d bytes: %w", n_ServerId, err)
	}
	t.ServerId = uint32(binary.BigEndian.Uint32(tmpServerId[:]))
	n_Address, err := io.ReadFull(r, t.Address[:])
	if err != nil {
		return fmt.Errorf("read Address: expect %d bytes but read %d bytes: %w", 4, n_Address, err)
	}
	n_MacAddress, err := io.ReadFull(r, t.MacAddress[:])
	if err != nil {
		return fmt.Errorf("read MacAddress: expect %d bytes but read %d bytes: %w", 6, n_MacAddress, err)
	}
	tmpPortLen := [1]byte{}
	n_PortLen, err := io.ReadFull(r, tmpPortLen[:])
	if err != nil {
		return fmt.Errorf("read PortLen: expect 1 byte but read %d bytes: %w", n_PortLen, err)
	}
	t.PortLen = uint8(tmpPortLen[0])
	len_Port := int(t.PortLen)
	for i_4 := 0; i_4 < len_Port; i_4++ {
		var tmp5_ uint16
		tmpPort := [2]byte{}
		n_Port, err := io.ReadFull(r, tmpPort[:])
		if err != nil {
			return fmt.Errorf("read Port: expect 2 bytes but read %d bytes: %w", n_Port, err)
		}
		tmp5_ = uint16(binary.BigEndian.Uint16(tmpPort[:]))
		t.Port = append(t.Port, tmp5_)
	}
	return nil
}

func (t *L7Lbinfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L7Lbinfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L7Lbinfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L7Lbupdate) Visit(v VisitorJJRQX) {
	v.Visit(v, "ServerId", &t.ServerId)
}
func (t *L7Lbupdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L7Lbupdate) Write(w io.Writer) (err error) {
	tmp6 := [4]byte{}
	binary.BigEndian.PutUint32(tmp6[:], uint32(t.ServerId))
	if n, err := w.Write(tmp6[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.ServerId: %w", err)
	}
	return nil
}
func (t *L7Lbupdate) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L7Lbupdate) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L7Lbupdate) Read(r io.Reader) (err error) {
	tmpServerId := [4]byte{}
	n_ServerId, err := io.ReadFull(r, tmpServerId[:])
	if err != nil {
		return fmt.Errorf("read ServerId: expect 4 bytes but read %d bytes: %w", n_ServerId, err)
	}
	t.ServerId = uint32(binary.BigEndian.Uint32(tmpServerId[:]))
	return nil
}

func (t *L7Lbupdate) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L7Lbupdate) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L7Lbupdate: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *KeepAliveInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "NextPeriod", &t.NextPeriod)
}
func (t *KeepAliveInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *KeepAliveInfo) Write(w io.Writer) (err error) {
	tmp7 := [8]byte{}
	binary.BigEndian.PutUint64(tmp7[:], uint64(t.NextPeriod))
	if n, err := w.Write(tmp7[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.NextPeriod: %w", err)
	}
	return nil
}
func (t *KeepAliveInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 8))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *KeepAliveInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *KeepAliveInfo) Read(r io.Reader) (err error) {
	tmpNextPeriod := [8]byte{}
	n_NextPeriod, err := io.ReadFull(r, tmpNextPeriod[:])
	if err != nil {
		return fmt.Errorf("read NextPeriod: expect 8 bytes but read %d bytes: %w", n_NextPeriod, err)
	}
	t.NextPeriod = uint64(binary.BigEndian.Uint64(tmpNextPeriod[:]))
	return nil
}

func (t *KeepAliveInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *KeepAliveInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode KeepAliveInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L4Lbinfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "ServerId", &t.ServerId)
	v.Visit(v, "VirtualAddress", &t.VirtualAddress)
	v.Visit(v, "Address", &t.Address)
	v.Visit(v, "MacAddress", &t.MacAddress)
}
func (t *L4Lbinfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L4Lbinfo) Write(w io.Writer) (err error) {
	tmp8 := [4]byte{}
	binary.BigEndian.PutUint32(tmp8[:], uint32(t.ServerId))
	if n, err := w.Write(tmp8[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.ServerId: %w", err)
	}
	if n, err := w.Write(t.VirtualAddress[:]); err != nil || n != len(t.VirtualAddress) {
		return fmt.Errorf("encode VirtualAddress: %w", err)
	}
	if n, err := w.Write(t.Address[:]); err != nil || n != len(t.Address) {
		return fmt.Errorf("encode Address: %w", err)
	}
	if n, err := w.Write(t.MacAddress[:]); err != nil || n != len(t.MacAddress) {
		return fmt.Errorf("encode MacAddress: %w", err)
	}
	return nil
}
func (t *L4Lbinfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 18))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L4Lbinfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L4Lbinfo) Read(r io.Reader) (err error) {
	tmpServerId := [4]byte{}
	n_ServerId, err := io.ReadFull(r, tmpServerId[:])
	if err != nil {
		return fmt.Errorf("read ServerId: expect 4 bytes but read %d bytes: %w", n_ServerId, err)
	}
	t.ServerId = uint32(binary.BigEndian.Uint32(tmpServerId[:]))
	n_VirtualAddress, err := io.ReadFull(r, t.VirtualAddress[:])
	if err != nil {
		return fmt.Errorf("read VirtualAddress: expect %d bytes but read %d bytes: %w", 4, n_VirtualAddress, err)
	}
	n_Address, err := io.ReadFull(r, t.Address[:])
	if err != nil {
		return fmt.Errorf("read Address: expect %d bytes but read %d bytes: %w", 4, n_Address, err)
	}
	n_MacAddress, err := io.ReadFull(r, t.MacAddress[:])
	if err != nil {
		return fmt.Errorf("read MacAddress: expect %d bytes but read %d bytes: %w", 6, n_MacAddress, err)
	}
	return nil
}

func (t *L4Lbinfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L4Lbinfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L4Lbinfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L4Lbupdate) Visit(v VisitorJJRQX) {
	v.Visit(v, "VirtualAddress", &t.VirtualAddress)
}
func (t *L4Lbupdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L4Lbupdate) Write(w io.Writer) (err error) {
	if n, err := w.Write(t.VirtualAddress[:]); err != nil || n != len(t.VirtualAddress) {
		return fmt.Errorf("encode VirtualAddress: %w", err)
	}
	return nil
}
func (t *L4Lbupdate) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L4Lbupdate) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L4Lbupdate) Read(r io.Reader) (err error) {
	n_VirtualAddress, err := io.ReadFull(r, t.VirtualAddress[:])
	if err != nil {
		return fmt.Errorf("read VirtualAddress: expect %d bytes but read %d bytes: %w", 4, n_VirtualAddress, err)
	}
	return nil
}

func (t *L4Lbupdate) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L4Lbupdate) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L4Lbupdate: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *KeyShareInfo) SetKey(v []uint8) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.Len = uint16(len(v))
	t.Key = v
	return true
}
func (t *KeyShareInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "Type", &t.Type)
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Key", &t.Key)
}
func (t *KeyShareInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *KeyShareInfo) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Type)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Type: %w", err)
	}
	tmp9 := [2]byte{}
	binary.BigEndian.PutUint16(tmp9[:], uint16(t.Len))
	if n, err := w.Write(tmp9[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Key := int(t.Len)
	if len(t.Key) != len_Key {
		return fmt.Errorf("encode Key: expect %d bytes but got %d bytes", len_Key, len(t.Key))
	}
	if n, err := w.Write(t.Key); err != nil || n != len(t.Key) {
		return fmt.Errorf("encode Key: %w", err)
	}
	return nil
}
func (t *KeyShareInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 3))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *KeyShareInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *KeyShareInfo) Read(r io.Reader) (err error) {
	tmpType := [1]byte{}
	n_Type, err := io.ReadFull(r, tmpType[:])
	if err != nil {
		return fmt.Errorf("read Type: expect 1 byte but read %d bytes: %w", n_Type, err)
	}
	t.Type = KeyType(tmpType[0])
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.BigEndian.Uint16(tmpLen[:]))
	len_Key := int(t.Len)
	if len_Key != 0 {
		tmpKey := make([]byte, len_Key)
		n_Key, err := io.ReadFull(r, tmpKey[:])
		if err != nil {
			return fmt.Errorf("read Key: expect %d bytes but read %d bytes: %w", len_Key, n_Key, err)
		}
		t.Key = tmpKey[:]
	} else {
		t.Key = nil
	}
	return nil
}

func (t *KeyShareInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *KeyShareInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode KeyShareInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *WasmInstallInfo) SetMethod(v []uint8) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.MethodLen = uint8(len(v))
	t.Method = v
	return true
}
func (t *WasmInstallInfo) SetPath(v []uint8) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.PathLen = uint16(len(v))
	t.Path = v
	return true
}
func (t *WasmInstallInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "Id", &t.Id)
	v.Visit(v, "MethodLen", &t.MethodLen)
	v.Visit(v, "Method", &t.Method)
	v.Visit(v, "PathLen", &t.PathLen)
	v.Visit(v, "Path", &t.Path)
	v.Visit(v, "BinarySize", &t.BinarySize)
}
func (t *WasmInstallInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *WasmInstallInfo) Write(w io.Writer) (err error) {
	tmp10 := [4]byte{}
	binary.BigEndian.PutUint32(tmp10[:], uint32(t.Id))
	if n, err := w.Write(tmp10[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.Id: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.MethodLen)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.MethodLen: %w", err)
	}
	len_Method := int(t.MethodLen)
	if len(t.Method) != len_Method {
		return fmt.Errorf("encode Method: expect %d bytes but got %d bytes", len_Method, len(t.Method))
	}
	if n, err := w.Write(t.Method); err != nil || n != len(t.Method) {
		return fmt.Errorf("encode Method: %w", err)
	}
	tmp11 := [2]byte{}
	binary.BigEndian.PutUint16(tmp11[:], uint16(t.PathLen))
	if n, err := w.Write(tmp11[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.PathLen: %w", err)
	}
	len_Path := int(t.PathLen)
	if len(t.Path) != len_Path {
		return fmt.Errorf("encode Path: expect %d bytes but got %d bytes", len_Path, len(t.Path))
	}
	if n, err := w.Write(t.Path); err != nil || n != len(t.Path) {
		return fmt.Errorf("encode Path: %w", err)
	}
	tmp12 := [8]byte{}
	binary.BigEndian.PutUint64(tmp12[:], uint64(t.BinarySize))
	if n, err := w.Write(tmp12[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.BinarySize: %w", err)
	}
	return nil
}
func (t *WasmInstallInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 5))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *WasmInstallInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *WasmInstallInfo) Read(r io.Reader) (err error) {
	tmpId := [4]byte{}
	n_Id, err := io.ReadFull(r, tmpId[:])
	if err != nil {
		return fmt.Errorf("read Id: expect 4 bytes but read %d bytes: %w", n_Id, err)
	}
	t.Id = uint32(binary.BigEndian.Uint32(tmpId[:]))
	tmpMethodLen := [1]byte{}
	n_MethodLen, err := io.ReadFull(r, tmpMethodLen[:])
	if err != nil {
		return fmt.Errorf("read MethodLen: expect 1 byte but read %d bytes: %w", n_MethodLen, err)
	}
	t.MethodLen = uint8(tmpMethodLen[0])
	len_Method := int(t.MethodLen)
	if len_Method != 0 {
		tmpMethod := make([]byte, len_Method)
		n_Method, err := io.ReadFull(r, tmpMethod[:])
		if err != nil {
			return fmt.Errorf("read Method: expect %d bytes but read %d bytes: %w", len_Method, n_Method, err)
		}
		t.Method = tmpMethod[:]
	} else {
		t.Method = nil
	}
	tmpPathLen := [2]byte{}
	n_PathLen, err := io.ReadFull(r, tmpPathLen[:])
	if err != nil {
		return fmt.Errorf("read PathLen: expect 2 bytes but read %d bytes: %w", n_PathLen, err)
	}
	t.PathLen = uint16(binary.BigEndian.Uint16(tmpPathLen[:]))
	len_Path := int(t.PathLen)
	if len_Path != 0 {
		tmpPath := make([]byte, len_Path)
		n_Path, err := io.ReadFull(r, tmpPath[:])
		if err != nil {
			return fmt.Errorf("read Path: expect %d bytes but read %d bytes: %w", len_Path, n_Path, err)
		}
		t.Path = tmpPath[:]
	} else {
		t.Path = nil
	}
	tmpBinarySize := [8]byte{}
	n_BinarySize, err := io.ReadFull(r, tmpBinarySize[:])
	if err != nil {
		return fmt.Errorf("read BinarySize: expect 8 bytes but read %d bytes: %w", n_BinarySize, err)
	}
	t.BinarySize = uint64(binary.BigEndian.Uint64(tmpBinarySize[:]))
	return nil
}

func (t *WasmInstallInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *WasmInstallInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode WasmInstallInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *WasmUninstallInfo) Visit(v VisitorJJRQX) {
	v.Visit(v, "Id", &t.Id)
}
func (t *WasmUninstallInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *WasmUninstallInfo) Write(w io.Writer) (err error) {
	tmp13 := [4]byte{}
	binary.BigEndian.PutUint32(tmp13[:], uint32(t.Id))
	if n, err := w.Write(tmp13[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.Id: %w", err)
	}
	return nil
}
func (t *WasmUninstallInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *WasmUninstallInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *WasmUninstallInfo) Read(r io.Reader) (err error) {
	tmpId := [4]byte{}
	n_Id, err := io.ReadFull(r, tmpId[:])
	if err != nil {
		return fmt.Errorf("read Id: expect 4 bytes but read %d bytes: %w", n_Id, err)
	}
	t.Id = uint32(binary.BigEndian.Uint32(tmpId[:]))
	return nil
}

func (t *WasmUninstallInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *WasmUninstallInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode WasmUninstallInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *L4Lbl7Lbupdate) SetInfo(v []L7Lbinfo) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.Len = uint8(len(v))
	t.Info = v
	return true
}
func (t *L4Lbl7Lbupdate) Visit(v VisitorJJRQX) {
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Info", &t.Info)
}
func (t *L4Lbl7Lbupdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *L4Lbl7Lbupdate) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Len)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Info := int(t.Len)
	if len(t.Info) != len_Info {
		return fmt.Errorf("encode Info: expect %d but got %d for length", len_Info, len(t.Info))
	}
	for _, v := range t.Info {
		if err := v.Write(w); err != nil {
			return fmt.Errorf("encode Info: %w", err)
		}
	}
	return nil
}
func (t *L4Lbl7Lbupdate) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 1))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *L4Lbl7Lbupdate) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *L4Lbl7Lbupdate) Read(r io.Reader) (err error) {
	tmpLen := [1]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 1 byte but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint8(tmpLen[0])
	len_Info := int(t.Len)
	for i_14 := 0; i_14 < len_Info; i_14++ {
		var tmp15_ L7Lbinfo
		if err := tmp15_.Read(r); err != nil {
			return fmt.Errorf("read Info: %w", err)
		}
		t.Info = append(t.Info, tmp15_)
	}
	return nil
}

func (t *L4Lbl7Lbupdate) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *L4Lbl7Lbupdate) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode L4Lbl7Lbupdate: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *union_18_t) isunion16_() {}
func (t *union_19_t) isunion16_() {}
func (t *union_20_t) isunion16_() {}
func (t *union_21_t) isunion16_() {}
func (t *union_22_t) isunion16_() {}
func (t *union_23_t) isunion16_() {}
func (t *union_24_t) isunion16_() {}
func (t *union_25_t) isunion16_() {}
func (t *union_26_t) isunion16_() {}
func (t *union_27_t) isunion16_() {}
func (t *ControlMessage) Data() *[]uint8 {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmUninstall {
		return nil
	} else if true {
		if _, ok := t.union16_.(*union_27_t); !ok {
			return nil // not set
		}
		tmp := []uint8(t.union16_.(*union_27_t).Data)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetData(v []uint8) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmUninstall {
		return false
	} else if true {
		if _, ok := t.union16_.(*union_27_t); !ok {
			t.union16_ = &union_27_t{}
		}
		t.union16_.(*union_27_t).Data = []uint8(v)
		return true
	}
	return false
}
func (t *ControlMessage) KeepAlive() *KeepAliveInfo {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		if _, ok := t.union16_.(*union_18_t); !ok {
			return nil // not set
		}
		tmp := KeepAliveInfo(t.union16_.(*union_18_t).KeepAlive)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetKeepAlive(v KeepAliveInfo) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		if _, ok := t.union16_.(*union_18_t); !ok {
			t.union16_ = &union_18_t{}
		}
		t.union16_.(*union_18_t).KeepAlive = KeepAliveInfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) KeyShare() *KeyShareInfo {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		if _, ok := t.union16_.(*union_24_t); !ok {
			return nil // not set
		}
		tmp := KeyShareInfo(t.union16_.(*union_24_t).KeyShare)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetKeyShare(v KeyShareInfo) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		if _, ok := t.union16_.(*union_24_t); !ok {
			t.union16_ = &union_24_t{}
		}
		t.union16_.(*union_24_t).KeyShare = KeyShareInfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) L4LbHello() *L4Lbinfo {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		if _, ok := t.union16_.(*union_21_t); !ok {
			return nil // not set
		}
		tmp := L4Lbinfo(t.union16_.(*union_21_t).L4LbHello)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL4LbHello(v L4Lbinfo) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		if _, ok := t.union16_.(*union_21_t); !ok {
			t.union16_ = &union_21_t{}
		}
		t.union16_.(*union_21_t).L4LbHello = L4Lbinfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) L4LbL7LbUpdate() *L4Lbl7Lbupdate {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		if _, ok := t.union16_.(*union_22_t); !ok {
			return nil // not set
		}
		tmp := L4Lbl7Lbupdate(t.union16_.(*union_22_t).L4LbL7LbUpdate)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL4LbL7LbUpdate(v L4Lbl7Lbupdate) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		if _, ok := t.union16_.(*union_22_t); !ok {
			t.union16_ = &union_22_t{}
		}
		t.union16_.(*union_22_t).L4LbL7LbUpdate = L4Lbl7Lbupdate(v)
		return true
	}
	return false
}
func (t *ControlMessage) L4LbUpdate() *L4Lbupdate {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		if _, ok := t.union16_.(*union_23_t); !ok {
			return nil // not set
		}
		tmp := L4Lbupdate(t.union16_.(*union_23_t).L4LbUpdate)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL4LbUpdate(v L4Lbupdate) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		if _, ok := t.union16_.(*union_23_t); !ok {
			t.union16_ = &union_23_t{}
		}
		t.union16_.(*union_23_t).L4LbUpdate = L4Lbupdate(v)
		return true
	}
	return false
}
func (t *ControlMessage) L7LbHello() *L7Lbinfo {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		if _, ok := t.union16_.(*union_19_t); !ok {
			return nil // not set
		}
		tmp := L7Lbinfo(t.union16_.(*union_19_t).L7LbHello)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL7LbHello(v L7Lbinfo) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		if _, ok := t.union16_.(*union_19_t); !ok {
			t.union16_ = &union_19_t{}
		}
		t.union16_.(*union_19_t).L7LbHello = L7Lbinfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) L7LbUpdate() *L7Lbupdate {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		if _, ok := t.union16_.(*union_20_t); !ok {
			return nil // not set
		}
		tmp := L7Lbupdate(t.union16_.(*union_20_t).L7LbUpdate)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetL7LbUpdate(v L7Lbupdate) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		if _, ok := t.union16_.(*union_20_t); !ok {
			t.union16_ = &union_20_t{}
		}
		t.union16_.(*union_20_t).L7LbUpdate = L7Lbupdate(v)
		return true
	}
	return false
}
func (t *ControlMessage) WasmInstall() *WasmInstallInfo {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		if _, ok := t.union16_.(*union_25_t); !ok {
			return nil // not set
		}
		tmp := WasmInstallInfo(t.union16_.(*union_25_t).WasmInstall)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetWasmInstall(v WasmInstallInfo) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		if _, ok := t.union16_.(*union_25_t); !ok {
			t.union16_ = &union_25_t{}
		}
		t.union16_.(*union_25_t).WasmInstall = WasmInstallInfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) WasmUninstall() *WasmUninstallInfo {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return nil
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		return nil
	} else if t.Header.MessageType == ControlMessageType_WasmUninstall {
		if _, ok := t.union16_.(*union_26_t); !ok {
			return nil // not set
		}
		tmp := WasmUninstallInfo(t.union16_.(*union_26_t).WasmUninstall)
		return &tmp
	}
	return nil
}
func (t *ControlMessage) SetWasmUninstall(v WasmUninstallInfo) bool {
	if t.Header.MessageType == ControlMessageType_Keepalive {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbHello {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_L4LbUpdate {
		return false
	} else if t.Header.MessageType == ControlMessageType_KeyShare {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmInstall {
		return false
	} else if t.Header.MessageType == ControlMessageType_WasmUninstall {
		if _, ok := t.union16_.(*union_26_t); !ok {
			t.union16_ = &union_26_t{}
		}
		t.union16_.(*union_26_t).WasmUninstall = WasmUninstallInfo(v)
		return true
	}
	return false
}
func (t *ControlMessage) Visit(v VisitorJJRQX) {
	v.Visit(v, "Header", &t.Header)
	v.Visit(v, "Data", (t.Data()))
	v.Visit(v, "KeepAlive", (t.KeepAlive()))
	v.Visit(v, "KeyShare", (t.KeyShare()))
	v.Visit(v, "L4LbHello", (t.L4LbHello()))
	v.Visit(v, "L4LbL7LbUpdate", (t.L4LbL7LbUpdate()))
	v.Visit(v, "L4LbUpdate", (t.L4LbUpdate()))
	v.Visit(v, "L7LbHello", (t.L7LbHello()))
	v.Visit(v, "L7LbUpdate", (t.L7LbUpdate()))
	v.Visit(v, "WasmInstall", (t.WasmInstall()))
	v.Visit(v, "WasmUninstall", (t.WasmUninstall()))
}
func (t *ControlMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJJRQXToMap(t))
}
func (t *ControlMessage) Write(w io.Writer) (err error) {
	if err := t.Header.Write(w); err != nil {
		return fmt.Errorf("encode Header: %w", err)
	}
	switch {
	case (t.Header.MessageType == ControlMessageType_Keepalive):
		if _, ok := t.union16_.(*union_18_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_18_t")
		}
		new_buf_28 := bytes.NewBuffer(nil)
		old_buf_28_w := w
		w = new_buf_28
		if err := t.union16_.(*union_18_t).KeepAlive.Write(w); err != nil {
			return fmt.Errorf("encode KeepAlive: %w", err)
		}
		if new_buf_28.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode KeepAlive: expect %d bytes but got %d bytes", new_buf_28.Len(), int(t.Header.Len))
		}
		_, err = new_buf_28.WriteTo(old_buf_28_w)
		if err != nil {
			return err
		}
		w = old_buf_28_w
	case (t.Header.MessageType == ControlMessageType_L7LbHello):
		if _, ok := t.union16_.(*union_19_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_19_t")
		}
		new_buf_29 := bytes.NewBuffer(nil)
		old_buf_29_w := w
		w = new_buf_29
		if err := t.union16_.(*union_19_t).L7LbHello.Write(w); err != nil {
			return fmt.Errorf("encode L7LbHello: %w", err)
		}
		if new_buf_29.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L7LbHello: expect %d bytes but got %d bytes", new_buf_29.Len(), int(t.Header.Len))
		}
		_, err = new_buf_29.WriteTo(old_buf_29_w)
		if err != nil {
			return err
		}
		w = old_buf_29_w
	case (t.Header.MessageType == ControlMessageType_L7LbUpdate):
		if _, ok := t.union16_.(*union_20_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_20_t")
		}
		new_buf_30 := bytes.NewBuffer(nil)
		old_buf_30_w := w
		w = new_buf_30
		if err := t.union16_.(*union_20_t).L7LbUpdate.Write(w); err != nil {
			return fmt.Errorf("encode L7LbUpdate: %w", err)
		}
		if new_buf_30.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L7LbUpdate: expect %d bytes but got %d bytes", new_buf_30.Len(), int(t.Header.Len))
		}
		_, err = new_buf_30.WriteTo(old_buf_30_w)
		if err != nil {
			return err
		}
		w = old_buf_30_w
	case (t.Header.MessageType == ControlMessageType_L4LbHello):
		if _, ok := t.union16_.(*union_21_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_21_t")
		}
		new_buf_31 := bytes.NewBuffer(nil)
		old_buf_31_w := w
		w = new_buf_31
		if err := t.union16_.(*union_21_t).L4LbHello.Write(w); err != nil {
			return fmt.Errorf("encode L4LbHello: %w", err)
		}
		if new_buf_31.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L4LbHello: expect %d bytes but got %d bytes", new_buf_31.Len(), int(t.Header.Len))
		}
		_, err = new_buf_31.WriteTo(old_buf_31_w)
		if err != nil {
			return err
		}
		w = old_buf_31_w
	case (t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate):
		if _, ok := t.union16_.(*union_22_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_22_t")
		}
		new_buf_32 := bytes.NewBuffer(nil)
		old_buf_32_w := w
		w = new_buf_32
		if err := t.union16_.(*union_22_t).L4LbL7LbUpdate.Write(w); err != nil {
			return fmt.Errorf("encode L4LbL7LbUpdate: %w", err)
		}
		if new_buf_32.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L4LbL7LbUpdate: expect %d bytes but got %d bytes", new_buf_32.Len(), int(t.Header.Len))
		}
		_, err = new_buf_32.WriteTo(old_buf_32_w)
		if err != nil {
			return err
		}
		w = old_buf_32_w
	case (t.Header.MessageType == ControlMessageType_L4LbUpdate):
		if _, ok := t.union16_.(*union_23_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_23_t")
		}
		new_buf_33 := bytes.NewBuffer(nil)
		old_buf_33_w := w
		w = new_buf_33
		if err := t.union16_.(*union_23_t).L4LbUpdate.Write(w); err != nil {
			return fmt.Errorf("encode L4LbUpdate: %w", err)
		}
		if new_buf_33.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode L4LbUpdate: expect %d bytes but got %d bytes", new_buf_33.Len(), int(t.Header.Len))
		}
		_, err = new_buf_33.WriteTo(old_buf_33_w)
		if err != nil {
			return err
		}
		w = old_buf_33_w
	case (t.Header.MessageType == ControlMessageType_KeyShare):
		if _, ok := t.union16_.(*union_24_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_24_t")
		}
		new_buf_34 := bytes.NewBuffer(nil)
		old_buf_34_w := w
		w = new_buf_34
		if err := t.union16_.(*union_24_t).KeyShare.Write(w); err != nil {
			return fmt.Errorf("encode KeyShare: %w", err)
		}
		if new_buf_34.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode KeyShare: expect %d bytes but got %d bytes", new_buf_34.Len(), int(t.Header.Len))
		}
		_, err = new_buf_34.WriteTo(old_buf_34_w)
		if err != nil {
			return err
		}
		w = old_buf_34_w
	case (t.Header.MessageType == ControlMessageType_WasmInstall):
		if _, ok := t.union16_.(*union_25_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_25_t")
		}
		new_buf_35 := bytes.NewBuffer(nil)
		old_buf_35_w := w
		w = new_buf_35
		if err := t.union16_.(*union_25_t).WasmInstall.Write(w); err != nil {
			return fmt.Errorf("encode WasmInstall: %w", err)
		}
		if new_buf_35.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode WasmInstall: expect %d bytes but got %d bytes", new_buf_35.Len(), int(t.Header.Len))
		}
		_, err = new_buf_35.WriteTo(old_buf_35_w)
		if err != nil {
			return err
		}
		w = old_buf_35_w
	case (t.Header.MessageType == ControlMessageType_WasmUninstall):
		if _, ok := t.union16_.(*union_26_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_26_t")
		}
		new_buf_36 := bytes.NewBuffer(nil)
		old_buf_36_w := w
		w = new_buf_36
		if err := t.union16_.(*union_26_t).WasmUninstall.Write(w); err != nil {
			return fmt.Errorf("encode WasmUninstall: %w", err)
		}
		if new_buf_36.Len() != int(t.Header.Len) {
			return fmt.Errorf("encode WasmUninstall: expect %d bytes but got %d bytes", new_buf_36.Len(), int(t.Header.Len))
		}
		_, err = new_buf_36.WriteTo(old_buf_36_w)
		if err != nil {
			return err
		}
		w = old_buf_36_w
	default:
		if _, ok := t.union16_.(*union_27_t); !ok {
			return fmt.Errorf("encode t.union16_: union is not set to union_27_t")
		}
		len_Data := int(t.Header.Len)
		if len(t.union16_.(*union_27_t).Data) != len_Data {
			return fmt.Errorf("encode Data: expect %d bytes but got %d bytes", len_Data, len(t.union16_.(*union_27_t).Data))
		}
		if n, err := w.Write(t.union16_.(*union_27_t).Data); err != nil || n != len(t.union16_.(*union_27_t).Data) {
			return fmt.Errorf("encode Data: %w", err)
		}
	}
	return nil
}
func (t *ControlMessage) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *ControlMessage) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *ControlMessage) Read(r io.Reader) (err error) {
	if err := t.Header.Read(r); err != nil {
		return fmt.Errorf("read Header: %w", err)
	}
	switch {
	case (t.Header.MessageType == ControlMessageType_Keepalive):
		t.union16_ = &union_18_t{}
		sub_byte_len_KeepAlive := int64(t.Header.Len)
		sub_byte_r_KeepAlive := io.LimitReader(r, int64(sub_byte_len_KeepAlive))
		tmp_old_r_KeepAlive_37 := r
		r = sub_byte_r_KeepAlive
		if err := t.union16_.(*union_18_t).KeepAlive.Read(r); err != nil {
			return fmt.Errorf("read KeepAlive: %w", err)
		}
		if sub_byte_r_KeepAlive.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read KeepAlive: expect %d bytes but got %d bytes", sub_byte_len_KeepAlive, sub_byte_len_KeepAlive-sub_byte_r_KeepAlive.(*io.LimitedReader).N)
		}
		r = tmp_old_r_KeepAlive_37
	case (t.Header.MessageType == ControlMessageType_L7LbHello):
		t.union16_ = &union_19_t{}
		sub_byte_len_L7LbHello := int64(t.Header.Len)
		sub_byte_r_L7LbHello := io.LimitReader(r, int64(sub_byte_len_L7LbHello))
		tmp_old_r_L7LbHello_38 := r
		r = sub_byte_r_L7LbHello
		if err := t.union16_.(*union_19_t).L7LbHello.Read(r); err != nil {
			return fmt.Errorf("read L7LbHello: %w", err)
		}
		if sub_byte_r_L7LbHello.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L7LbHello: expect %d bytes but got %d bytes", sub_byte_len_L7LbHello, sub_byte_len_L7LbHello-sub_byte_r_L7LbHello.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L7LbHello_38
	case (t.Header.MessageType == ControlMessageType_L7LbUpdate):
		t.union16_ = &union_20_t{}
		sub_byte_len_L7LbUpdate := int64(t.Header.Len)
		sub_byte_r_L7LbUpdate := io.LimitReader(r, int64(sub_byte_len_L7LbUpdate))
		tmp_old_r_L7LbUpdate_39 := r
		r = sub_byte_r_L7LbUpdate
		if err := t.union16_.(*union_20_t).L7LbUpdate.Read(r); err != nil {
			return fmt.Errorf("read L7LbUpdate: %w", err)
		}
		if sub_byte_r_L7LbUpdate.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L7LbUpdate: expect %d bytes but got %d bytes", sub_byte_len_L7LbUpdate, sub_byte_len_L7LbUpdate-sub_byte_r_L7LbUpdate.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L7LbUpdate_39
	case (t.Header.MessageType == ControlMessageType_L4LbHello):
		t.union16_ = &union_21_t{}
		sub_byte_len_L4LbHello := int64(t.Header.Len)
		sub_byte_r_L4LbHello := io.LimitReader(r, int64(sub_byte_len_L4LbHello))
		tmp_old_r_L4LbHello_40 := r
		r = sub_byte_r_L4LbHello
		if err := t.union16_.(*union_21_t).L4LbHello.Read(r); err != nil {
			return fmt.Errorf("read L4LbHello: %w", err)
		}
		if sub_byte_r_L4LbHello.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L4LbHello: expect %d bytes but got %d bytes", sub_byte_len_L4LbHello, sub_byte_len_L4LbHello-sub_byte_r_L4LbHello.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L4LbHello_40
	case (t.Header.MessageType == ControlMessageType_L4LbL7LbUpdate):
		t.union16_ = &union_22_t{}
		sub_byte_len_L4LbL7LbUpdate := int64(t.Header.Len)
		sub_byte_r_L4LbL7LbUpdate := io.LimitReader(r, int64(sub_byte_len_L4LbL7LbUpdate))
		tmp_old_r_L4LbL7LbUpdate_41 := r
		r = sub_byte_r_L4LbL7LbUpdate
		if err := t.union16_.(*union_22_t).L4LbL7LbUpdate.Read(r); err != nil {
			return fmt.Errorf("read L4LbL7LbUpdate: %w", err)
		}
		if sub_byte_r_L4LbL7LbUpdate.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L4LbL7LbUpdate: expect %d bytes but got %d bytes", sub_byte_len_L4LbL7LbUpdate, sub_byte_len_L4LbL7LbUpdate-sub_byte_r_L4LbL7LbUpdate.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L4LbL7LbUpdate_41
	case (t.Header.MessageType == ControlMessageType_L4LbUpdate):
		t.union16_ = &union_23_t{}
		sub_byte_len_L4LbUpdate := int64(t.Header.Len)
		sub_byte_r_L4LbUpdate := io.LimitReader(r, int64(sub_byte_len_L4LbUpdate))
		tmp_old_r_L4LbUpdate_42 := r
		r = sub_byte_r_L4LbUpdate
		if err := t.union16_.(*union_23_t).L4LbUpdate.Read(r); err != nil {
			return fmt.Errorf("read L4LbUpdate: %w", err)
		}
		if sub_byte_r_L4LbUpdate.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read L4LbUpdate: expect %d bytes but got %d bytes", sub_byte_len_L4LbUpdate, sub_byte_len_L4LbUpdate-sub_byte_r_L4LbUpdate.(*io.LimitedReader).N)
		}
		r = tmp_old_r_L4LbUpdate_42
	case (t.Header.MessageType == ControlMessageType_KeyShare):
		t.union16_ = &union_24_t{}
		sub_byte_len_KeyShare := int64(t.Header.Len)
		sub_byte_r_KeyShare := io.LimitReader(r, int64(sub_byte_len_KeyShare))
		tmp_old_r_KeyShare_43 := r
		r = sub_byte_r_KeyShare
		if err := t.union16_.(*union_24_t).KeyShare.Read(r); err != nil {
			return fmt.Errorf("read KeyShare: %w", err)
		}
		if sub_byte_r_KeyShare.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read KeyShare: expect %d bytes but got %d bytes", sub_byte_len_KeyShare, sub_byte_len_KeyShare-sub_byte_r_KeyShare.(*io.LimitedReader).N)
		}
		r = tmp_old_r_KeyShare_43
	case (t.Header.MessageType == ControlMessageType_WasmInstall):
		t.union16_ = &union_25_t{}
		sub_byte_len_WasmInstall := int64(t.Header.Len)
		sub_byte_r_WasmInstall := io.LimitReader(r, int64(sub_byte_len_WasmInstall))
		tmp_old_r_WasmInstall_44 := r
		r = sub_byte_r_WasmInstall
		if err := t.union16_.(*union_25_t).WasmInstall.Read(r); err != nil {
			return fmt.Errorf("read WasmInstall: %w", err)
		}
		if sub_byte_r_WasmInstall.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read WasmInstall: expect %d bytes but got %d bytes", sub_byte_len_WasmInstall, sub_byte_len_WasmInstall-sub_byte_r_WasmInstall.(*io.LimitedReader).N)
		}
		r = tmp_old_r_WasmInstall_44
	case (t.Header.MessageType == ControlMessageType_WasmUninstall):
		t.union16_ = &union_26_t{}
		sub_byte_len_WasmUninstall := int64(t.Header.Len)
		sub_byte_r_WasmUninstall := io.LimitReader(r, int64(sub_byte_len_WasmUninstall))
		tmp_old_r_WasmUninstall_45 := r
		r = sub_byte_r_WasmUninstall
		if err := t.union16_.(*union_26_t).WasmUninstall.Read(r); err != nil {
			return fmt.Errorf("read WasmUninstall: %w", err)
		}
		if sub_byte_r_WasmUninstall.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read WasmUninstall: expect %d bytes but got %d bytes", sub_byte_len_WasmUninstall, sub_byte_len_WasmUninstall-sub_byte_r_WasmUninstall.(*io.LimitedReader).N)
		}
		r = tmp_old_r_WasmUninstall_45
	default:
		t.union16_ = &union_27_t{}
		len_Data := int(t.Header.Len)
		if len_Data != 0 {
			tmpData := make([]byte, len_Data)
			n_Data, err := io.ReadFull(r, tmpData[:])
			if err != nil {
				return fmt.Errorf("read Data: expect %d bytes but read %d bytes: %w", len_Data, n_Data, err)
			}
			t.union16_.(*union_27_t).Data = tmpData[:]
		} else {
			t.union16_.(*union_27_t).Data = nil
		}
	}
	return nil
}

func (t *ControlMessage) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *ControlMessage) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode ControlMessage: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
