// Code generated by json2go. DO NOT EDIT.
package edge

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"reflect"
)

type Method uint8

const (
	Method_Other Method = 0
	Method_Get   Method = 1
	Method_Post  Method = 2
	Method_Put   Method = 3
)

func (t Method) String() string {
	switch t {
	case Method_Other:
		return "Other"
	case Method_Get:
		return "GET"
	case Method_Post:
		return "POST"
	case Method_Put:
		return "PUT"
	}
	return fmt.Sprintf("Method(%d)", t)
}

type union2_MethodInfo interface {
	isunion1_()
}
type union_3_t struct {
	Len        uint8
	MethodName []uint8
}
type MethodInfo struct {
	Method  Method
	union1_ union2_MethodInfo
}
type VisitorRWGCX interface {
	Visit(v VisitorRWGCX, name string, field any)
}
type VisitorRWGCXFunc func(v VisitorRWGCX, name string, field any)

func (f VisitorRWGCXFunc) Visit(v VisitorRWGCX, name string, field any) {
	f(v, name, field)
}

type VisitorRWGCXVisitable interface {
	Visit(v VisitorRWGCX)
}

func VisitorRWGCXToMap(v any) interface{} {
	if v == nil {
		return nil
	}
	if inter, ok := v.(VisitorRWGCXVisitable); ok {
		if p := reflect.ValueOf(inter); p.Kind() == reflect.Pointer && p.IsNil() {
			return nil
		}
		m := map[string]interface{}{}
		inter.Visit(VisitorRWGCXFunc(func(v VisitorRWGCX, name string, field any) {
			m[name] = VisitorRWGCXToMap(field)
		}))
		return m
	}
	if tf := reflect.TypeOf(v); (tf.Kind() == reflect.Slice || tf.Kind() == reflect.Array) && !(func() bool { k := tf.Elem().Kind().String(); return k[:3] == "int" || k[:3] == "uin" || k[:3] == "flo" })() {
		m := []interface{}{}
		vf := reflect.ValueOf(v)
		for i := 0; i < vf.Len(); i++ {
			index := vf.Index(i)
			if index.Kind() == reflect.Struct && index.CanAddr() {
				index = index.Addr()
			}
			m = append(m, VisitorRWGCXToMap(index.Interface()))
		}
		return m
	}
	if tf := reflect.TypeOf(v); tf.Kind() == reflect.Pointer {
		val := reflect.ValueOf(v)
		if val.IsNil() {
			return nil
		}
		return VisitorRWGCXToMap(val.Elem().Interface())
	}
	return v
}

type String struct {
	Len  uint16
	Data []uint8
}
type Body struct {
	Len  uint32
	Body []uint8
}
type Field struct {
	Key   String
	Value String
}
type Header struct {
	Len    uint16
	Fields []Field
}
type ResponseInfo struct {
	Status uint16
	Header Header
}
type PathInfo struct {
	Path     String
	QueryLen uint8
	Query    []Field
}
type RequestInfo struct {
	PopId      uint32
	RemoteAddr [16]uint8
	Method     MethodInfo
	Path       PathInfo
	Header     Header
}

func (t *union_3_t) isunion1_() {}
func (t *MethodInfo) Len() *uint8 {
	if true == (t.Method == Method_Other) {
		if _, ok := t.union1_.(*union_3_t); !ok {
			return nil // not set
		}
		tmp := uint8(t.union1_.(*union_3_t).Len)
		return &tmp
	}
	return nil
}
func (t *MethodInfo) SetLen(v uint8) bool {
	if true == (t.Method == Method_Other) {
		if _, ok := t.union1_.(*union_3_t); !ok {
			t.union1_ = &union_3_t{}
		}
		t.union1_.(*union_3_t).Len = uint8(v)
		return true
	}
	return false
}
func (t *MethodInfo) MethodName() *[]uint8 {
	if true == (t.Method == Method_Other) {
		if _, ok := t.union1_.(*union_3_t); !ok {
			return nil // not set
		}
		tmp := []uint8(t.union1_.(*union_3_t).MethodName)
		return &tmp
	}
	return nil
}
func (t *MethodInfo) SetMethodName(v []uint8) bool {
	if true == (t.Method == Method_Other) {
		if len(v) > int(^uint8(0)) {
			return false
		}
		if _, ok := t.union1_.(*union_3_t); !ok {
			t.union1_ = &union_3_t{}
		}
		t.union1_.(*union_3_t).Len = uint8(len(v))
		t.union1_.(*union_3_t).MethodName = []uint8(v)
		return true
	}
	return false
}
func (t *MethodInfo) Visit(v VisitorRWGCX) {
	v.Visit(v, "Method", &t.Method)
	v.Visit(v, "Len", (t.Len()))
	v.Visit(v, "MethodName", (t.MethodName()))
}
func (t *MethodInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorRWGCXToMap(t))
}
func (t *MethodInfo) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Method)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Method: %w", err)
	}
	if t.Method == Method_Other {
		if _, ok := t.union1_.(*union_3_t); !ok {
			return fmt.Errorf("encode t.union1_: union is not set to union_3_t")
		}
		if n, err := w.Write([]byte{byte(t.union1_.(*union_3_t).Len)}); err != nil || n != 1 {
			return fmt.Errorf("encode t.union1_.(*union_3_t).Len: %w", err)
		}
		len_MethodName := int(t.union1_.(*union_3_t).Len)
		if len(t.union1_.(*union_3_t).MethodName) != len_MethodName {
			return fmt.Errorf("encode MethodName: expect %d bytes but got %d bytes", len_MethodName, len(t.union1_.(*union_3_t).MethodName))
		}
		if n, err := w.Write(t.union1_.(*union_3_t).MethodName); err != nil || n != len(t.union1_.(*union_3_t).MethodName) {
			return fmt.Errorf("encode MethodName: %w", err)
		}
	}
	return nil
}
func (t *MethodInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 1))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *MethodInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *MethodInfo) Read(r io.Reader) (err error) {
	tmpMethod := [1]byte{}
	n_Method, err := io.ReadFull(r, tmpMethod[:])
	if err != nil {
		return fmt.Errorf("read Method: expect 1 byte but read %d bytes: %w", n_Method, err)
	}
	t.Method = Method(tmpMethod[0])
	if t.Method == Method_Other {
		t.union1_ = &union_3_t{}
		tmpLen := [1]byte{}
		n_Len, err := io.ReadFull(r, tmpLen[:])
		if err != nil {
			return fmt.Errorf("read Len: expect 1 byte but read %d bytes: %w", n_Len, err)
		}
		t.union1_.(*union_3_t).Len = uint8(tmpLen[0])
		len_MethodName := int(t.union1_.(*union_3_t).Len)
		if len_MethodName != 0 {
			tmpMethodName := make([]byte, len_MethodName)
			n_MethodName, err := io.ReadFull(r, tmpMethodName[:])
			if err != nil {
				return fmt.Errorf("read MethodName: expect %d bytes but read %d bytes: %w", len_MethodName, n_MethodName, err)
			}
			t.union1_.(*union_3_t).MethodName = tmpMethodName[:]
		} else {
			t.union1_.(*union_3_t).MethodName = nil
		}
	}
	return nil
}

func (t *MethodInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *MethodInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode MethodInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *String) SetData(v []uint8) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.Len = uint16(len(v))
	t.Data = v
	return true
}
func (t *String) Visit(v VisitorRWGCX) {
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Data", &t.Data)
}
func (t *String) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorRWGCXToMap(t))
}
func (t *String) Write(w io.Writer) (err error) {
	tmp4 := [2]byte{}
	binary.LittleEndian.PutUint16(tmp4[:], uint16(t.Len))
	if n, err := w.Write(tmp4[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Data := int(t.Len)
	if len(t.Data) != len_Data {
		return fmt.Errorf("encode Data: expect %d bytes but got %d bytes", len_Data, len(t.Data))
	}
	if n, err := w.Write(t.Data); err != nil || n != len(t.Data) {
		return fmt.Errorf("encode Data: %w", err)
	}
	return nil
}
func (t *String) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 2))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *String) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *String) Read(r io.Reader) (err error) {
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.LittleEndian.Uint16(tmpLen[:]))
	len_Data := int(t.Len)
	if len_Data != 0 {
		tmpData := make([]byte, len_Data)
		n_Data, err := io.ReadFull(r, tmpData[:])
		if err != nil {
			return fmt.Errorf("read Data: expect %d bytes but read %d bytes: %w", len_Data, n_Data, err)
		}
		t.Data = tmpData[:]
	} else {
		t.Data = nil
	}
	return nil
}

func (t *String) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *String) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode String: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Body) SetBody(v []uint8) bool {
	if len(v) > int(^uint32(0)) {
		return false
	}
	t.Len = uint32(len(v))
	t.Body = v
	return true
}
func (t *Body) Visit(v VisitorRWGCX) {
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Body", &t.Body)
}
func (t *Body) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorRWGCXToMap(t))
}
func (t *Body) Write(w io.Writer) (err error) {
	tmp5 := [4]byte{}
	binary.LittleEndian.PutUint32(tmp5[:], uint32(t.Len))
	if n, err := w.Write(tmp5[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Body := int(t.Len)
	if len(t.Body) != len_Body {
		return fmt.Errorf("encode Body: expect %d bytes but got %d bytes", len_Body, len(t.Body))
	}
	if n, err := w.Write(t.Body); err != nil || n != len(t.Body) {
		return fmt.Errorf("encode Body: %w", err)
	}
	return nil
}
func (t *Body) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 4))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Body) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Body) Read(r io.Reader) (err error) {
	tmpLen := [4]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 4 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint32(binary.LittleEndian.Uint32(tmpLen[:]))
	len_Body := int(t.Len)
	if len_Body != 0 {
		tmpBody := make([]byte, len_Body)
		n_Body, err := io.ReadFull(r, tmpBody[:])
		if err != nil {
			return fmt.Errorf("read Body: expect %d bytes but read %d bytes: %w", len_Body, n_Body, err)
		}
		t.Body = tmpBody[:]
	} else {
		t.Body = nil
	}
	return nil
}

func (t *Body) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Body) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Body: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Field) Visit(v VisitorRWGCX) {
	v.Visit(v, "Key", &t.Key)
	v.Visit(v, "Value", &t.Value)
}
func (t *Field) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorRWGCXToMap(t))
}
func (t *Field) Write(w io.Writer) (err error) {
	if err := t.Key.Write(w); err != nil {
		return fmt.Errorf("encode Key: %w", err)
	}
	if err := t.Value.Write(w); err != nil {
		return fmt.Errorf("encode Value: %w", err)
	}
	return nil
}
func (t *Field) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 0))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Field) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Field) Read(r io.Reader) (err error) {
	if err := t.Key.Read(r); err != nil {
		return fmt.Errorf("read Key: %w", err)
	}
	if err := t.Value.Read(r); err != nil {
		return fmt.Errorf("read Value: %w", err)
	}
	return nil
}

func (t *Field) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Field) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Field: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Header) SetFields(v []Field) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.Len = uint16(len(v))
	t.Fields = v
	return true
}
func (t *Header) Visit(v VisitorRWGCX) {
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Fields", &t.Fields)
}
func (t *Header) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorRWGCXToMap(t))
}
func (t *Header) Write(w io.Writer) (err error) {
	tmp6 := [2]byte{}
	binary.LittleEndian.PutUint16(tmp6[:], uint16(t.Len))
	if n, err := w.Write(tmp6[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Fields := int(t.Len)
	if len(t.Fields) != len_Fields {
		return fmt.Errorf("encode Fields: expect %d but got %d for length", len_Fields, len(t.Fields))
	}
	for _, v := range t.Fields {
		if err := v.Write(w); err != nil {
			return fmt.Errorf("encode Fields: %w", err)
		}
	}
	return nil
}
func (t *Header) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 2))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Header) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Header) Read(r io.Reader) (err error) {
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.LittleEndian.Uint16(tmpLen[:]))
	len_Fields := int(t.Len)
	for i_7 := 0; i_7 < len_Fields; i_7++ {
		var tmp8_ Field
		if err := tmp8_.Read(r); err != nil {
			return fmt.Errorf("read Fields: %w", err)
		}
		t.Fields = append(t.Fields, tmp8_)
	}
	return nil
}

func (t *Header) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Header) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Header: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *ResponseInfo) Visit(v VisitorRWGCX) {
	v.Visit(v, "Status", &t.Status)
	v.Visit(v, "Header", &t.Header)
}
func (t *ResponseInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorRWGCXToMap(t))
}
func (t *ResponseInfo) Write(w io.Writer) (err error) {
	tmp9 := [2]byte{}
	binary.LittleEndian.PutUint16(tmp9[:], uint16(t.Status))
	if n, err := w.Write(tmp9[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Status: %w", err)
	}
	if err := t.Header.Write(w); err != nil {
		return fmt.Errorf("encode Header: %w", err)
	}
	return nil
}
func (t *ResponseInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 2))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *ResponseInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *ResponseInfo) Read(r io.Reader) (err error) {
	tmpStatus := [2]byte{}
	n_Status, err := io.ReadFull(r, tmpStatus[:])
	if err != nil {
		return fmt.Errorf("read Status: expect 2 bytes but read %d bytes: %w", n_Status, err)
	}
	t.Status = uint16(binary.LittleEndian.Uint16(tmpStatus[:]))
	if err := t.Header.Read(r); err != nil {
		return fmt.Errorf("read Header: %w", err)
	}
	return nil
}

func (t *ResponseInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *ResponseInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode ResponseInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *PathInfo) SetQuery(v []Field) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.QueryLen = uint8(len(v))
	t.Query = v
	return true
}
func (t *PathInfo) Visit(v VisitorRWGCX) {
	v.Visit(v, "Path", &t.Path)
	v.Visit(v, "QueryLen", &t.QueryLen)
	v.Visit(v, "Query", &t.Query)
}
func (t *PathInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorRWGCXToMap(t))
}
func (t *PathInfo) Write(w io.Writer) (err error) {
	if err := t.Path.Write(w); err != nil {
		return fmt.Errorf("encode Path: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.QueryLen)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.QueryLen: %w", err)
	}
	len_Query := int(t.QueryLen)
	if len(t.Query) != len_Query {
		return fmt.Errorf("encode Query: expect %d but got %d for length", len_Query, len(t.Query))
	}
	for _, v := range t.Query {
		if err := v.Write(w); err != nil {
			return fmt.Errorf("encode Query: %w", err)
		}
	}
	return nil
}
func (t *PathInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 0))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *PathInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *PathInfo) Read(r io.Reader) (err error) {
	if err := t.Path.Read(r); err != nil {
		return fmt.Errorf("read Path: %w", err)
	}
	tmpQueryLen := [1]byte{}
	n_QueryLen, err := io.ReadFull(r, tmpQueryLen[:])
	if err != nil {
		return fmt.Errorf("read QueryLen: expect 1 byte but read %d bytes: %w", n_QueryLen, err)
	}
	t.QueryLen = uint8(tmpQueryLen[0])
	len_Query := int(t.QueryLen)
	for i_10 := 0; i_10 < len_Query; i_10++ {
		var tmp11_ Field
		if err := tmp11_.Read(r); err != nil {
			return fmt.Errorf("read Query: %w", err)
		}
		t.Query = append(t.Query, tmp11_)
	}
	return nil
}

func (t *PathInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *PathInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode PathInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *RequestInfo) Visit(v VisitorRWGCX) {
	v.Visit(v, "PopId", &t.PopId)
	v.Visit(v, "RemoteAddr", &t.RemoteAddr)
	v.Visit(v, "Method", &t.Method)
	v.Visit(v, "Path", &t.Path)
	v.Visit(v, "Header", &t.Header)
}
func (t *RequestInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorRWGCXToMap(t))
}
func (t *RequestInfo) Write(w io.Writer) (err error) {
	tmp12 := [4]byte{}
	binary.LittleEndian.PutUint32(tmp12[:], uint32(t.PopId))
	if n, err := w.Write(tmp12[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.PopId: %w", err)
	}
	if n, err := w.Write(t.RemoteAddr[:]); err != nil || n != len(t.RemoteAddr) {
		return fmt.Errorf("encode RemoteAddr: %w", err)
	}
	if err := t.Method.Write(w); err != nil {
		return fmt.Errorf("encode Method: %w", err)
	}
	if err := t.Path.Write(w); err != nil {
		return fmt.Errorf("encode Path: %w", err)
	}
	if err := t.Header.Write(w); err != nil {
		return fmt.Errorf("encode Header: %w", err)
	}
	return nil
}
func (t *RequestInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 20))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *RequestInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *RequestInfo) Read(r io.Reader) (err error) {
	tmpPopId := [4]byte{}
	n_PopId, err := io.ReadFull(r, tmpPopId[:])
	if err != nil {
		return fmt.Errorf("read PopId: expect 4 bytes but read %d bytes: %w", n_PopId, err)
	}
	t.PopId = uint32(binary.LittleEndian.Uint32(tmpPopId[:]))
	n_RemoteAddr, err := io.ReadFull(r, t.RemoteAddr[:])
	if err != nil {
		return fmt.Errorf("read RemoteAddr: expect %d bytes but read %d bytes: %w", 16, n_RemoteAddr, err)
	}
	if err := t.Method.Read(r); err != nil {
		return fmt.Errorf("read Method: %w", err)
	}
	if err := t.Path.Read(r); err != nil {
		return fmt.Errorf("read Path: %w", err)
	}
	if err := t.Header.Read(r); err != nil {
		return fmt.Errorf("read Header: %w", err)
	}
	return nil
}

func (t *RequestInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *RequestInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode RequestInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
