// Code generated by json2go. DO NOT EDIT.
package main

import (
	"bufio"
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"reflect"
)

type EtherType uint16

const (
	EtherType_Ipv4           EtherType = 0x0800
	EtherType_Arp            EtherType = 0x0806
	EtherType_Vlan           EtherType = 0x8100
	EtherType_Ipv6           EtherType = 0x86DD
	EtherType_ServiceVlen    EtherType = 0x88A8
	EtherType_PppoeDiscovery EtherType = 0x8863
	EtherType_PppoeSession   EtherType = 0x8864
)

func (t EtherType) String() string {
	switch t {
	case EtherType_Ipv4:
		return "Ipv4"
	case EtherType_Arp:
		return "Arp"
	case EtherType_Vlan:
		return "Vlan"
	case EtherType_Ipv6:
		return "Ipv6"
	case EtherType_ServiceVlen:
		return "ServiceVlen"
	case EtherType_PppoeDiscovery:
		return "PppoeDiscovery"
	case EtherType_PppoeSession:
		return "PppoeSession"
	}
	return fmt.Sprintf("EtherType(%d)", t)
}

type ProtocolNumber uint8

const (
	ProtocolNumber_Hopopt        ProtocolNumber = 0
	ProtocolNumber_Icmp          ProtocolNumber = 1
	ProtocolNumber_Igmp          ProtocolNumber = 2
	ProtocolNumber_Ggp           ProtocolNumber = 3
	ProtocolNumber_Ipv4          ProtocolNumber = 4
	ProtocolNumber_St            ProtocolNumber = 5
	ProtocolNumber_Tcp           ProtocolNumber = 6
	ProtocolNumber_Cbt           ProtocolNumber = 7
	ProtocolNumber_Egp           ProtocolNumber = 8
	ProtocolNumber_Igp           ProtocolNumber = 9
	ProtocolNumber_BbnRccMon     ProtocolNumber = 10
	ProtocolNumber_NvpIi         ProtocolNumber = 11
	ProtocolNumber_Pup           ProtocolNumber = 12
	ProtocolNumber_Argus         ProtocolNumber = 13
	ProtocolNumber_Emcon         ProtocolNumber = 14
	ProtocolNumber_Xnet          ProtocolNumber = 15
	ProtocolNumber_Chaos         ProtocolNumber = 16
	ProtocolNumber_Udp           ProtocolNumber = 17
	ProtocolNumber_Mux           ProtocolNumber = 18
	ProtocolNumber_DcnMeas       ProtocolNumber = 19
	ProtocolNumber_Hmp           ProtocolNumber = 20
	ProtocolNumber_Prm           ProtocolNumber = 21
	ProtocolNumber_XnsIdp        ProtocolNumber = 22
	ProtocolNumber_Trunk1        ProtocolNumber = 23
	ProtocolNumber_Trunk2        ProtocolNumber = 24
	ProtocolNumber_RoutingHeader ProtocolNumber = 43
	ProtocolNumber_Esp           ProtocolNumber = 50
	ProtocolNumber_Ah            ProtocolNumber = 51
	ProtocolNumber_Icmpv6        ProtocolNumber = 58
	ProtocolNumber_Ospf          ProtocolNumber = 89
	ProtocolNumber_Ethernet      ProtocolNumber = 143
)

func (t ProtocolNumber) String() string {
	switch t {
	case ProtocolNumber_Hopopt:
		return "Hopopt"
	case ProtocolNumber_Icmp:
		return "Icmp"
	case ProtocolNumber_Igmp:
		return "Igmp"
	case ProtocolNumber_Ggp:
		return "Ggp"
	case ProtocolNumber_Ipv4:
		return "Ipv4"
	case ProtocolNumber_St:
		return "St"
	case ProtocolNumber_Tcp:
		return "Tcp"
	case ProtocolNumber_Cbt:
		return "Cbt"
	case ProtocolNumber_Egp:
		return "Egp"
	case ProtocolNumber_Igp:
		return "Igp"
	case ProtocolNumber_BbnRccMon:
		return "BbnRccMon"
	case ProtocolNumber_NvpIi:
		return "NvpIi"
	case ProtocolNumber_Pup:
		return "Pup"
	case ProtocolNumber_Argus:
		return "Argus"
	case ProtocolNumber_Emcon:
		return "Emcon"
	case ProtocolNumber_Xnet:
		return "Xnet"
	case ProtocolNumber_Chaos:
		return "Chaos"
	case ProtocolNumber_Udp:
		return "Udp"
	case ProtocolNumber_Mux:
		return "Mux"
	case ProtocolNumber_DcnMeas:
		return "DcnMeas"
	case ProtocolNumber_Hmp:
		return "Hmp"
	case ProtocolNumber_Prm:
		return "Prm"
	case ProtocolNumber_XnsIdp:
		return "XnsIdp"
	case ProtocolNumber_Trunk1:
		return "Trunk1"
	case ProtocolNumber_Trunk2:
		return "Trunk2"
	case ProtocolNumber_RoutingHeader:
		return "RoutingHeader"
	case ProtocolNumber_Esp:
		return "Esp"
	case ProtocolNumber_Ah:
		return "Ah"
	case ProtocolNumber_Icmpv6:
		return "Icmpv6"
	case ProtocolNumber_Ospf:
		return "Ospf"
	case ProtocolNumber_Ethernet:
		return "Ethernet"
	}
	return fmt.Sprintf("ProtocolNumber(%d)", t)
}

type TcpoptionKind uint8

const (
	TcpoptionKind_EndOfOptionsList   TcpoptionKind = 0
	TcpoptionKind_Nop                TcpoptionKind = 1
	TcpoptionKind_MaximumSegmentSize TcpoptionKind = 2
	TcpoptionKind_WindowScale        TcpoptionKind = 3
	TcpoptionKind_SackPermitted      TcpoptionKind = 4
	TcpoptionKind_Sack               TcpoptionKind = 5
	TcpoptionKind_Timestamp          TcpoptionKind = 8
	TcpoptionKind_Mptcp              TcpoptionKind = 30
)

func (t TcpoptionKind) String() string {
	switch t {
	case TcpoptionKind_EndOfOptionsList:
		return "EndOfOptionsList"
	case TcpoptionKind_Nop:
		return "Nop"
	case TcpoptionKind_MaximumSegmentSize:
		return "MaximumSegmentSize"
	case TcpoptionKind_WindowScale:
		return "WindowScale"
	case TcpoptionKind_SackPermitted:
		return "SackPermitted"
	case TcpoptionKind_Sack:
		return "Sack"
	case TcpoptionKind_Timestamp:
		return "Timestamp"
	case TcpoptionKind_Mptcp:
		return "Mptcp"
	}
	return fmt.Sprintf("TcpoptionKind(%d)", t)
}

type EtherHeader struct {
	DstMac    [6]uint8
	SrcMac    [6]uint8
	EtherType EtherType
}
type VisitorJHZCL interface {
	Visit(v VisitorJHZCL, name string, field any)
}
type VisitorJHZCLFunc func(v VisitorJHZCL, name string, field any)

func (f VisitorJHZCLFunc) Visit(v VisitorJHZCL, name string, field any) {
	f(v, name, field)
}

type VisitorJHZCLVisitable interface {
	Visit(v VisitorJHZCL)
}

func VisitorJHZCLToMap(v any) interface{} {
	if v == nil {
		return nil
	}
	if inter, ok := v.(VisitorJHZCLVisitable); ok {
		if p := reflect.ValueOf(inter); p.Kind() == reflect.Pointer && p.IsNil() {
			return nil
		}
		m := map[string]interface{}{}
		inter.Visit(VisitorJHZCLFunc(func(v VisitorJHZCL, name string, field any) {
			m[name] = VisitorJHZCLToMap(field)
		}))
		return m
	}
	if tf := reflect.TypeOf(v); (tf.Kind() == reflect.Slice || tf.Kind() == reflect.Array) && !(func() bool { k := tf.Elem().Kind().String(); return k[:3] == "int" || k[:3] == "uin" || k[:3] == "flo" })() {
		m := []interface{}{}
		vf := reflect.ValueOf(v)
		for i := 0; i < vf.Len(); i++ {
			index := vf.Index(i)
			if index.Kind() == reflect.Struct && index.CanAddr() {
				index = index.Addr()
			}
			m = append(m, VisitorJHZCLToMap(index.Interface()))
		}
		return m
	}
	if tf := reflect.TypeOf(v); tf.Kind() == reflect.Pointer {
		val := reflect.ValueOf(v)
		if val.IsNil() {
			return nil
		}
		return VisitorJHZCLToMap(val.Elem().Interface())
	}
	return v
}

type Ipv4Header struct {
	flags2   uint8
	flags3   uint8
	Len      uint16
	Id       uint16
	flags4   uint16
	Ttl      uint8
	Proto    ProtocolNumber
	Checksum uint16
	SrcAddr  [4]uint8
	DstAddr  [4]uint8
	Options  []uint8
}
type SackBlock struct {
	Left  uint32
	Right uint32
}
type Timestamp struct {
	Value     uint32
	EchoReply uint32
}
type Ipv4Packet struct {
	Hdr  Ipv4Header
	Data []uint8
}
type Sack struct {
	Blocks []SackBlock
}
type union16_Tcpoption interface {
	isunion15_()
}
type union_17_t struct{}
type union_18_t struct{}
type union_19_t struct {
	Length uint8
	Mss    uint16
}
type union_20_t struct {
	Length     uint8
	ShiftCount uint8
}
type union_21_t struct {
	Length uint8
}
type union_22_t struct {
	Length uint8
	Sack   Sack
}
type union_23_t struct {
	Length    uint8
	Timestamp Timestamp
}
type union_24_t struct {
	Length uint8
	Data   []uint8
}
type Tcpoption struct {
	Kind     TcpoptionKind
	union15_ union16_Tcpoption
}
type Tcpheader struct {
	SrcPort       uint16
	DstPort       uint16
	SeqNum        uint32
	AckNum        uint32
	flags30       uint8
	flags31       uint8
	WindowSize    uint16
	Checksum      uint16
	UrgentPointer uint16
	Options       []Tcpoption
}
type Tcpsegment struct {
	Hdr     Tcpheader
	Payload []uint8
}
type Frame struct {
	Ether EtherHeader
	Ipip  Ipv4Header
	Ipv4  Ipv4Header
	Tcp   Tcpsegment
}

func (t *EtherHeader) Visit(v VisitorJHZCL) {
	v.Visit(v, "DstMac", &t.DstMac)
	v.Visit(v, "SrcMac", &t.SrcMac)
	v.Visit(v, "EtherType", &t.EtherType)
}
func (t *EtherHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *EtherHeader) Write(w io.Writer) (err error) {
	if n, err := w.Write(t.DstMac[:]); err != nil || n != len(t.DstMac) {
		return fmt.Errorf("encode DstMac: %w", err)
	}
	if n, err := w.Write(t.SrcMac[:]); err != nil || n != len(t.SrcMac) {
		return fmt.Errorf("encode SrcMac: %w", err)
	}
	tmp1 := [2]byte{}
	binary.BigEndian.PutUint16(tmp1[:], uint16(t.EtherType))
	if n, err := w.Write(tmp1[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.EtherType: %w", err)
	}
	return nil
}
func (t *EtherHeader) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 14))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *EtherHeader) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *EtherHeader) Read(r io.Reader) (err error) {
	n_DstMac, err := io.ReadFull(r, t.DstMac[:])
	if err != nil {
		return fmt.Errorf("read DstMac: expect %d bytes but read %d bytes: %w", 6, n_DstMac, err)
	}
	n_SrcMac, err := io.ReadFull(r, t.SrcMac[:])
	if err != nil {
		return fmt.Errorf("read SrcMac: expect %d bytes but read %d bytes: %w", 6, n_SrcMac, err)
	}
	tmpEtherType := [2]byte{}
	n_EtherType, err := io.ReadFull(r, tmpEtherType[:])
	if err != nil {
		return fmt.Errorf("read EtherType: expect 2 bytes but read %d bytes: %w", n_EtherType, err)
	}
	t.EtherType = EtherType(binary.BigEndian.Uint16(tmpEtherType[:]))
	return nil
}

func (t *EtherHeader) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *EtherHeader) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode EtherHeader: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Ipv4Header) Version() uint8 {
	return ((t.flags2 & 0xf0) >> 4)
}
func (t *Ipv4Header) SetVersion(v uint8) bool {
	if v > 15 {
		return false
	}
	t.flags2 = (t.flags2 & ^uint8(0xf0)) | ((v & 0xf) << 4)
	return true
}
func (t *Ipv4Header) Ihl() uint8 {
	return ((t.flags2 & 0x0f) >> 0)
}
func (t *Ipv4Header) SetIhl(v uint8) bool {
	if v > 15 {
		return false
	}
	t.flags2 = (t.flags2 & ^uint8(0xf)) | ((v & 0xf) << 0)
	return true
}
func (t *Ipv4Header) Dscp() uint8 {
	return ((t.flags3 & 0xfc) >> 2)
}
func (t *Ipv4Header) SetDscp(v uint8) bool {
	if v > 63 {
		return false
	}
	t.flags3 = (t.flags3 & ^uint8(0xfc)) | ((v & 0x3f) << 2)
	return true
}
func (t *Ipv4Header) Ecn() uint8 {
	return ((t.flags3 & 0x03) >> 0)
}
func (t *Ipv4Header) SetEcn(v uint8) bool {
	if v > 3 {
		return false
	}
	t.flags3 = (t.flags3 & ^uint8(0x3)) | ((v & 0x3) << 0)
	return true
}
func (t *Ipv4Header) Reserved() bool {
	return ((t.flags4 & 0x8000) >> 15) == 1
}
func (t *Ipv4Header) SetReserved(v bool) {
	if v {
		t.flags4 |= uint16(0x8000)
	} else {
		t.flags4 &= ^uint16(0x8000)
	}
}
func (t *Ipv4Header) DontFragment() bool {
	return ((t.flags4 & 0x4000) >> 14) == 1
}
func (t *Ipv4Header) SetDontFragment(v bool) {
	if v {
		t.flags4 |= uint16(0x4000)
	} else {
		t.flags4 &= ^uint16(0x4000)
	}
}
func (t *Ipv4Header) MoreFragment() bool {
	return ((t.flags4 & 0x2000) >> 13) == 1
}
func (t *Ipv4Header) SetMoreFragment(v bool) {
	if v {
		t.flags4 |= uint16(0x2000)
	} else {
		t.flags4 &= ^uint16(0x2000)
	}
}
func (t *Ipv4Header) FragOffset() uint16 {
	return ((t.flags4 & 0x1fff) >> 0)
}
func (t *Ipv4Header) SetFragOffset(v uint16) bool {
	if v > 8191 {
		return false
	}
	t.flags4 = (t.flags4 & ^uint16(0x1fff)) | ((v & 0x1fff) << 0)
	return true
}
func (t *Ipv4Header) SetOptions(v []uint8) bool {
	t.Options = v
	return true
}
func (t *Ipv4Header) Visit(v VisitorJHZCL) {
	v.Visit(v, "Version", t.Version())
	v.Visit(v, "Ihl", t.Ihl())
	v.Visit(v, "Dscp", t.Dscp())
	v.Visit(v, "Ecn", t.Ecn())
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Id", &t.Id)
	v.Visit(v, "Reserved", (func() uint16 {
		if t.Reserved() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "DontFragment", (func() uint16 {
		if t.DontFragment() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "MoreFragment", (func() uint16 {
		if t.MoreFragment() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "FragOffset", t.FragOffset())
	v.Visit(v, "Ttl", &t.Ttl)
	v.Visit(v, "Proto", &t.Proto)
	v.Visit(v, "Checksum", &t.Checksum)
	v.Visit(v, "SrcAddr", &t.SrcAddr)
	v.Visit(v, "DstAddr", &t.DstAddr)
	v.Visit(v, "Options", &t.Options)
}
func (t *Ipv4Header) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *Ipv4Header) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.flags2)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.flags2: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.flags3)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.flags3: %w", err)
	}
	tmp5 := [2]byte{}
	binary.BigEndian.PutUint16(tmp5[:], uint16(t.Len))
	if n, err := w.Write(tmp5[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	tmp6 := [2]byte{}
	binary.BigEndian.PutUint16(tmp6[:], uint16(t.Id))
	if n, err := w.Write(tmp6[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Id: %w", err)
	}
	tmp7 := [2]byte{}
	binary.BigEndian.PutUint16(tmp7[:], uint16(t.flags4))
	if n, err := w.Write(tmp7[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.flags4: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.Ttl)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Ttl: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.Proto)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Proto: %w", err)
	}
	tmp8 := [2]byte{}
	binary.BigEndian.PutUint16(tmp8[:], uint16(t.Checksum))
	if n, err := w.Write(tmp8[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Checksum: %w", err)
	}
	if n, err := w.Write(t.SrcAddr[:]); err != nil || n != len(t.SrcAddr) {
		return fmt.Errorf("encode SrcAddr: %w", err)
	}
	if n, err := w.Write(t.DstAddr[:]); err != nil || n != len(t.DstAddr) {
		return fmt.Errorf("encode DstAddr: %w", err)
	}
	len_Options := int(((uint8(t.Ihl()) * 4) - 20))
	if len(t.Options) != len_Options {
		return fmt.Errorf("encode Options: expect %d bytes but got %d bytes", len_Options, len(t.Options))
	}
	if n, err := w.Write(t.Options); err != nil || n != len(t.Options) {
		return fmt.Errorf("encode Options: %w", err)
	}
	return nil
}
func (t *Ipv4Header) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 20))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Ipv4Header) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Ipv4Header) Read(r io.Reader) (err error) {
	tmpflags2 := [1]byte{}
	n_flags2, err := io.ReadFull(r, tmpflags2[:])
	if err != nil {
		return fmt.Errorf("read flags2: expect 1 byte but read %d bytes: %w", n_flags2, err)
	}
	t.flags2 = uint8(tmpflags2[0])
	tmpflags3 := [1]byte{}
	n_flags3, err := io.ReadFull(r, tmpflags3[:])
	if err != nil {
		return fmt.Errorf("read flags3: expect 1 byte but read %d bytes: %w", n_flags3, err)
	}
	t.flags3 = uint8(tmpflags3[0])
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.BigEndian.Uint16(tmpLen[:]))
	tmpId := [2]byte{}
	n_Id, err := io.ReadFull(r, tmpId[:])
	if err != nil {
		return fmt.Errorf("read Id: expect 2 bytes but read %d bytes: %w", n_Id, err)
	}
	t.Id = uint16(binary.BigEndian.Uint16(tmpId[:]))
	tmpflags4 := [2]byte{}
	n_flags4, err := io.ReadFull(r, tmpflags4[:])
	if err != nil {
		return fmt.Errorf("read flags4: expect 2 bytes but read %d bytes: %w", n_flags4, err)
	}
	t.flags4 = uint16(binary.BigEndian.Uint16(tmpflags4[:]))
	tmpTtl := [1]byte{}
	n_Ttl, err := io.ReadFull(r, tmpTtl[:])
	if err != nil {
		return fmt.Errorf("read Ttl: expect 1 byte but read %d bytes: %w", n_Ttl, err)
	}
	t.Ttl = uint8(tmpTtl[0])
	tmpProto := [1]byte{}
	n_Proto, err := io.ReadFull(r, tmpProto[:])
	if err != nil {
		return fmt.Errorf("read Proto: expect 1 byte but read %d bytes: %w", n_Proto, err)
	}
	t.Proto = ProtocolNumber(tmpProto[0])
	tmpChecksum := [2]byte{}
	n_Checksum, err := io.ReadFull(r, tmpChecksum[:])
	if err != nil {
		return fmt.Errorf("read Checksum: expect 2 bytes but read %d bytes: %w", n_Checksum, err)
	}
	t.Checksum = uint16(binary.BigEndian.Uint16(tmpChecksum[:]))
	n_SrcAddr, err := io.ReadFull(r, t.SrcAddr[:])
	if err != nil {
		return fmt.Errorf("read SrcAddr: expect %d bytes but read %d bytes: %w", 4, n_SrcAddr, err)
	}
	n_DstAddr, err := io.ReadFull(r, t.DstAddr[:])
	if err != nil {
		return fmt.Errorf("read DstAddr: expect %d bytes but read %d bytes: %w", 4, n_DstAddr, err)
	}
	len_Options := int(((uint8(t.Ihl()) * 4) - 20))
	if len_Options != 0 {
		tmpOptions := make([]byte, len_Options)
		n_Options, err := io.ReadFull(r, tmpOptions[:])
		if err != nil {
			return fmt.Errorf("read Options: expect %d bytes but read %d bytes: %w", len_Options, n_Options, err)
		}
		t.Options = tmpOptions[:]
	} else {
		t.Options = nil
	}
	return nil
}

func (t *Ipv4Header) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Ipv4Header) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Ipv4Header: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *SackBlock) Visit(v VisitorJHZCL) {
	v.Visit(v, "Left", &t.Left)
	v.Visit(v, "Right", &t.Right)
}
func (t *SackBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *SackBlock) Write(w io.Writer) (err error) {
	tmp9 := [4]byte{}
	binary.BigEndian.PutUint32(tmp9[:], uint32(t.Left))
	if n, err := w.Write(tmp9[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.Left: %w", err)
	}
	tmp10 := [4]byte{}
	binary.BigEndian.PutUint32(tmp10[:], uint32(t.Right))
	if n, err := w.Write(tmp10[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.Right: %w", err)
	}
	return nil
}
func (t *SackBlock) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 8))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *SackBlock) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *SackBlock) Read(r io.Reader) (err error) {
	tmpLeft := [4]byte{}
	n_Left, err := io.ReadFull(r, tmpLeft[:])
	if err != nil {
		return fmt.Errorf("read Left: expect 4 bytes but read %d bytes: %w", n_Left, err)
	}
	t.Left = uint32(binary.BigEndian.Uint32(tmpLeft[:]))
	tmpRight := [4]byte{}
	n_Right, err := io.ReadFull(r, tmpRight[:])
	if err != nil {
		return fmt.Errorf("read Right: expect 4 bytes but read %d bytes: %w", n_Right, err)
	}
	t.Right = uint32(binary.BigEndian.Uint32(tmpRight[:]))
	return nil
}

func (t *SackBlock) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *SackBlock) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode SackBlock: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Timestamp) Visit(v VisitorJHZCL) {
	v.Visit(v, "Value", &t.Value)
	v.Visit(v, "EchoReply", &t.EchoReply)
}
func (t *Timestamp) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *Timestamp) Write(w io.Writer) (err error) {
	tmp11 := [4]byte{}
	binary.BigEndian.PutUint32(tmp11[:], uint32(t.Value))
	if n, err := w.Write(tmp11[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.Value: %w", err)
	}
	tmp12 := [4]byte{}
	binary.BigEndian.PutUint32(tmp12[:], uint32(t.EchoReply))
	if n, err := w.Write(tmp12[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.EchoReply: %w", err)
	}
	return nil
}
func (t *Timestamp) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 8))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Timestamp) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Timestamp) Read(r io.Reader) (err error) {
	tmpValue := [4]byte{}
	n_Value, err := io.ReadFull(r, tmpValue[:])
	if err != nil {
		return fmt.Errorf("read Value: expect 4 bytes but read %d bytes: %w", n_Value, err)
	}
	t.Value = uint32(binary.BigEndian.Uint32(tmpValue[:]))
	tmpEchoReply := [4]byte{}
	n_EchoReply, err := io.ReadFull(r, tmpEchoReply[:])
	if err != nil {
		return fmt.Errorf("read EchoReply: expect 4 bytes but read %d bytes: %w", n_EchoReply, err)
	}
	t.EchoReply = uint32(binary.BigEndian.Uint32(tmpEchoReply[:]))
	return nil
}

func (t *Timestamp) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Timestamp) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Timestamp: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Ipv4Packet) SetData(v []uint8) bool {
	t.Data = v
	return true
}
func (t *Ipv4Packet) Visit(v VisitorJHZCL) {
	v.Visit(v, "Hdr", &t.Hdr)
	v.Visit(v, "Data", &t.Data)
}
func (t *Ipv4Packet) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *Ipv4Packet) Write(w io.Writer) (err error) {
	if err := t.Hdr.Write(w); err != nil {
		return fmt.Errorf("encode Hdr: %w", err)
	}
	Len := (t.Hdr.Len - uint16((t.Hdr.Ihl() * 4)))
	len_Data := int(Len)
	if len(t.Data) != len_Data {
		return fmt.Errorf("encode Data: expect %d bytes but got %d bytes", len_Data, len(t.Data))
	}
	if n, err := w.Write(t.Data); err != nil || n != len(t.Data) {
		return fmt.Errorf("encode Data: %w", err)
	}
	return nil
}
func (t *Ipv4Packet) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 0))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Ipv4Packet) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Ipv4Packet) Read(r io.Reader) (err error) {
	if err := t.Hdr.Read(r); err != nil {
		return fmt.Errorf("read Hdr: %w", err)
	}
	Len := (t.Hdr.Len - uint16((t.Hdr.Ihl() * 4)))
	len_Data := int(Len)
	if len_Data != 0 {
		tmpData := make([]byte, len_Data)
		n_Data, err := io.ReadFull(r, tmpData[:])
		if err != nil {
			return fmt.Errorf("read Data: expect %d bytes but read %d bytes: %w", len_Data, n_Data, err)
		}
		t.Data = tmpData[:]
	} else {
		t.Data = nil
	}
	return nil
}

func (t *Ipv4Packet) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Ipv4Packet) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Ipv4Packet: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Sack) Visit(v VisitorJHZCL) {
	v.Visit(v, "Blocks", &t.Blocks)
}
func (t *Sack) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *Sack) Write(w io.Writer) (err error) {
	for _, v := range t.Blocks {
		if err := v.Write(w); err != nil {
			return fmt.Errorf("encode Blocks: %w", err)
		}
	}
	return nil
}
func (t *Sack) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 0))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Sack) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Sack) Read(r io.Reader) (err error) {
	tmp_byte_scanner13_ := bufio.NewReaderSize(r, 1)
	old_r_Blocks := r
	r = tmp_byte_scanner13_
	for {
		_, err := tmp_byte_scanner13_.ReadByte()
		if err != nil {
			if err != io.EOF {
				return fmt.Errorf("read Blocks: %w", err)
			}
			break
		}
		if err := tmp_byte_scanner13_.UnreadByte(); err != nil {
			return fmt.Errorf("read Blocks: unexpected unread error: %w", err)
		}
		var tmp14_ SackBlock
		if err := tmp14_.Read(r); err != nil {
			return fmt.Errorf("read Blocks: %w", err)
		}
		t.Blocks = append(t.Blocks, tmp14_)
	}
	r = old_r_Blocks
	return nil
}

func (t *Sack) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Sack) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Sack: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *union_17_t) isunion15_() {}
func (t *union_18_t) isunion15_() {}
func (t *union_19_t) isunion15_() {}
func (t *union_20_t) isunion15_() {}
func (t *union_21_t) isunion15_() {}
func (t *union_22_t) isunion15_() {}
func (t *union_23_t) isunion15_() {}
func (t *union_24_t) isunion15_() {}
func (t *Tcpoption) Data() *[]uint8 {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return nil
	} else if t.Kind == TcpoptionKind_Nop {
		return nil
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		return nil
	} else if t.Kind == TcpoptionKind_WindowScale {
		return nil
	} else if t.Kind == TcpoptionKind_SackPermitted {
		return nil
	} else if t.Kind == TcpoptionKind_Sack {
		return nil
	} else if t.Kind == TcpoptionKind_Timestamp {
		return nil
	} else if true {
		if _, ok := t.union15_.(*union_24_t); !ok {
			return nil // not set
		}
		tmp := []uint8(t.union15_.(*union_24_t).Data)
		return &tmp
	}
	return nil
}
func (t *Tcpoption) SetData(v []uint8) bool {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return false
	} else if t.Kind == TcpoptionKind_Nop {
		return false
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		return false
	} else if t.Kind == TcpoptionKind_WindowScale {
		return false
	} else if t.Kind == TcpoptionKind_SackPermitted {
		return false
	} else if t.Kind == TcpoptionKind_Sack {
		return false
	} else if t.Kind == TcpoptionKind_Timestamp {
		return false
	} else if true {
		if _, ok := t.union15_.(*union_24_t); !ok {
			t.union15_ = &union_24_t{}
		}
		t.union15_.(*union_24_t).Data = []uint8(v)
		return true
	}
	return false
}
func (t *Tcpoption) Length() *uint8 {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return nil
	} else if t.Kind == TcpoptionKind_Nop {
		return nil
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		if _, ok := t.union15_.(*union_19_t); !ok {
			return nil // not set
		}
		tmp := uint8(t.union15_.(*union_19_t).Length)
		return &tmp
	} else if t.Kind == TcpoptionKind_WindowScale {
		if _, ok := t.union15_.(*union_20_t); !ok {
			return nil // not set
		}
		tmp := uint8(t.union15_.(*union_20_t).Length)
		return &tmp
	} else if t.Kind == TcpoptionKind_SackPermitted {
		if _, ok := t.union15_.(*union_21_t); !ok {
			return nil // not set
		}
		tmp := uint8(t.union15_.(*union_21_t).Length)
		return &tmp
	} else if t.Kind == TcpoptionKind_Sack {
		if _, ok := t.union15_.(*union_22_t); !ok {
			return nil // not set
		}
		tmp := uint8(t.union15_.(*union_22_t).Length)
		return &tmp
	} else if t.Kind == TcpoptionKind_Timestamp {
		if _, ok := t.union15_.(*union_23_t); !ok {
			return nil // not set
		}
		tmp := uint8(t.union15_.(*union_23_t).Length)
		return &tmp
	} else if true {
		if _, ok := t.union15_.(*union_24_t); !ok {
			return nil // not set
		}
		tmp := uint8(t.union15_.(*union_24_t).Length)
		return &tmp
	}
	return nil
}
func (t *Tcpoption) SetLength(v uint8) bool {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return false
	} else if t.Kind == TcpoptionKind_Nop {
		return false
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		if _, ok := t.union15_.(*union_19_t); !ok {
			t.union15_ = &union_19_t{}
		}
		t.union15_.(*union_19_t).Length = uint8(v)
		return true
	} else if t.Kind == TcpoptionKind_WindowScale {
		if _, ok := t.union15_.(*union_20_t); !ok {
			t.union15_ = &union_20_t{}
		}
		t.union15_.(*union_20_t).Length = uint8(v)
		return true
	} else if t.Kind == TcpoptionKind_SackPermitted {
		if _, ok := t.union15_.(*union_21_t); !ok {
			t.union15_ = &union_21_t{}
		}
		t.union15_.(*union_21_t).Length = uint8(v)
		return true
	} else if t.Kind == TcpoptionKind_Sack {
		if _, ok := t.union15_.(*union_22_t); !ok {
			t.union15_ = &union_22_t{}
		}
		t.union15_.(*union_22_t).Length = uint8(v)
		return true
	} else if t.Kind == TcpoptionKind_Timestamp {
		if _, ok := t.union15_.(*union_23_t); !ok {
			t.union15_ = &union_23_t{}
		}
		t.union15_.(*union_23_t).Length = uint8(v)
		return true
	} else if true {
		if _, ok := t.union15_.(*union_24_t); !ok {
			t.union15_ = &union_24_t{}
		}
		t.union15_.(*union_24_t).Length = uint8(v)
		return true
	}
	return false
}
func (t *Tcpoption) Mss() *uint16 {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return nil
	} else if t.Kind == TcpoptionKind_Nop {
		return nil
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		if _, ok := t.union15_.(*union_19_t); !ok {
			return nil // not set
		}
		tmp := uint16(t.union15_.(*union_19_t).Mss)
		return &tmp
	}
	return nil
}
func (t *Tcpoption) SetMss(v uint16) bool {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return false
	} else if t.Kind == TcpoptionKind_Nop {
		return false
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		if _, ok := t.union15_.(*union_19_t); !ok {
			t.union15_ = &union_19_t{}
		}
		t.union15_.(*union_19_t).Mss = uint16(v)
		return true
	}
	return false
}
func (t *Tcpoption) Sack() *Sack {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return nil
	} else if t.Kind == TcpoptionKind_Nop {
		return nil
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		return nil
	} else if t.Kind == TcpoptionKind_WindowScale {
		return nil
	} else if t.Kind == TcpoptionKind_SackPermitted {
		return nil
	} else if t.Kind == TcpoptionKind_Sack {
		if _, ok := t.union15_.(*union_22_t); !ok {
			return nil // not set
		}
		tmp := Sack(t.union15_.(*union_22_t).Sack)
		return &tmp
	}
	return nil
}
func (t *Tcpoption) SetSack(v Sack) bool {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return false
	} else if t.Kind == TcpoptionKind_Nop {
		return false
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		return false
	} else if t.Kind == TcpoptionKind_WindowScale {
		return false
	} else if t.Kind == TcpoptionKind_SackPermitted {
		return false
	} else if t.Kind == TcpoptionKind_Sack {
		if _, ok := t.union15_.(*union_22_t); !ok {
			t.union15_ = &union_22_t{}
		}
		t.union15_.(*union_22_t).Sack = Sack(v)
		return true
	}
	return false
}
func (t *Tcpoption) ShiftCount() *uint8 {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return nil
	} else if t.Kind == TcpoptionKind_Nop {
		return nil
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		return nil
	} else if t.Kind == TcpoptionKind_WindowScale {
		if _, ok := t.union15_.(*union_20_t); !ok {
			return nil // not set
		}
		tmp := uint8(t.union15_.(*union_20_t).ShiftCount)
		return &tmp
	}
	return nil
}
func (t *Tcpoption) SetShiftCount(v uint8) bool {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return false
	} else if t.Kind == TcpoptionKind_Nop {
		return false
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		return false
	} else if t.Kind == TcpoptionKind_WindowScale {
		if _, ok := t.union15_.(*union_20_t); !ok {
			t.union15_ = &union_20_t{}
		}
		t.union15_.(*union_20_t).ShiftCount = uint8(v)
		return true
	}
	return false
}
func (t *Tcpoption) Timestamp() *Timestamp {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return nil
	} else if t.Kind == TcpoptionKind_Nop {
		return nil
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		return nil
	} else if t.Kind == TcpoptionKind_WindowScale {
		return nil
	} else if t.Kind == TcpoptionKind_SackPermitted {
		return nil
	} else if t.Kind == TcpoptionKind_Sack {
		return nil
	} else if t.Kind == TcpoptionKind_Timestamp {
		if _, ok := t.union15_.(*union_23_t); !ok {
			return nil // not set
		}
		tmp := Timestamp(t.union15_.(*union_23_t).Timestamp)
		return &tmp
	}
	return nil
}
func (t *Tcpoption) SetTimestamp(v Timestamp) bool {
	if t.Kind == TcpoptionKind_EndOfOptionsList {
		return false
	} else if t.Kind == TcpoptionKind_Nop {
		return false
	} else if t.Kind == TcpoptionKind_MaximumSegmentSize {
		return false
	} else if t.Kind == TcpoptionKind_WindowScale {
		return false
	} else if t.Kind == TcpoptionKind_SackPermitted {
		return false
	} else if t.Kind == TcpoptionKind_Sack {
		return false
	} else if t.Kind == TcpoptionKind_Timestamp {
		if _, ok := t.union15_.(*union_23_t); !ok {
			t.union15_ = &union_23_t{}
		}
		t.union15_.(*union_23_t).Timestamp = Timestamp(v)
		return true
	}
	return false
}
func (t *Tcpoption) Visit(v VisitorJHZCL) {
	v.Visit(v, "Kind", &t.Kind)
	v.Visit(v, "Data", (t.Data()))
	v.Visit(v, "Length", (t.Length()))
	v.Visit(v, "Mss", (t.Mss()))
	v.Visit(v, "Sack", (t.Sack()))
	v.Visit(v, "ShiftCount", (t.ShiftCount()))
	v.Visit(v, "Timestamp", (t.Timestamp()))
}
func (t *Tcpoption) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *Tcpoption) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Kind)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Kind: %w", err)
	}
	switch {
	case (t.Kind == TcpoptionKind_EndOfOptionsList):
	case (t.Kind == TcpoptionKind_Nop):
	case (t.Kind == TcpoptionKind_MaximumSegmentSize):
		if _, ok := t.union15_.(*union_19_t); !ok {
			return fmt.Errorf("encode t.union15_: union is not set to union_19_t")
		}
		if n, err := w.Write([]byte{byte(t.union15_.(*union_19_t).Length)}); err != nil || n != 1 {
			return fmt.Errorf("encode t.union15_.(*union_19_t).Length: %w", err)
		}
		tmp25 := [2]byte{}
		binary.BigEndian.PutUint16(tmp25[:], uint16(t.union15_.(*union_19_t).Mss))
		if n, err := w.Write(tmp25[:]); err != nil || n != 2 {
			return fmt.Errorf("encode t.union15_.(*union_19_t).Mss: %w", err)
		}
	case (t.Kind == TcpoptionKind_WindowScale):
		if _, ok := t.union15_.(*union_20_t); !ok {
			return fmt.Errorf("encode t.union15_: union is not set to union_20_t")
		}
		if n, err := w.Write([]byte{byte(t.union15_.(*union_20_t).Length)}); err != nil || n != 1 {
			return fmt.Errorf("encode t.union15_.(*union_20_t).Length: %w", err)
		}
		if n, err := w.Write([]byte{byte(t.union15_.(*union_20_t).ShiftCount)}); err != nil || n != 1 {
			return fmt.Errorf("encode t.union15_.(*union_20_t).ShiftCount: %w", err)
		}
	case (t.Kind == TcpoptionKind_SackPermitted):
		if _, ok := t.union15_.(*union_21_t); !ok {
			return fmt.Errorf("encode t.union15_: union is not set to union_21_t")
		}
		if n, err := w.Write([]byte{byte(t.union15_.(*union_21_t).Length)}); err != nil || n != 1 {
			return fmt.Errorf("encode t.union15_.(*union_21_t).Length: %w", err)
		}
	case (t.Kind == TcpoptionKind_Sack):
		if _, ok := t.union15_.(*union_22_t); !ok {
			return fmt.Errorf("encode t.union15_: union is not set to union_22_t")
		}
		if n, err := w.Write([]byte{byte(t.union15_.(*union_22_t).Length)}); err != nil || n != 1 {
			return fmt.Errorf("encode t.union15_.(*union_22_t).Length: %w", err)
		}
		new_buf_26 := bytes.NewBuffer(nil)
		old_buf_26_w := w
		w = new_buf_26
		if err := t.union15_.(*union_22_t).Sack.Write(w); err != nil {
			return fmt.Errorf("encode Sack: %w", err)
		}
		if new_buf_26.Len() != int((t.union15_.(*union_22_t).Length - 2)) {
			return fmt.Errorf("encode Sack: expect %d bytes but got %d bytes", new_buf_26.Len(), int((t.union15_.(*union_22_t).Length - 2)))
		}
		_, err = new_buf_26.WriteTo(old_buf_26_w)
		if err != nil {
			return err
		}
		w = old_buf_26_w
	case (t.Kind == TcpoptionKind_Timestamp):
		if _, ok := t.union15_.(*union_23_t); !ok {
			return fmt.Errorf("encode t.union15_: union is not set to union_23_t")
		}
		if n, err := w.Write([]byte{byte(t.union15_.(*union_23_t).Length)}); err != nil || n != 1 {
			return fmt.Errorf("encode t.union15_.(*union_23_t).Length: %w", err)
		}
		new_buf_27 := bytes.NewBuffer(nil)
		old_buf_27_w := w
		w = new_buf_27
		if err := t.union15_.(*union_23_t).Timestamp.Write(w); err != nil {
			return fmt.Errorf("encode Timestamp: %w", err)
		}
		if new_buf_27.Len() != int((t.union15_.(*union_23_t).Length - 2)) {
			return fmt.Errorf("encode Timestamp: expect %d bytes but got %d bytes", new_buf_27.Len(), int((t.union15_.(*union_23_t).Length - 2)))
		}
		_, err = new_buf_27.WriteTo(old_buf_27_w)
		if err != nil {
			return err
		}
		w = old_buf_27_w
	default:
		if _, ok := t.union15_.(*union_24_t); !ok {
			return fmt.Errorf("encode t.union15_: union is not set to union_24_t")
		}
		if n, err := w.Write([]byte{byte(t.union15_.(*union_24_t).Length)}); err != nil || n != 1 {
			return fmt.Errorf("encode t.union15_.(*union_24_t).Length: %w", err)
		}
		len_Data := int((t.union15_.(*union_24_t).Length - 2))
		if len(t.union15_.(*union_24_t).Data) != len_Data {
			return fmt.Errorf("encode Data: expect %d bytes but got %d bytes", len_Data, len(t.union15_.(*union_24_t).Data))
		}
		if n, err := w.Write(t.union15_.(*union_24_t).Data); err != nil || n != len(t.union15_.(*union_24_t).Data) {
			return fmt.Errorf("encode Data: %w", err)
		}
	}
	return nil
}
func (t *Tcpoption) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 1))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Tcpoption) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Tcpoption) Read(r io.Reader) (err error) {
	tmpKind := [1]byte{}
	n_Kind, err := io.ReadFull(r, tmpKind[:])
	if err != nil {
		return fmt.Errorf("read Kind: expect 1 byte but read %d bytes: %w", n_Kind, err)
	}
	t.Kind = TcpoptionKind(tmpKind[0])
	switch {
	case (t.Kind == TcpoptionKind_EndOfOptionsList):
	case (t.Kind == TcpoptionKind_Nop):
	case (t.Kind == TcpoptionKind_MaximumSegmentSize):
		t.union15_ = &union_19_t{}
		tmpLength := [1]byte{}
		n_Length, err := io.ReadFull(r, tmpLength[:])
		if err != nil {
			return fmt.Errorf("read Length: expect 1 byte but read %d bytes: %w", n_Length, err)
		}
		t.union15_.(*union_19_t).Length = uint8(tmpLength[0])
		tmpMss := [2]byte{}
		n_Mss, err := io.ReadFull(r, tmpMss[:])
		if err != nil {
			return fmt.Errorf("read Mss: expect 2 bytes but read %d bytes: %w", n_Mss, err)
		}
		t.union15_.(*union_19_t).Mss = uint16(binary.BigEndian.Uint16(tmpMss[:]))
	case (t.Kind == TcpoptionKind_WindowScale):
		t.union15_ = &union_20_t{}
		tmpLength := [1]byte{}
		n_Length, err := io.ReadFull(r, tmpLength[:])
		if err != nil {
			return fmt.Errorf("read Length: expect 1 byte but read %d bytes: %w", n_Length, err)
		}
		t.union15_.(*union_20_t).Length = uint8(tmpLength[0])
		tmpShiftCount := [1]byte{}
		n_ShiftCount, err := io.ReadFull(r, tmpShiftCount[:])
		if err != nil {
			return fmt.Errorf("read ShiftCount: expect 1 byte but read %d bytes: %w", n_ShiftCount, err)
		}
		t.union15_.(*union_20_t).ShiftCount = uint8(tmpShiftCount[0])
	case (t.Kind == TcpoptionKind_SackPermitted):
		t.union15_ = &union_21_t{}
		tmpLength := [1]byte{}
		n_Length, err := io.ReadFull(r, tmpLength[:])
		if err != nil {
			return fmt.Errorf("read Length: expect 1 byte but read %d bytes: %w", n_Length, err)
		}
		t.union15_.(*union_21_t).Length = uint8(tmpLength[0])
	case (t.Kind == TcpoptionKind_Sack):
		t.union15_ = &union_22_t{}
		tmpLength := [1]byte{}
		n_Length, err := io.ReadFull(r, tmpLength[:])
		if err != nil {
			return fmt.Errorf("read Length: expect 1 byte but read %d bytes: %w", n_Length, err)
		}
		t.union15_.(*union_22_t).Length = uint8(tmpLength[0])
		sub_byte_len_Sack := int64((t.union15_.(*union_22_t).Length - 2))
		sub_byte_r_Sack := io.LimitReader(r, int64(sub_byte_len_Sack))
		tmp_old_r_Sack_28 := r
		r = sub_byte_r_Sack
		if err := t.union15_.(*union_22_t).Sack.Read(r); err != nil {
			return fmt.Errorf("read Sack: %w", err)
		}
		if sub_byte_r_Sack.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read Sack: expect %d bytes but got %d bytes", sub_byte_len_Sack, sub_byte_len_Sack-sub_byte_r_Sack.(*io.LimitedReader).N)
		}
		r = tmp_old_r_Sack_28
	case (t.Kind == TcpoptionKind_Timestamp):
		t.union15_ = &union_23_t{}
		tmpLength := [1]byte{}
		n_Length, err := io.ReadFull(r, tmpLength[:])
		if err != nil {
			return fmt.Errorf("read Length: expect 1 byte but read %d bytes: %w", n_Length, err)
		}
		t.union15_.(*union_23_t).Length = uint8(tmpLength[0])
		sub_byte_len_Timestamp := int64((t.union15_.(*union_23_t).Length - 2))
		sub_byte_r_Timestamp := io.LimitReader(r, int64(sub_byte_len_Timestamp))
		tmp_old_r_Timestamp_29 := r
		r = sub_byte_r_Timestamp
		if err := t.union15_.(*union_23_t).Timestamp.Read(r); err != nil {
			return fmt.Errorf("read Timestamp: %w", err)
		}
		if sub_byte_r_Timestamp.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("read Timestamp: expect %d bytes but got %d bytes", sub_byte_len_Timestamp, sub_byte_len_Timestamp-sub_byte_r_Timestamp.(*io.LimitedReader).N)
		}
		r = tmp_old_r_Timestamp_29
	default:
		t.union15_ = &union_24_t{}
		tmpLength := [1]byte{}
		n_Length, err := io.ReadFull(r, tmpLength[:])
		if err != nil {
			return fmt.Errorf("read Length: expect 1 byte but read %d bytes: %w", n_Length, err)
		}
		t.union15_.(*union_24_t).Length = uint8(tmpLength[0])
		len_Data := int((t.union15_.(*union_24_t).Length - 2))
		if len_Data != 0 {
			tmpData := make([]byte, len_Data)
			n_Data, err := io.ReadFull(r, tmpData[:])
			if err != nil {
				return fmt.Errorf("read Data: expect %d bytes but read %d bytes: %w", len_Data, n_Data, err)
			}
			t.union15_.(*union_24_t).Data = tmpData[:]
		} else {
			t.union15_.(*union_24_t).Data = nil
		}
	}
	return nil
}

func (t *Tcpoption) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Tcpoption) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Tcpoption: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Tcpheader) DataOffset() uint8 {
	return ((t.flags30 & 0xf0) >> 4)
}
func (t *Tcpheader) SetDataOffset(v uint8) bool {
	if v > 15 {
		return false
	}
	t.flags30 = (t.flags30 & ^uint8(0xf0)) | ((v & 0xf) << 4)
	return true
}
func (t *Tcpheader) Reserved() uint8 {
	return ((t.flags30 & 0x0f) >> 0)
}
func (t *Tcpheader) SetReserved(v uint8) bool {
	if v > 15 {
		return false
	}
	t.flags30 = (t.flags30 & ^uint8(0xf)) | ((v & 0xf) << 0)
	return true
}
func (t *Tcpheader) Cwr() bool {
	return ((t.flags31 & 0x80) >> 7) == 1
}
func (t *Tcpheader) SetCwr(v bool) {
	if v {
		t.flags31 |= uint8(0x80)
	} else {
		t.flags31 &= ^uint8(0x80)
	}
}
func (t *Tcpheader) Ece() bool {
	return ((t.flags31 & 0x40) >> 6) == 1
}
func (t *Tcpheader) SetEce(v bool) {
	if v {
		t.flags31 |= uint8(0x40)
	} else {
		t.flags31 &= ^uint8(0x40)
	}
}
func (t *Tcpheader) Urg() bool {
	return ((t.flags31 & 0x20) >> 5) == 1
}
func (t *Tcpheader) SetUrg(v bool) {
	if v {
		t.flags31 |= uint8(0x20)
	} else {
		t.flags31 &= ^uint8(0x20)
	}
}
func (t *Tcpheader) Ack() bool {
	return ((t.flags31 & 0x10) >> 4) == 1
}
func (t *Tcpheader) SetAck(v bool) {
	if v {
		t.flags31 |= uint8(0x10)
	} else {
		t.flags31 &= ^uint8(0x10)
	}
}
func (t *Tcpheader) Psh() bool {
	return ((t.flags31 & 0x08) >> 3) == 1
}
func (t *Tcpheader) SetPsh(v bool) {
	if v {
		t.flags31 |= uint8(0x8)
	} else {
		t.flags31 &= ^uint8(0x8)
	}
}
func (t *Tcpheader) Rst() bool {
	return ((t.flags31 & 0x04) >> 2) == 1
}
func (t *Tcpheader) SetRst(v bool) {
	if v {
		t.flags31 |= uint8(0x4)
	} else {
		t.flags31 &= ^uint8(0x4)
	}
}
func (t *Tcpheader) Syn() bool {
	return ((t.flags31 & 0x02) >> 1) == 1
}
func (t *Tcpheader) SetSyn(v bool) {
	if v {
		t.flags31 |= uint8(0x2)
	} else {
		t.flags31 &= ^uint8(0x2)
	}
}
func (t *Tcpheader) Fin() bool {
	return ((t.flags31 & 0x01) >> 0) == 1
}
func (t *Tcpheader) SetFin(v bool) {
	if v {
		t.flags31 |= uint8(0x1)
	} else {
		t.flags31 &= ^uint8(0x1)
	}
}
func (t *Tcpheader) Visit(v VisitorJHZCL) {
	v.Visit(v, "SrcPort", &t.SrcPort)
	v.Visit(v, "DstPort", &t.DstPort)
	v.Visit(v, "SeqNum", &t.SeqNum)
	v.Visit(v, "AckNum", &t.AckNum)
	v.Visit(v, "DataOffset", t.DataOffset())
	v.Visit(v, "Reserved", t.Reserved())
	v.Visit(v, "Cwr", (func() uint8 {
		if t.Cwr() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Ece", (func() uint8 {
		if t.Ece() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Urg", (func() uint8 {
		if t.Urg() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Ack", (func() uint8 {
		if t.Ack() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Psh", (func() uint8 {
		if t.Psh() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Rst", (func() uint8 {
		if t.Rst() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Syn", (func() uint8 {
		if t.Syn() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Fin", (func() uint8 {
		if t.Fin() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "WindowSize", &t.WindowSize)
	v.Visit(v, "Checksum", &t.Checksum)
	v.Visit(v, "UrgentPointer", &t.UrgentPointer)
	v.Visit(v, "Options", &t.Options)
}
func (t *Tcpheader) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *Tcpheader) Write(w io.Writer) (err error) {
	tmp32 := [2]byte{}
	binary.BigEndian.PutUint16(tmp32[:], uint16(t.SrcPort))
	if n, err := w.Write(tmp32[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.SrcPort: %w", err)
	}
	tmp33 := [2]byte{}
	binary.BigEndian.PutUint16(tmp33[:], uint16(t.DstPort))
	if n, err := w.Write(tmp33[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.DstPort: %w", err)
	}
	tmp34 := [4]byte{}
	binary.BigEndian.PutUint32(tmp34[:], uint32(t.SeqNum))
	if n, err := w.Write(tmp34[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.SeqNum: %w", err)
	}
	tmp35 := [4]byte{}
	binary.BigEndian.PutUint32(tmp35[:], uint32(t.AckNum))
	if n, err := w.Write(tmp35[:]); err != nil || n != 4 {
		return fmt.Errorf("encode t.AckNum: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.flags30)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.flags30: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.flags31)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.flags31: %w", err)
	}
	tmp36 := [2]byte{}
	binary.BigEndian.PutUint16(tmp36[:], uint16(t.WindowSize))
	if n, err := w.Write(tmp36[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.WindowSize: %w", err)
	}
	tmp37 := [2]byte{}
	binary.BigEndian.PutUint16(tmp37[:], uint16(t.Checksum))
	if n, err := w.Write(tmp37[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Checksum: %w", err)
	}
	tmp38 := [2]byte{}
	binary.BigEndian.PutUint16(tmp38[:], uint16(t.UrgentPointer))
	if n, err := w.Write(tmp38[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.UrgentPointer: %w", err)
	}
	new_buf_39 := bytes.NewBuffer(nil)
	old_buf_39_w := w
	w = new_buf_39
	for _, v := range t.Options {
		if err := v.Write(w); err != nil {
			return fmt.Errorf("encode Options: %w", err)
		}
	}
	if new_buf_39.Len() != int((uint8((t.DataOffset() * 4)) - 20)) {
		return fmt.Errorf("encode Options: expect %d bytes but got %d bytes", new_buf_39.Len(), int((uint8((t.DataOffset() * 4)) - 20)))
	}
	_, err = new_buf_39.WriteTo(old_buf_39_w)
	if err != nil {
		return err
	}
	w = old_buf_39_w
	return nil
}
func (t *Tcpheader) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 20))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Tcpheader) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Tcpheader) Read(r io.Reader) (err error) {
	tmpSrcPort := [2]byte{}
	n_SrcPort, err := io.ReadFull(r, tmpSrcPort[:])
	if err != nil {
		return fmt.Errorf("read SrcPort: expect 2 bytes but read %d bytes: %w", n_SrcPort, err)
	}
	t.SrcPort = uint16(binary.BigEndian.Uint16(tmpSrcPort[:]))
	tmpDstPort := [2]byte{}
	n_DstPort, err := io.ReadFull(r, tmpDstPort[:])
	if err != nil {
		return fmt.Errorf("read DstPort: expect 2 bytes but read %d bytes: %w", n_DstPort, err)
	}
	t.DstPort = uint16(binary.BigEndian.Uint16(tmpDstPort[:]))
	tmpSeqNum := [4]byte{}
	n_SeqNum, err := io.ReadFull(r, tmpSeqNum[:])
	if err != nil {
		return fmt.Errorf("read SeqNum: expect 4 bytes but read %d bytes: %w", n_SeqNum, err)
	}
	t.SeqNum = uint32(binary.BigEndian.Uint32(tmpSeqNum[:]))
	tmpAckNum := [4]byte{}
	n_AckNum, err := io.ReadFull(r, tmpAckNum[:])
	if err != nil {
		return fmt.Errorf("read AckNum: expect 4 bytes but read %d bytes: %w", n_AckNum, err)
	}
	t.AckNum = uint32(binary.BigEndian.Uint32(tmpAckNum[:]))
	tmpflags30 := [1]byte{}
	n_flags30, err := io.ReadFull(r, tmpflags30[:])
	if err != nil {
		return fmt.Errorf("read flags30: expect 1 byte but read %d bytes: %w", n_flags30, err)
	}
	t.flags30 = uint8(tmpflags30[0])
	tmpflags31 := [1]byte{}
	n_flags31, err := io.ReadFull(r, tmpflags31[:])
	if err != nil {
		return fmt.Errorf("read flags31: expect 1 byte but read %d bytes: %w", n_flags31, err)
	}
	t.flags31 = uint8(tmpflags31[0])
	tmpWindowSize := [2]byte{}
	n_WindowSize, err := io.ReadFull(r, tmpWindowSize[:])
	if err != nil {
		return fmt.Errorf("read WindowSize: expect 2 bytes but read %d bytes: %w", n_WindowSize, err)
	}
	t.WindowSize = uint16(binary.BigEndian.Uint16(tmpWindowSize[:]))
	tmpChecksum := [2]byte{}
	n_Checksum, err := io.ReadFull(r, tmpChecksum[:])
	if err != nil {
		return fmt.Errorf("read Checksum: expect 2 bytes but read %d bytes: %w", n_Checksum, err)
	}
	t.Checksum = uint16(binary.BigEndian.Uint16(tmpChecksum[:]))
	tmpUrgentPointer := [2]byte{}
	n_UrgentPointer, err := io.ReadFull(r, tmpUrgentPointer[:])
	if err != nil {
		return fmt.Errorf("read UrgentPointer: expect 2 bytes but read %d bytes: %w", n_UrgentPointer, err)
	}
	t.UrgentPointer = uint16(binary.BigEndian.Uint16(tmpUrgentPointer[:]))
	sub_byte_len_Options := int64((uint8((t.DataOffset() * 4)) - 20))
	sub_byte_r_Options := io.LimitReader(r, int64(sub_byte_len_Options))
	tmp_old_r_Options_40 := r
	r = sub_byte_r_Options
	len_Options := int(r.(*io.LimitedReader).N)
	tmpOptions := make([]byte, len_Options)
	n_Options, err := io.ReadFull(r, tmpOptions[:])
	if err != nil {
		return fmt.Errorf("read Options: expect %d bytes but read %d bytes: %w", len_Options, n_Options, err)
	}
	range_tmp_Options := bytes.NewReader(tmpOptions[:])
	tmp_old_r_Options := r
	r = range_tmp_Options
	for range_tmp_Options.Len() > 0 {
		var tmp41_ Tcpoption
		if err := tmp41_.Read(r); err != nil {
			return fmt.Errorf("read Options: %w", err)
		}
		t.Options = append(t.Options, tmp41_)
	}
	r = tmp_old_r_Options
	if sub_byte_r_Options.(*io.LimitedReader).N != 0 {
		return fmt.Errorf("read Options: expect %d bytes but got %d bytes", sub_byte_len_Options, sub_byte_len_Options-sub_byte_r_Options.(*io.LimitedReader).N)
	}
	r = tmp_old_r_Options_40
	return nil
}

func (t *Tcpheader) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Tcpheader) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Tcpheader: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Tcpsegment) Visit(v VisitorJHZCL) {
	v.Visit(v, "Hdr", &t.Hdr)
	v.Visit(v, "Payload", &t.Payload)
}
func (t *Tcpsegment) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *Tcpsegment) Write(w io.Writer) (err error) {
	if err := t.Hdr.Write(w); err != nil {
		return fmt.Errorf("encode Hdr: %w", err)
	}
	if n, err := w.Write(t.Payload); err != nil || n != len(t.Payload) {
		return fmt.Errorf("encode Payload: %w", err)
	}
	return nil
}
func (t *Tcpsegment) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 0))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Tcpsegment) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Tcpsegment) Read(r io.Reader) (err error) {
	if err := t.Hdr.Read(r); err != nil {
		return fmt.Errorf("read Hdr: %w", err)
	}
	bytes_buf_Payload := &bytes.Buffer{}
	if _, err := io.Copy(bytes_buf_Payload, r); err != nil {
		return err
	}
	t.Payload = bytes_buf_Payload.Bytes()
	return nil
}

func (t *Tcpsegment) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Tcpsegment) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Tcpsegment: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Frame) Visit(v VisitorJHZCL) {
	v.Visit(v, "Ether", &t.Ether)
	v.Visit(v, "Ipip", &t.Ipip)
	v.Visit(v, "Ipv4", &t.Ipv4)
	v.Visit(v, "Tcp", &t.Tcp)
}
func (t *Frame) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorJHZCLToMap(t))
}
func (t *Frame) Write(w io.Writer) (err error) {
	if err := t.Ether.Write(w); err != nil {
		return fmt.Errorf("encode Ether: %w", err)
	}
	if err := t.Ipip.Write(w); err != nil {
		return fmt.Errorf("encode Ipip: %w", err)
	}
	if err := t.Ipv4.Write(w); err != nil {
		return fmt.Errorf("encode Ipv4: %w", err)
	}
	if err := t.Tcp.Write(w); err != nil {
		return fmt.Errorf("encode Tcp: %w", err)
	}
	return nil
}
func (t *Frame) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 14))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Frame) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Frame) Read(r io.Reader) (err error) {
	if err := t.Ether.Read(r); err != nil {
		return fmt.Errorf("read Ether: %w", err)
	}
	if err := t.Ipip.Read(r); err != nil {
		return fmt.Errorf("read Ipip: %w", err)
	}
	if err := t.Ipv4.Read(r); err != nil {
		return fmt.Errorf("read Ipv4: %w", err)
	}
	if err := t.Tcp.Read(r); err != nil {
		return fmt.Errorf("read Tcp: %w", err)
	}
	return nil
}

func (t *Frame) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Frame) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Frame: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
